{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectLib",
    "version": "0.2.7-STABLE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectLib-0.2.7-STABLE.jar",
          "url": "ConnectLib-0.2.7-STABLE.jar",
          "size": 31430,
          "sha512": "3439951e3ababf76022e571bc3150df039670d116dbfd72990f43dfbee59f55a38bcdafcdbc542c6b42a46be202c1cf1e983801c51986dfafdfb42bb34cc72c8",
          "sha256": "56a9c711d1753806e1c84819c508a03c1be3b652dca82a9938003e9fdfdb8f0c",
          "sha1": "b2fe18c05fd82add5ccab96761e503a1d844ba49",
          "md5": "de532e5d47e285c6b6369591e77e5627"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "ConnectLib-0.2.7-STABLE.jar",
          "url": "ConnectLib-0.2.7-STABLE.jar",
          "size": 31430,
          "sha512": "3439951e3ababf76022e571bc3150df039670d116dbfd72990f43dfbee59f55a38bcdafcdbc542c6b42a46be202c1cf1e983801c51986dfafdfb42bb34cc72c8",
          "sha256": "56a9c711d1753806e1c84819c508a03c1be3b652dca82a9938003e9fdfdb8f0c",
          "sha1": "b2fe18c05fd82add5ccab96761e503a1d844ba49",
          "md5": "de532e5d47e285c6b6369591e77e5627"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectLib-0.2.7-STABLE-sources.jar",
          "url": "ConnectLib-0.2.7-STABLE-sources.jar",
          "size": 17862,
          "sha512": "4d31935dfb9fb4dbb7c12d3d30ea3a29ac14f97206f9d926e29164b88f3f6dbc652d9bd1996bb42559cb953e91e354578d56cbb39ab9401878bfce85e9658368",
          "sha256": "c1085feedff408e9f067bb56c638cf565e60838b2b26286fe23bd6ac3c4afe2f",
          "sha1": "5cef97c41cb17454d45617aabe6d652fff077a48",
          "md5": "3edfb22ac879f2ca48aeda4e4a2ed1d2"
        }
      ]
    }
  ]
}
