{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectLib",
    "version": "0.4.8-STABLE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectLib-0.4.8-STABLE.jar",
          "url": "ConnectLib-0.4.8-STABLE.jar",
          "size": 65830,
          "sha512": "7df931b5e677ee68ff26e1fd75c1fba49e79755ca7d3374c473bd8540192e989e24e9ad5ba88d4f64a4a01c126fa4b9be0b8921a244eb7d4a936acab8ea63286",
          "sha256": "2e33e784cab89475512bed34ba1d7b4e8bf11c4aedcc4263811972f6577f99e8",
          "sha1": "38593822f14d116cf776dc7e70d59e5ba5edf023",
          "md5": "9fdce2b10a39188deddecfc936a7ff69"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "ConnectLib-0.4.8-STABLE.jar",
          "url": "ConnectLib-0.4.8-STABLE.jar",
          "size": 65830,
          "sha512": "7df931b5e677ee68ff26e1fd75c1fba49e79755ca7d3374c473bd8540192e989e24e9ad5ba88d4f64a4a01c126fa4b9be0b8921a244eb7d4a936acab8ea63286",
          "sha256": "2e33e784cab89475512bed34ba1d7b4e8bf11c4aedcc4263811972f6577f99e8",
          "sha1": "38593822f14d116cf776dc7e70d59e5ba5edf023",
          "md5": "9fdce2b10a39188deddecfc936a7ff69"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectLib-0.4.8-STABLE-sources.jar",
          "url": "ConnectLib-0.4.8-STABLE-sources.jar",
          "size": 39701,
          "sha512": "4c1c96ba1e7be6d877e281b207adf2de3860e996e89fb9fe03da26f7ddb4d1d40b9a3e13d3f45aface588cadcd17b4319339dee9a57bcea6b178d253ae70147e",
          "sha256": "364c47b62fce662a1b7971638742f658e35fea6843b7b94279348aa5d2984a96",
          "sha1": "56349f3742b07f7f7abd0124bb7e2abc8fdf7af0",
          "md5": "6a88b1dba8dffdbdb68e76a22ee0fc3f"
        }
      ]
    }
  ]
}
