{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectorAPI",
    "version": "0.2.0-Alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.2.0-Alpha.jar",
          "url": "ConnectorAPI-0.2.0-Alpha.jar",
          "size": 24711,
          "sha512": "85954f17fed35d653367f8ca970dee257da94241b856656c4319a0309795a5fa6b6d3803ed7211dc0caf91ba9a1b9503998535fba0b00867b1922926a57e95e7",
          "sha256": "cdc06750188eec8312d45d2f23f9c8cf5e43db1a4226fcfa678d955bf89db15b",
          "sha1": "413be6f3c2df2ca2610e2c431ae42bcbfc56a8e2",
          "md5": "46bb635a9e6c4d2a10367f7d5a311bb3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-base",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-base",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-graphics",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-graphics",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-controls",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-controls",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-fxml",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-fxml",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "ConnectorAPI-0.2.0-Alpha.jar",
          "url": "ConnectorAPI-0.2.0-Alpha.jar",
          "size": 24711,
          "sha512": "85954f17fed35d653367f8ca970dee257da94241b856656c4319a0309795a5fa6b6d3803ed7211dc0caf91ba9a1b9503998535fba0b00867b1922926a57e95e7",
          "sha256": "cdc06750188eec8312d45d2f23f9c8cf5e43db1a4226fcfa678d955bf89db15b",
          "sha1": "413be6f3c2df2ca2610e2c431ae42bcbfc56a8e2",
          "md5": "46bb635a9e6c4d2a10367f7d5a311bb3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.2.0-Alpha-sources.jar",
          "url": "ConnectorAPI-0.2.0-Alpha-sources.jar",
          "size": 13681,
          "sha512": "0b8c5c719d195454fe946caad9b5bc5691130b7403a6b32f54a3320aec5714ce98d974299ad90a6a4909f4c663f27088935bfab68d914defe3b40eb214d28c63",
          "sha256": "1fa5dbc4bae12bd4fd602720da1ec8ead116b7a0c402af62c65dcfb3a79a1e55",
          "sha1": "67e118a9c720fc323840d47c500509f3bbda3311",
          "md5": "f5267f1d8daf10c1faceb01dd302e388"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.2.0-Alpha-javadoc.jar",
          "url": "ConnectorAPI-0.2.0-Alpha-javadoc.jar",
          "size": 143946,
          "sha512": "4da384e7fe0b9121ff3ff4a40a6374d1926ee214a33289c23a3c754dab641dba0d28b172790232a27532fd516a8afbeeb02b709c03f5aa80b2bb3dc69c95e6ca",
          "sha256": "db0ddb447df33b7a5459093d5b6815f13b92991ff1c1edf2fb18112a963fa3be",
          "sha1": "f47b17605b52f5e4646f54f5a1a95e1bef02aad0",
          "md5": "62cc88f5880576cb391018163dfc12c8"
        }
      ]
    }
  ]
}
