{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectLib",
    "version": "0.2.7.2-STABLE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectLib-0.2.7.2-STABLE.jar",
          "url": "ConnectLib-0.2.7.2-STABLE.jar",
          "size": 31979,
          "sha512": "8983beda3bba77cfe7954149fea1b327f278840418d2759fd8b16ee739bbd818c12a4add3ffc0aef4878a636607a3d04018428eb678d8ed571ce57d669e3796c",
          "sha256": "c0e7baaa0bad8dfcfddac1c6ec4f6da3b51289ff11af10b3895f9bee65343f65",
          "sha1": "05cd519e9bf9ce65c6101e29c3774b7d162ddee3",
          "md5": "7fc6ebe14e14345c7c041738da9ac06a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "ConnectLib-0.2.7.2-STABLE.jar",
          "url": "ConnectLib-0.2.7.2-STABLE.jar",
          "size": 31979,
          "sha512": "8983beda3bba77cfe7954149fea1b327f278840418d2759fd8b16ee739bbd818c12a4add3ffc0aef4878a636607a3d04018428eb678d8ed571ce57d669e3796c",
          "sha256": "c0e7baaa0bad8dfcfddac1c6ec4f6da3b51289ff11af10b3895f9bee65343f65",
          "sha1": "05cd519e9bf9ce65c6101e29c3774b7d162ddee3",
          "md5": "7fc6ebe14e14345c7c041738da9ac06a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectLib-0.2.7.2-STABLE-sources.jar",
          "url": "ConnectLib-0.2.7.2-STABLE-sources.jar",
          "size": 17935,
          "sha512": "c7d870ffd2f74bf71d34c5c0a7cb4cfbdc026e116f2e7d3271f6342240bc9b79383784506b292fccd6c66997c2e1d714eb2f59f686d2ded29dc4067750abe8a0",
          "sha256": "f18bb029fc4ac62c8e68b85b12caa2357a8b00e31ed8068b110d9f9d3bf8591a",
          "sha1": "9ccdabcdc8ffbfc3814d59cac5d22cf63aa7bb77",
          "md5": "510860f8225a32ab23079de50c68e601"
        }
      ]
    }
  ]
}
