{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectLib",
    "version": "0.2.7.2-STABLE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectLib-0.2.7.2-STABLE.jar",
          "url": "ConnectLib-0.2.7.2-STABLE.jar",
          "size": 31977,
          "sha512": "5ce7702ad118f14cea1c2144839a1c7b49e05e57d7756dbf0c2f90ccc05da3cce65989435e4f473b66ab6ca44a3b584150ffe8982dea31e057535eea7b47888b",
          "sha256": "f17dccba53f6ef442f0813494b2e17d4e49fc353126fc9e8776d4547313fe3f8",
          "sha1": "abef86e3995d042eaec52c83c187b59e02e3d508",
          "md5": "fc279dd1394919cf54fd476e20c5ef8d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "ConnectLib-0.2.7.2-STABLE.jar",
          "url": "ConnectLib-0.2.7.2-STABLE.jar",
          "size": 31977,
          "sha512": "5ce7702ad118f14cea1c2144839a1c7b49e05e57d7756dbf0c2f90ccc05da3cce65989435e4f473b66ab6ca44a3b584150ffe8982dea31e057535eea7b47888b",
          "sha256": "f17dccba53f6ef442f0813494b2e17d4e49fc353126fc9e8776d4547313fe3f8",
          "sha1": "abef86e3995d042eaec52c83c187b59e02e3d508",
          "md5": "fc279dd1394919cf54fd476e20c5ef8d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectLib-0.2.7.2-STABLE-sources.jar",
          "url": "ConnectLib-0.2.7.2-STABLE-sources.jar",
          "size": 17938,
          "sha512": "dacecb645703c13a73fb45867e1a8751b3d328af6db4f136cf9b240b830f62eab7c196a9981f2ba30aa4c7375da5e4df9b40c5661904aa2f6842eb6498d6eccb",
          "sha256": "49b3a0e479e446824795cb4efb067248063772f8182b0b3481ec57ea45da22b7",
          "sha1": "ab8f38c7eacb84097ee448cc77166bb6d3dd1527",
          "md5": "de86998e0000710ef52360087277f140"
        }
      ]
    }
  ]
}
