{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectorAPI",
    "version": "0.1.4-STABLE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.4-STABLE.jar",
          "url": "ConnectorAPI-0.1.4-STABLE.jar",
          "size": 25740,
          "sha512": "8ab2be2e414ebcb80df7eac783cbd8501b1cb2ef4aaa948029d34cf1397c76d8ce199727934f742c747acdc55fc903c0c2db876fc1618619b4215afb47ec4a56",
          "sha256": "6f9d979a1988d8068d67881cb0546809c6b0dbb8188054081b87789bd6e68643",
          "sha1": "5018697a6393296cb9120f30d5b976735b73a92e",
          "md5": "c4696bb8431f91697bf9019568f563cf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-base",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-base",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-graphics",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-graphics",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-controls",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-controls",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-fxml",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-fxml",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "ConnectorAPI-0.1.4-STABLE.jar",
          "url": "ConnectorAPI-0.1.4-STABLE.jar",
          "size": 25740,
          "sha512": "8ab2be2e414ebcb80df7eac783cbd8501b1cb2ef4aaa948029d34cf1397c76d8ce199727934f742c747acdc55fc903c0c2db876fc1618619b4215afb47ec4a56",
          "sha256": "6f9d979a1988d8068d67881cb0546809c6b0dbb8188054081b87789bd6e68643",
          "sha1": "5018697a6393296cb9120f30d5b976735b73a92e",
          "md5": "c4696bb8431f91697bf9019568f563cf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.4-STABLE-sources.jar",
          "url": "ConnectorAPI-0.1.4-STABLE-sources.jar",
          "size": 14656,
          "sha512": "f7f870654f48119947dfdc1a49394e67d3102f55989d8d42142b1c5af142f3700e1b03d18e8420ff14e88eddc0083b29bf8f0dfdf79cd49a4fb57d45e0e269f2",
          "sha256": "db01f9f6d166b378913bce3b7165d81873705e6570817f6a5657e991158d6609",
          "sha1": "840c7557168905dcb3977b3aacb53f9a44d8d3cd",
          "md5": "24d486d8c74064e04f19aacaa3d14d23"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.4-STABLE-javadoc.jar",
          "url": "ConnectorAPI-0.1.4-STABLE-javadoc.jar",
          "size": 145196,
          "sha512": "fd5576a822cc754d3efa37f59cc72a91b1cdc0fe17d82ba7194fc217d1095c4fada5edd4b95797a3d04c64c65d5777396279371ebce3c5953bc487b9a4ba9143",
          "sha256": "e33248d5d0602af1b0d42454774f50a9009cf6387377aaf769a6710c9c3e8049",
          "sha1": "75c4edbb17383249960576d750b837ee6540a2ab",
          "md5": "29fde5c4ee5146c628b2f02a6d26191e"
        }
      ]
    }
  ]
}
