{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectorAPI",
    "version": "0.1.4-STABLE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.4-STABLE.jar",
          "url": "ConnectorAPI-0.1.4-STABLE.jar",
          "size": 25925,
          "sha512": "6ddaecac43e3eb6cbe5124e3878a00c943fe67b8a2564b2cffc9cce518d1d6ff8402b792064acaad96481f1654ca64455f9a91363f9b82f3bbee57f802f21142",
          "sha256": "6dae1d8c3636e30fcb883d6c5aa94955d3a3a2dd9a14d25e3d79d89889084aa1",
          "sha1": "67f935cbc2c6e61aa1501de27ae96362a4c01bf8",
          "md5": "d9a9a3dc2349c45094e89357ad4b21c8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-base",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-base",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-graphics",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-graphics",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-controls",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-controls",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-fxml",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-fxml",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "ConnectorAPI-0.1.4-STABLE.jar",
          "url": "ConnectorAPI-0.1.4-STABLE.jar",
          "size": 25925,
          "sha512": "6ddaecac43e3eb6cbe5124e3878a00c943fe67b8a2564b2cffc9cce518d1d6ff8402b792064acaad96481f1654ca64455f9a91363f9b82f3bbee57f802f21142",
          "sha256": "6dae1d8c3636e30fcb883d6c5aa94955d3a3a2dd9a14d25e3d79d89889084aa1",
          "sha1": "67f935cbc2c6e61aa1501de27ae96362a4c01bf8",
          "md5": "d9a9a3dc2349c45094e89357ad4b21c8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.4-STABLE-sources.jar",
          "url": "ConnectorAPI-0.1.4-STABLE-sources.jar",
          "size": 14855,
          "sha512": "af2726c95b44cb6eb074be05818dd54ef9f4988fab9c4194787d67b714b3351a7df756a2ab603607df50934652d58babcc61fb312cb6f89346a19d70ae13a5af",
          "sha256": "2d5ed28993825f7d7a4d02d8b46893981239f7edc0313500c40462450a05ebbb",
          "sha1": "0f3d26ed75a7159c5bfa587ec0dfd7cc6ce29f2f",
          "md5": "a2320a4c67ec8cc1fb4cc0cf431a1f94"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.4-STABLE-javadoc.jar",
          "url": "ConnectorAPI-0.1.4-STABLE-javadoc.jar",
          "size": 145594,
          "sha512": "3b489e510e376f7e78bd4972f299ebcb65d1ace9b8948cc7fb57fb20ca709ac87093f221d67c9589350f37d3d919a3cec6a6b523945b5e8e6ff2f00d7d90f7c6",
          "sha256": "39fd157cec5c3dd001b73e5122b18ac340ca1d317253b36a8199a4c8694d7e29",
          "sha1": "6a88ffb40599a18d61f55f2e38c09ab68d659efb",
          "md5": "6ac90fa7d82b137c7229730b56b4c7ec"
        }
      ]
    }
  ]
}
