{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectLib",
    "version": "0.4.8.2-STABLE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectLib-0.4.8.2-STABLE.jar",
          "url": "ConnectLib-0.4.8.2-STABLE.jar",
          "size": 62109,
          "sha512": "00782a878dd4bed9a423811ffa3756bbe0a2c0f121eeac1707e73d606ccd938784845f7a0131741264a53c3db76dc8b34017ee86c825882ff5ebde8852b15ad9",
          "sha256": "61cec510f42a1038540e6e06859cfa7e5e8573f27dada0b4cac5dbafd738faaa",
          "sha1": "31e46d7cd4e044ec572b7ab390608c7a7edcd8fb",
          "md5": "8575c11caec5afec5fb9217573cc64f4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "ConnectLib-0.4.8.2-STABLE.jar",
          "url": "ConnectLib-0.4.8.2-STABLE.jar",
          "size": 62109,
          "sha512": "00782a878dd4bed9a423811ffa3756bbe0a2c0f121eeac1707e73d606ccd938784845f7a0131741264a53c3db76dc8b34017ee86c825882ff5ebde8852b15ad9",
          "sha256": "61cec510f42a1038540e6e06859cfa7e5e8573f27dada0b4cac5dbafd738faaa",
          "sha1": "31e46d7cd4e044ec572b7ab390608c7a7edcd8fb",
          "md5": "8575c11caec5afec5fb9217573cc64f4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectLib-0.4.8.2-STABLE-sources.jar",
          "url": "ConnectLib-0.4.8.2-STABLE-sources.jar",
          "size": 35591,
          "sha512": "85799e4b26e65835cc546feb874900299ffae42dc2eab94b6de1b99aa00f17a6f9faed34e659356ebdb9a5add14df330a1bcab042fffab383eab33256d930347",
          "sha256": "cdd56ec89b044c053d019df000a9b5535794e268cadd68da0ae27267fe61854e",
          "sha1": "924d277fd7fee255430b666061bfc58186684912",
          "md5": "d08dc702a7dc50a9f607c0d56295444e"
        }
      ]
    }
  ]
}
