{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectLib",
    "version": "0.2.6.2-STABLE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectLib-0.2.6.2-STABLE.jar",
          "url": "ConnectLib-0.2.6.2-STABLE.jar",
          "size": 26865,
          "sha512": "87e58adef2f6024e2f0282f9988d2698b80f7cbdd50e9d3f254487173717a042b4065c8ddaf6eb003374e13efdf42f48d3c400a81d7b2324a4f16c51bbde61aa",
          "sha256": "95933a101240db9a94082fb28211127e671cc9383e0fa5f64b0687e4ed103c21",
          "sha1": "3b6e82b3ffc199dcd2917a3f213137e60de6d990",
          "md5": "0df0489d216bf8f53b0bb6cb88aa95c2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "ConnectLib-0.2.6.2-STABLE.jar",
          "url": "ConnectLib-0.2.6.2-STABLE.jar",
          "size": 26865,
          "sha512": "87e58adef2f6024e2f0282f9988d2698b80f7cbdd50e9d3f254487173717a042b4065c8ddaf6eb003374e13efdf42f48d3c400a81d7b2324a4f16c51bbde61aa",
          "sha256": "95933a101240db9a94082fb28211127e671cc9383e0fa5f64b0687e4ed103c21",
          "sha1": "3b6e82b3ffc199dcd2917a3f213137e60de6d990",
          "md5": "0df0489d216bf8f53b0bb6cb88aa95c2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectLib-0.2.6.2-STABLE-sources.jar",
          "url": "ConnectLib-0.2.6.2-STABLE-sources.jar",
          "size": 15811,
          "sha512": "fac5b07b5165fe0c1c4ed8439aca0d43c6b33b703f80579bf59c62100de7aaf6f6c16351adf469ad34543c63c67c4d6661549371d11709d2f27c4fc68d26c2b5",
          "sha256": "06b6b924237cb0f42da2232fee341ebac819b2a647995d6eb648c4fc3cb687b6",
          "sha1": "bdbf906e817b0e3066d78df652cb9ad5a3edf75b",
          "md5": "121e8e3842c44575416d523ca13e0e74"
        }
      ]
    }
  ]
}
