{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectLib",
    "version": "0.2.6.2-STABLE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectLib-0.2.6.2-STABLE.jar",
          "url": "ConnectLib-0.2.6.2-STABLE.jar",
          "size": 26865,
          "sha512": "9eb7461d5989e5b8f9363c1f49cd3d1f6bad2f3ca04cf7eabd70d0bd970fe670e84578523689d3c559deae2e3c0c405e554f2de4a7d5777e1f1d7abc1803796e",
          "sha256": "a6e30d7a38739fae2ab5443b2198ac4594b0b79eeebd2cb98a825c3d68ffdbcb",
          "sha1": "ecfc5d62d5ab890da0bb3fdcef4bbf3c38da3756",
          "md5": "e22a19a59daea357c919bfac099a8157"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "ConnectLib-0.2.6.2-STABLE.jar",
          "url": "ConnectLib-0.2.6.2-STABLE.jar",
          "size": 26865,
          "sha512": "9eb7461d5989e5b8f9363c1f49cd3d1f6bad2f3ca04cf7eabd70d0bd970fe670e84578523689d3c559deae2e3c0c405e554f2de4a7d5777e1f1d7abc1803796e",
          "sha256": "a6e30d7a38739fae2ab5443b2198ac4594b0b79eeebd2cb98a825c3d68ffdbcb",
          "sha1": "ecfc5d62d5ab890da0bb3fdcef4bbf3c38da3756",
          "md5": "e22a19a59daea357c919bfac099a8157"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectLib-0.2.6.2-STABLE-sources.jar",
          "url": "ConnectLib-0.2.6.2-STABLE-sources.jar",
          "size": 15811,
          "sha512": "17621c92b222bcf324187657f4d64aa110330ef40040ec38ba640951a7c0b4f16629e79bd3025219787c1e2b26b2966c60cb3880131e2126998531ecf79e805e",
          "sha256": "31d822ee5c55e12de572b68eee7e98143cce7ca6e9fcb6554dc9afabbc2eb95b",
          "sha1": "2d696e33bd49b5a88718478fdc840a427ad94290",
          "md5": "a785709ac00a99aa34e97e2d9256f572"
        }
      ]
    }
  ]
}
