{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectLib",
    "version": "0.2.6.2-STABLE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectLib-0.2.6.2-STABLE.jar",
          "url": "ConnectLib-0.2.6.2-STABLE.jar",
          "size": 26865,
          "sha512": "e7c0bce9a2a927b043ae9c802653f7ec4d8c6a5e1c84c8228fb0385f2b33941dcfa0d363b6908caa8c2c72943a8c5eb0d131c46f0d1af01c68bafca4b3f17f88",
          "sha256": "18c05bb11f93100c3002f5767a3d5f6cef591c063af8353dd809b0b2461b4fb1",
          "sha1": "67f5cf2c531051eb00be191b4298fd5749542962",
          "md5": "c305d764f92f98ff8fc1e86fe380b521"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "ConnectLib-0.2.6.2-STABLE.jar",
          "url": "ConnectLib-0.2.6.2-STABLE.jar",
          "size": 26865,
          "sha512": "e7c0bce9a2a927b043ae9c802653f7ec4d8c6a5e1c84c8228fb0385f2b33941dcfa0d363b6908caa8c2c72943a8c5eb0d131c46f0d1af01c68bafca4b3f17f88",
          "sha256": "18c05bb11f93100c3002f5767a3d5f6cef591c063af8353dd809b0b2461b4fb1",
          "sha1": "67f5cf2c531051eb00be191b4298fd5749542962",
          "md5": "c305d764f92f98ff8fc1e86fe380b521"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectLib-0.2.6.2-STABLE-sources.jar",
          "url": "ConnectLib-0.2.6.2-STABLE-sources.jar",
          "size": 15811,
          "sha512": "73a686f5452ac4d142fec923a8d5209fec87eb234679caa013154440e5803fa32bb2b57d137d3eeff68f1b2346186300a1af393ab5ed8f24526155b3135ae7d1",
          "sha256": "208b26934a70a6f15d66c9c655e8649c98fa87978f3ce5652ace6d0187d2f2cb",
          "sha1": "12ec22659bdac3cb290b103ceff0ff21852711b6",
          "md5": "435791c448648cc7f05b1fe14efd926c"
        }
      ]
    }
  ]
}
