{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectorAPI",
    "version": "0.1.3.14-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.14-SNAPSHOT.jar",
          "url": "ConnectorAPI-0.1.3.14-SNAPSHOT.jar",
          "size": 30635,
          "sha512": "c0a81f28bc529f651efd0f7429820e54fbd824874cd1d5c52f67a7f3676ec4566fd404654ed42c9f5bb9631f64a4b71e90f476bc74f540def0ffab81373ef191",
          "sha256": "dbad14b825ee63747616818b89dd8b1e5b562c2fe54ba9b2749abf6c54208c06",
          "sha1": "ce1f1b0b8cc4ff4cb8adfa70488244363fcf4bd2",
          "md5": "9927bcb70eaf322d8c6f1741008197c3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-base",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-base",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-graphics",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-graphics",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-controls",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-controls",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-fxml",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-fxml",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.14-SNAPSHOT.jar",
          "url": "ConnectorAPI-0.1.3.14-SNAPSHOT.jar",
          "size": 30635,
          "sha512": "c0a81f28bc529f651efd0f7429820e54fbd824874cd1d5c52f67a7f3676ec4566fd404654ed42c9f5bb9631f64a4b71e90f476bc74f540def0ffab81373ef191",
          "sha256": "dbad14b825ee63747616818b89dd8b1e5b562c2fe54ba9b2749abf6c54208c06",
          "sha1": "ce1f1b0b8cc4ff4cb8adfa70488244363fcf4bd2",
          "md5": "9927bcb70eaf322d8c6f1741008197c3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.14-SNAPSHOT-sources.jar",
          "url": "ConnectorAPI-0.1.3.14-SNAPSHOT-sources.jar",
          "size": 17698,
          "sha512": "f51fb64271bdd9f0770c5a6c4e492d6bc7cd755ffee92225acad6633f245ab58c201bd948fa910aef3140070237fd7f38853c0c84b4e37a8931f53b90d3f7af1",
          "sha256": "41d1570c3e84c396eb812b8056fbb50fe00a96742cdf4cdde9d265c861367c22",
          "sha1": "5bdf07a1118b11a1df62e7257c1ec438d58b7a5a",
          "md5": "b507c3ec269120eeeeb0b8c10db5ac9c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.14-SNAPSHOT-javadoc.jar",
          "url": "ConnectorAPI-0.1.3.14-SNAPSHOT-javadoc.jar",
          "size": 152604,
          "sha512": "d776eb7ea51ba8d93e43f00a952f393ad054e687b2bf56a722d93da4bec9aac6d761ef9c479c0a8871d64b7ee5df082f19d413188ec37d126702d242d93c5743",
          "sha256": "96c58f16d6ecbede929bcc99607471da7748b54bad2b3ebb1ff5ed3ca03b04bb",
          "sha1": "aa55af269adb73a72dc5c878ddfca3703b938ada",
          "md5": "d62fb0c70a2a65497cc56bbe42e619f6"
        }
      ]
    }
  ]
}
