{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectorAPI",
    "version": "0.1.7.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.7.0-SNAPSHOT.jar",
          "url": "ConnectorAPI-0.1.7.0-SNAPSHOT.jar",
          "size": 30321,
          "sha512": "673d219cf35f216ed513717da46ae36fbd8f64da34f5d0955ad7d8f72ea609bffc2b9ff42dd56060a4abed2868944b00d45f993d86ebec6724d95391fc47c329",
          "sha256": "dfb17e7baac123291172f8f452bbe50bbcd1d22c3921db08e6411255b0ac1c0f",
          "sha1": "76873c4585142a0f0ef9e17ecbb0613d9ee13dd7",
          "md5": "ce0ae485d5134b6c9f2d1fc3118c1416"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "ConnectorAPI-0.1.7.0-SNAPSHOT.jar",
          "url": "ConnectorAPI-0.1.7.0-SNAPSHOT.jar",
          "size": 30321,
          "sha512": "673d219cf35f216ed513717da46ae36fbd8f64da34f5d0955ad7d8f72ea609bffc2b9ff42dd56060a4abed2868944b00d45f993d86ebec6724d95391fc47c329",
          "sha256": "dfb17e7baac123291172f8f452bbe50bbcd1d22c3921db08e6411255b0ac1c0f",
          "sha1": "76873c4585142a0f0ef9e17ecbb0613d9ee13dd7",
          "md5": "ce0ae485d5134b6c9f2d1fc3118c1416"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.7.0-SNAPSHOT-sources.jar",
          "url": "ConnectorAPI-0.1.7.0-SNAPSHOT-sources.jar",
          "size": 16543,
          "sha512": "1faa74d77358fed2cf862374f1f5851b5f0a950615a0d2597d847be4a53ab975e378bc878f29310fb355118648b64f9172a3dd7b43f30bed1b6a7a81978c9f0e",
          "sha256": "c14213251a366f1d2df643f633778de2fc095d801072bb4639c67b1b8728f641",
          "sha1": "bc2047812e6526a3584922de4a728d74e7825af1",
          "md5": "659082dbd6d7dfbc21fda6d09471267f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.7.0-SNAPSHOT-javadoc.jar",
          "url": "ConnectorAPI-0.1.7.0-SNAPSHOT-javadoc.jar",
          "size": 154124,
          "sha512": "d2282672d9e839be66aa5100be56525b4d392f0d51a272f81c52b16221ea5b7e77b1627ac024891c6cd4f302c424f49db9c2ec51858aa3b798d5cebe29a7326f",
          "sha256": "817eb7ed444197311a532b6ba43579778e5a56370bbcaa8de037ba136a6b9e8b",
          "sha1": "681400333e2827c31d8c27f66c226adc4ef0128b",
          "md5": "f5b1d3dee6571e8ad616071fa4693279"
        }
      ]
    }
  ]
}
