{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectorAPI",
    "version": "0.1.7.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.7.0-SNAPSHOT.jar",
          "url": "ConnectorAPI-0.1.7.0-SNAPSHOT.jar",
          "size": 25478,
          "sha512": "a0cb6d975f15b5c143d4bcfd7cc5d158720ceeea73ea204f69acecf6ae1885a0718b3b8d212fdcba65cc72ad881192fb34157375c071e2b7efdee2ac397351b6",
          "sha256": "2a55137fcb6801ad27a7fcdc9af72f2ceb523cefc8ab723cabc375c167ff96b8",
          "sha1": "1d30138d6dcc91fa7acf7c0d18b6a52dd469bb85",
          "md5": "a1747b1ac7537a0fd560e6b6218ad8db"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "ConnectorAPI-0.1.7.0-SNAPSHOT.jar",
          "url": "ConnectorAPI-0.1.7.0-SNAPSHOT.jar",
          "size": 25478,
          "sha512": "a0cb6d975f15b5c143d4bcfd7cc5d158720ceeea73ea204f69acecf6ae1885a0718b3b8d212fdcba65cc72ad881192fb34157375c071e2b7efdee2ac397351b6",
          "sha256": "2a55137fcb6801ad27a7fcdc9af72f2ceb523cefc8ab723cabc375c167ff96b8",
          "sha1": "1d30138d6dcc91fa7acf7c0d18b6a52dd469bb85",
          "md5": "a1747b1ac7537a0fd560e6b6218ad8db"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.7.0-SNAPSHOT-sources.jar",
          "url": "ConnectorAPI-0.1.7.0-SNAPSHOT-sources.jar",
          "size": 14649,
          "sha512": "3110a5d403d19f37b1eced4620553c6ddcc18931929a171ff5d2c5a2972501c22c0a2783fe93b177cedb50b2e214b7d60d01156dbce4c32f00cfa01536dd3284",
          "sha256": "68af7c61f5b66fa68136b2c7f250ee0c9030a53333a226f604b15b332346b30b",
          "sha1": "2a0892677805563a0bd35263c2f294217eba44a0",
          "md5": "a10b638719fb9546181c004148fe01b8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.7.0-SNAPSHOT-javadoc.jar",
          "url": "ConnectorAPI-0.1.7.0-SNAPSHOT-javadoc.jar",
          "size": 145259,
          "sha512": "959633bb9fdb8aae1af24a4a569ca6fd98ed0c12e8fcc917b46dd719d42635c4aab13fbf3614849c228740cd3b3783aec1590d0dd1bd471e791eb51be9efe40e",
          "sha256": "91b8b4af9d53049de329bbeac97b3c474fc84e747c05feaf9334301577290e2e",
          "sha1": "d3b87711df250e820dc521ed42c132ed390e630c",
          "md5": "3fbf3a07e57eb062f8dbccf5da4cd97c"
        }
      ]
    }
  ]
}
