{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectorAPI",
    "version": "0.1.7.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.7.0-SNAPSHOT.jar",
          "url": "ConnectorAPI-0.1.7.0-SNAPSHOT.jar",
          "size": 30321,
          "sha512": "12823822eeaa753c8d55f36eeedd951805c20a1795c25f66f2e7673b31ea16fa58c9e43cfac2296135f4f8ff84b313b8b59eea0dc3e0f1917a8f25405a8350dd",
          "sha256": "56d7436ce9caf4aa02354abbf9e4b4f4f1e5b3699790063202d2f485af5bd105",
          "sha1": "f9ddc96d87d8a8f3b9fd537c1c22d3abcf8046e2",
          "md5": "38b336d81442e5c400fd7cf7e3cf109d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "ConnectorAPI-0.1.7.0-SNAPSHOT.jar",
          "url": "ConnectorAPI-0.1.7.0-SNAPSHOT.jar",
          "size": 30321,
          "sha512": "12823822eeaa753c8d55f36eeedd951805c20a1795c25f66f2e7673b31ea16fa58c9e43cfac2296135f4f8ff84b313b8b59eea0dc3e0f1917a8f25405a8350dd",
          "sha256": "56d7436ce9caf4aa02354abbf9e4b4f4f1e5b3699790063202d2f485af5bd105",
          "sha1": "f9ddc96d87d8a8f3b9fd537c1c22d3abcf8046e2",
          "md5": "38b336d81442e5c400fd7cf7e3cf109d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.7.0-SNAPSHOT-sources.jar",
          "url": "ConnectorAPI-0.1.7.0-SNAPSHOT-sources.jar",
          "size": 16543,
          "sha512": "665aa2995fb4c1f73b40cf4d7d4890e37dac8a55d5d9332d74a04bf233590472a92a62414b0fd2c2e47ab6d4d4a9f12a2df2891af1419eb136bc316f36732061",
          "sha256": "caff3ca260e31ae345668721d969594749adc7756016d9f984e5071baee00b9c",
          "sha1": "e5817bc92c6534c5bf77d9358ac646ec6f527e5f",
          "md5": "c75771cc11ca43143a3a5b83a26863be"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.7.0-SNAPSHOT-javadoc.jar",
          "url": "ConnectorAPI-0.1.7.0-SNAPSHOT-javadoc.jar",
          "size": 154124,
          "sha512": "14e1308159661e48966e4d51270357fba7237fb3cf2f1ae43a2afeacf80cef3f5914ec28e6cfebda16ad3bf047053772a5e1f5ff585541e880ffda80950c90bd",
          "sha256": "78583caaafc234006baf345751af6413ef6a3b1f0d32b895465d46a72bb17430",
          "sha1": "2dfe2156a13e15deef18faff13c993aa2aef0d22",
          "md5": "78efd7314d5f73cbba947ad7ec31bb12"
        }
      ]
    }
  ]
}
