{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectorAPI",
    "version": "0.1.3.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.6-SNAPSHOT.jar",
          "url": "ConnectorAPI-0.1.3.6-SNAPSHOT.jar",
          "size": 26040,
          "sha512": "9ee57e97f22868afa4952b6796d7bbf3d053bd21d5c34b597c908f5e722a47e3b3ba4978881efdf943b7612bca803111f4dabe666b33d16a992430fb6583a34f",
          "sha256": "199e7983d1a43e8179cf16b86f4e3d70b400e24bfa2cf28f5485451f76bb56f7",
          "sha1": "e28d722afe2e985679c76daacfc983507cd96142",
          "md5": "111b56e29f96e91d769e5e961588145e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-base",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-base",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-graphics",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-graphics",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-controls",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-controls",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-fxml",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-fxml",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.6-SNAPSHOT.jar",
          "url": "ConnectorAPI-0.1.3.6-SNAPSHOT.jar",
          "size": 26040,
          "sha512": "9ee57e97f22868afa4952b6796d7bbf3d053bd21d5c34b597c908f5e722a47e3b3ba4978881efdf943b7612bca803111f4dabe666b33d16a992430fb6583a34f",
          "sha256": "199e7983d1a43e8179cf16b86f4e3d70b400e24bfa2cf28f5485451f76bb56f7",
          "sha1": "e28d722afe2e985679c76daacfc983507cd96142",
          "md5": "111b56e29f96e91d769e5e961588145e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.6-SNAPSHOT-sources.jar",
          "url": "ConnectorAPI-0.1.3.6-SNAPSHOT-sources.jar",
          "size": 15045,
          "sha512": "c1a2b9d8e757f4e44fc44dbeb2099edde9d98dcc9b76f77ffc4ee7430911e9bd71da1e9cb3748dfc055a44c2d601f6e62f4a430b6af8714a149b5557c5bf570a",
          "sha256": "883f3c423d6b57a2efa0468b8c54ec9f56eecf4d5a6c8c16c0bade83346ab916",
          "sha1": "e9ce23d42cca87ed72b084ad081fc23d4d271ea4",
          "md5": "9d2eef0595666e2355d73d0892029282"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.6-SNAPSHOT-javadoc.jar",
          "url": "ConnectorAPI-0.1.3.6-SNAPSHOT-javadoc.jar",
          "size": 145904,
          "sha512": "ef4fbb3679a65672ff039c51bad24ddc14b692d6200ac8b9abcf1d94092abdea527b5afde128be54743f3a6a2c76dc00e4bae1043194e2be2ec69162e827b031",
          "sha256": "859a73c9c2145db7fe1805f7b027e8fc98cab2fed300e783be755db12047e1db",
          "sha1": "8e43bcd9c08d018e7f0c022976e27abe603f4b6f",
          "md5": "e0c3a85b4107fe7ed9bc3f3cbd3c6734"
        }
      ]
    }
  ]
}
