{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectorAPI",
    "version": "0.1.3.13-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.13-SNAPSHOT.jar",
          "url": "ConnectorAPI-0.1.3.13-SNAPSHOT.jar",
          "size": 29615,
          "sha512": "16fbee18799bcda7e4d55dd3b7e174b4fbc106d21efae888e41474c71d9b59cf76ea81b959cf1c13e12b3e5aa6ab86177019e1c498ae6a5f170745c64445bac3",
          "sha256": "5dca8b707fd6649c51a0eb24e40919eec5be018e219a617fa9be18a9680bfcff",
          "sha1": "ba399e2af8d7a6b9c4c2151625148655617af622",
          "md5": "687aae1366b893129e8c66f92536e0e8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-base",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-base",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-graphics",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-graphics",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-controls",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-controls",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-fxml",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-fxml",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.13-SNAPSHOT.jar",
          "url": "ConnectorAPI-0.1.3.13-SNAPSHOT.jar",
          "size": 29615,
          "sha512": "16fbee18799bcda7e4d55dd3b7e174b4fbc106d21efae888e41474c71d9b59cf76ea81b959cf1c13e12b3e5aa6ab86177019e1c498ae6a5f170745c64445bac3",
          "sha256": "5dca8b707fd6649c51a0eb24e40919eec5be018e219a617fa9be18a9680bfcff",
          "sha1": "ba399e2af8d7a6b9c4c2151625148655617af622",
          "md5": "687aae1366b893129e8c66f92536e0e8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.13-SNAPSHOT-sources.jar",
          "url": "ConnectorAPI-0.1.3.13-SNAPSHOT-sources.jar",
          "size": 17260,
          "sha512": "e2080c230dd6cbd0886099cedd3dd5835f804a203434fe499bf5bb5587354b67c49075d468194fa2b117020e2044ce08703af808af2460c6a374b3dd8b225c2f",
          "sha256": "3bdd72c39b4f7561c47636d424e1596b872e9d82db474966bff8181d5dc2dea6",
          "sha1": "907011aa55c6814d9e7fb2707d209bf452130028",
          "md5": "fe25b886f2f7e44ec9d80b453bd4db10"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.13-SNAPSHOT-javadoc.jar",
          "url": "ConnectorAPI-0.1.3.13-SNAPSHOT-javadoc.jar",
          "size": 152527,
          "sha512": "eb7ad2e4479811bdedf79fed03a9ece8b2b768b4d470a6c621f2170395a0d7ab421298942d70e31a0b060e71a01f68c14a7e53044f045ff8997e424d886bd838",
          "sha256": "30bb939cdf189d2376bb4aa4a8627641dd1fd414e54882115bb3b75b682e5043",
          "sha1": "5f5f0f0268e139ebe58f58c42427e10861231d4b",
          "md5": "c689bdaae1d9a87bceedddc1acc0707b"
        }
      ]
    }
  ]
}
