{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectLib",
    "version": "0.3.5-STABLE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectLib-0.3.5-STABLE.jar",
          "url": "ConnectLib-0.3.5-STABLE.jar",
          "size": 49745,
          "sha512": "d7b6dcf63e91af9ba796c1bc4d78d2eae742d0c547525692e6f34f2a6359793f62e0d27b1d48b1ac9dfee54d657e7fc38719f68f4e55e541aec2c5f29965d274",
          "sha256": "e7e115c0a8a2ddea11547e6e3aa8d6edd985b9bcca67ab9240f4dd83d6a94a24",
          "sha1": "fe9875875f15cb6f8058daa73e8b096b05dc0a0e",
          "md5": "9cf5c50fff28adcd7649a7acc5b9b1d3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "ConnectLib-0.3.5-STABLE.jar",
          "url": "ConnectLib-0.3.5-STABLE.jar",
          "size": 49745,
          "sha512": "d7b6dcf63e91af9ba796c1bc4d78d2eae742d0c547525692e6f34f2a6359793f62e0d27b1d48b1ac9dfee54d657e7fc38719f68f4e55e541aec2c5f29965d274",
          "sha256": "e7e115c0a8a2ddea11547e6e3aa8d6edd985b9bcca67ab9240f4dd83d6a94a24",
          "sha1": "fe9875875f15cb6f8058daa73e8b096b05dc0a0e",
          "md5": "9cf5c50fff28adcd7649a7acc5b9b1d3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectLib-0.3.5-STABLE-sources.jar",
          "url": "ConnectLib-0.3.5-STABLE-sources.jar",
          "size": 26912,
          "sha512": "0e3c02f52f9053a838e0c9f47d0fbbb620e67abe7d7c75109940b1d1097311b921d853637641a662063a1a7edc273597e9d3cecf79ae0853da2001a23db52a2a",
          "sha256": "94ce7cb0746ff2c48cb6925996e09016d54ceaeb2c8a113ecec1d1c1427e2836",
          "sha1": "7dff5f93df6279b4c47fbd944e1ea90c2cb4a0d7",
          "md5": "3241e794405492389731e88e56ab3896"
        }
      ]
    }
  ]
}
