{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectLib",
    "version": "0.3.5-STABLE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectLib-0.3.5-STABLE.jar",
          "url": "ConnectLib-0.3.5-STABLE.jar",
          "size": 49745,
          "sha512": "859e70c7028d84a20a63c75812e78f3d6a4913978e8101dfddf2c98b16e415f34e18f62264136a09b236d0d7d043f09955b5dd1e0114488e106b511db7cf0cb4",
          "sha256": "0966ecefaba08d441e47a7f480891ecdb9a24769aead0ec110295ce901826d1a",
          "sha1": "10d8498adb8241c3fc7c1fdcafc29931338c19d8",
          "md5": "ec5a5ab902c06ff64743d02f2719bd3e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "ConnectLib-0.3.5-STABLE.jar",
          "url": "ConnectLib-0.3.5-STABLE.jar",
          "size": 49745,
          "sha512": "859e70c7028d84a20a63c75812e78f3d6a4913978e8101dfddf2c98b16e415f34e18f62264136a09b236d0d7d043f09955b5dd1e0114488e106b511db7cf0cb4",
          "sha256": "0966ecefaba08d441e47a7f480891ecdb9a24769aead0ec110295ce901826d1a",
          "sha1": "10d8498adb8241c3fc7c1fdcafc29931338c19d8",
          "md5": "ec5a5ab902c06ff64743d02f2719bd3e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectLib-0.3.5-STABLE-sources.jar",
          "url": "ConnectLib-0.3.5-STABLE-sources.jar",
          "size": 26915,
          "sha512": "778f0de89d98557260ea2f509286c20604fea1125e5a443949a480aea0bbd801f19cf5736da2b833dc0a8ec433e117c892fb6a41eee86b675fdf884fdf0c0bd6",
          "sha256": "008fbdb587f4380131dfee8dd9ad71c3eff422f2a0d4d78810cd98bd713101f9",
          "sha1": "2ba33e1367a3547d26ea2d7643a37d3321275c59",
          "md5": "7eac43443722f56179eafc50e9195abf"
        }
      ]
    }
  ]
}
