{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectLib",
    "version": "0.3.5-STABLE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectLib-0.3.5-STABLE.jar",
          "url": "ConnectLib-0.3.5-STABLE.jar",
          "size": 49745,
          "sha512": "d6205319dd8627109e63d56220105725589b4f4c7de48c75710ebfd60d95ac047a7dedb1b48a2ebceb6133f2eb3a69bc277bc5eb803587c99221712bf7cbabe2",
          "sha256": "4e38ea18dfaf1c735b94ff7472886106c9c091734f912f23d47a055f1cf0937a",
          "sha1": "25e75894e14806b32f6baa845ab10755f8c00f27",
          "md5": "f652ac56a300b8829566da824b6e120c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "ConnectLib-0.3.5-STABLE.jar",
          "url": "ConnectLib-0.3.5-STABLE.jar",
          "size": 49745,
          "sha512": "d6205319dd8627109e63d56220105725589b4f4c7de48c75710ebfd60d95ac047a7dedb1b48a2ebceb6133f2eb3a69bc277bc5eb803587c99221712bf7cbabe2",
          "sha256": "4e38ea18dfaf1c735b94ff7472886106c9c091734f912f23d47a055f1cf0937a",
          "sha1": "25e75894e14806b32f6baa845ab10755f8c00f27",
          "md5": "f652ac56a300b8829566da824b6e120c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectLib-0.3.5-STABLE-sources.jar",
          "url": "ConnectLib-0.3.5-STABLE-sources.jar",
          "size": 26915,
          "sha512": "6d10907b0c2e391c7ceeaa95a19d17bce2d739cd3a5c683149a5132c98a89baab68bcb5d5dd68c84091add07448c03566b57670f3164e9b62cb552dc655f0e2e",
          "sha256": "77ec50f7beba3e2fc2934aca39f21ec0209420ba3acf92ed46e7793aba6994ee",
          "sha1": "6fedeaf650ef9191aecd127b2e131ee48ecfff42",
          "md5": "954b0ba8943d2dec349168478e9eafa5"
        }
      ]
    }
  ]
}
