{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectLib",
    "version": "0.2.5-STABLE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectLib-0.2.5-STABLE.jar",
          "url": "ConnectLib-0.2.5-STABLE.jar",
          "size": 26010,
          "sha512": "589f14f60a735963e7ed929dfca46edb6f88e1d76b5d9c669bb7eacaa556aaff787565df65ccdf482d6cc451da8d56d163924ee7c2d883acbec52c2f5142c2c7",
          "sha256": "3d58522bc30236d36d27956ae00caa411763dd333d68e0f1d3bcdf40e7bb0694",
          "sha1": "53c7c3b55454c5fcd3045fb4828eca6a3c0b9705",
          "md5": "a901eca42dd7c99e3d1f53e245ec2fa0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "ConnectLib-0.2.5-STABLE.jar",
          "url": "ConnectLib-0.2.5-STABLE.jar",
          "size": 26010,
          "sha512": "589f14f60a735963e7ed929dfca46edb6f88e1d76b5d9c669bb7eacaa556aaff787565df65ccdf482d6cc451da8d56d163924ee7c2d883acbec52c2f5142c2c7",
          "sha256": "3d58522bc30236d36d27956ae00caa411763dd333d68e0f1d3bcdf40e7bb0694",
          "sha1": "53c7c3b55454c5fcd3045fb4828eca6a3c0b9705",
          "md5": "a901eca42dd7c99e3d1f53e245ec2fa0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectLib-0.2.5-STABLE-sources.jar",
          "url": "ConnectLib-0.2.5-STABLE-sources.jar",
          "size": 15744,
          "sha512": "e486a9aee2a625ce20a99cbd9297d9bb81e9253429046c73a144b4373e7c2bdf45af1e3e656c071c756ed17b681d4e2d3b74f262181f3c96d847f6405fd29dad",
          "sha256": "be8b9d2200051367d93ddd1215e475794ba06e0b701483772423c425e99fce67",
          "sha1": "883c9ff54d996806f8a5442e40275c5cb1c31839",
          "md5": "1ebbe9b0b34e53aafb0016110769c6a4"
        }
      ]
    }
  ]
}
