{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectLib",
    "version": "0.2.5-STABLE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectLib-0.2.5-STABLE.jar",
          "url": "ConnectLib-0.2.5-STABLE.jar",
          "size": 26010,
          "sha512": "ef1644a34a21c426a47b64506512cd86d3c0e258ed4e1e86b3d240dd9fd193ffdf1564628803b2fb1e84db41e782e3b5808b4f1dec443f7fbdd14d1d5ab8bc44",
          "sha256": "bd673a5db7f2212387e6fa957c6d568f1152dd33915b4c05ed2ebfefbb872e8d",
          "sha1": "6cc8ecf9afad188c8c7b3d2b4e7997bb7ca7750a",
          "md5": "c8773a224964eef1f60b523508c1fa2f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "ConnectLib-0.2.5-STABLE.jar",
          "url": "ConnectLib-0.2.5-STABLE.jar",
          "size": 26010,
          "sha512": "ef1644a34a21c426a47b64506512cd86d3c0e258ed4e1e86b3d240dd9fd193ffdf1564628803b2fb1e84db41e782e3b5808b4f1dec443f7fbdd14d1d5ab8bc44",
          "sha256": "bd673a5db7f2212387e6fa957c6d568f1152dd33915b4c05ed2ebfefbb872e8d",
          "sha1": "6cc8ecf9afad188c8c7b3d2b4e7997bb7ca7750a",
          "md5": "c8773a224964eef1f60b523508c1fa2f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectLib-0.2.5-STABLE-sources.jar",
          "url": "ConnectLib-0.2.5-STABLE-sources.jar",
          "size": 15744,
          "sha512": "6b2ebdc9ea223c21382dbf4fc17bb555be71cd13eb8471546aa2f9657c0825c75bcd460d00f3e4a1584e901b5a6c1097ca2e9156446de09bf8a72189a4fe1d6c",
          "sha256": "6454da39075523c4a86945d061f9287494d0d73646c16a05c0fcf51b7b733950",
          "sha1": "82fa9807027f9ea5d95b3f845609cd5fa11e4456",
          "md5": "a8929b4fd865d19dc183a377814d57f7"
        }
      ]
    }
  ]
}
