{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectorAPI",
    "version": "0.1.3.4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.4-SNAPSHOT.jar",
          "url": "ConnectorAPI-0.1.3.4-SNAPSHOT.jar",
          "size": 25808,
          "sha512": "44c32156562329f716ca838c0624910b252b24891de785ed91e9cfa7d294ba604f41d0310b743583954f26b864f52b1a493ae9e66fbfa23acbe30abfdef0e700",
          "sha256": "52608d9d7a305f34a72ac91e2a598768e9e4a593a67e5dc7571007674a4980e3",
          "sha1": "774c4adcbca90c7aafba5f34d750f54a56826975",
          "md5": "cba453fe38d330bd0d730a6456942dcf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-base",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-base",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-graphics",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-graphics",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-controls",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-controls",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-fxml",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-fxml",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.4-SNAPSHOT.jar",
          "url": "ConnectorAPI-0.1.3.4-SNAPSHOT.jar",
          "size": 25808,
          "sha512": "44c32156562329f716ca838c0624910b252b24891de785ed91e9cfa7d294ba604f41d0310b743583954f26b864f52b1a493ae9e66fbfa23acbe30abfdef0e700",
          "sha256": "52608d9d7a305f34a72ac91e2a598768e9e4a593a67e5dc7571007674a4980e3",
          "sha1": "774c4adcbca90c7aafba5f34d750f54a56826975",
          "md5": "cba453fe38d330bd0d730a6456942dcf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.4-SNAPSHOT-sources.jar",
          "url": "ConnectorAPI-0.1.3.4-SNAPSHOT-sources.jar",
          "size": 14930,
          "sha512": "996f8c36821e5d07c4e928a5129a3ceb0a45c72bd2c13b22d14a4eee29696a041882d65011f2c7eca731889cbd56f30b0de5eab5ddd70f25c126867d0957af2a",
          "sha256": "9f4ed80a0bea320da322354b89b5b99622816dbb82bc1910cdd07d9bf57db394",
          "sha1": "6f448203cdc4477253cf998c7b5631d645ccb98c",
          "md5": "9afe2c5e31e082c094369c188a9e17d1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.4-SNAPSHOT-javadoc.jar",
          "url": "ConnectorAPI-0.1.3.4-SNAPSHOT-javadoc.jar",
          "size": 145904,
          "sha512": "9e244f6608758e161015ab03b05b4abc9bf666a1406f9989381e683e84f0cb2446f8afb2a28c7cd3f16c8f21357e9ca2124747d22546338677da2a8b9ac10608",
          "sha256": "012e814426af2e21a11d78a912ccd25297b32efc73f0642053fb8d1e4671c9f7",
          "sha1": "6f2600d16f994989f353fcf9457b83087a509be6",
          "md5": "4708b3694f952e32357cca43981c79a5"
        }
      ]
    }
  ]
}
