{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectorAPI",
    "version": "0.1.3.11-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.11-SNAPSHOT.jar",
          "url": "ConnectorAPI-0.1.3.11-SNAPSHOT.jar",
          "size": 29272,
          "sha512": "11b72447664a51cf3ae6357702c1ba7e05cf6650a515dd5674fc7dca233fa36c3f832043eead623d84efb36eb2805f91c250d774a7a4df5ea082aa0aa83a9aa9",
          "sha256": "45e009c2ea27243cbe9fcbb26ec410ec4e3ab153a8c1d53d253455f499bbdc90",
          "sha1": "00ccc28dd6f534bf94bd24f31f560cdf9b19e7cf",
          "md5": "1e037fa4fc7c27c5839d71a468d4511a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-base",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-base",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-graphics",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-graphics",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-controls",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-controls",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-fxml",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-fxml",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.11-SNAPSHOT.jar",
          "url": "ConnectorAPI-0.1.3.11-SNAPSHOT.jar",
          "size": 29272,
          "sha512": "11b72447664a51cf3ae6357702c1ba7e05cf6650a515dd5674fc7dca233fa36c3f832043eead623d84efb36eb2805f91c250d774a7a4df5ea082aa0aa83a9aa9",
          "sha256": "45e009c2ea27243cbe9fcbb26ec410ec4e3ab153a8c1d53d253455f499bbdc90",
          "sha1": "00ccc28dd6f534bf94bd24f31f560cdf9b19e7cf",
          "md5": "1e037fa4fc7c27c5839d71a468d4511a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.11-SNAPSHOT-sources.jar",
          "url": "ConnectorAPI-0.1.3.11-SNAPSHOT-sources.jar",
          "size": 17203,
          "sha512": "4b824027161eb458b7672768e1efd957bf7c7992653a807b35da46ac27d55398f397662f372d5f1c36f35475e63e846e26574dc539ed2c31133b60dcad94db00",
          "sha256": "0a962233cbdb2af3f63778b9912d61f1103b9960305de38d467557da3143091d",
          "sha1": "b7a1344cf9748821b5e1e2fd4c5190abfd18e777",
          "md5": "31e1986e5c9d7d0a088b7aebbcbbee12"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.11-SNAPSHOT-javadoc.jar",
          "url": "ConnectorAPI-0.1.3.11-SNAPSHOT-javadoc.jar",
          "size": 152426,
          "sha512": "5157de7ae9a68ef55da36141acdccc5eacd3e29b0c384acaab7a35f87ff29bd85bf83d8b4ba9ec2d73fd48c5fe0a46e29f949506df504943af8835c4ab92ad74",
          "sha256": "681f64938f9da7320d34023febaf6d178fdd9d8445caf3bf95f37afb854ab00b",
          "sha1": "f54f9f6ddaf9e4d82c55eb0f3693f0cc3c541ed6",
          "md5": "73b443e235ca2d4efabeafc9a2562f5b"
        }
      ]
    }
  ]
}
