{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectorAPI",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.2.jar",
          "url": "ConnectorAPI-0.1.2.jar",
          "size": 24201,
          "sha512": "93e966435c0def0ec5ba90657d77a47608341074057eeedab126b99095633b9275a4e0daaaf5bd0d23754199ba414e00b676189d27ea77a648761c3eb2b4ff37",
          "sha256": "333ec7d4b2f12849a76356b56e9c713c6b8d246fd534e1a8821475bb1f3cb26c",
          "sha1": "b3c0268253f9204effcac5fbdc8abcff7a753719",
          "md5": "5b28e734b37e436ee2bd0287befa36b9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-base",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-base",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-graphics",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-graphics",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-controls",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-controls",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-fxml",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-fxml",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "ConnectorAPI-0.1.2.jar",
          "url": "ConnectorAPI-0.1.2.jar",
          "size": 24201,
          "sha512": "93e966435c0def0ec5ba90657d77a47608341074057eeedab126b99095633b9275a4e0daaaf5bd0d23754199ba414e00b676189d27ea77a648761c3eb2b4ff37",
          "sha256": "333ec7d4b2f12849a76356b56e9c713c6b8d246fd534e1a8821475bb1f3cb26c",
          "sha1": "b3c0268253f9204effcac5fbdc8abcff7a753719",
          "md5": "5b28e734b37e436ee2bd0287befa36b9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.2-sources.jar",
          "url": "ConnectorAPI-0.1.2-sources.jar",
          "size": 13332,
          "sha512": "5e46e166cccd053bc6b6ae5e56f6ae364749ed4c0f6679ba2bd97f5dd2663d75ec7a6e614582a28ea8cee0493ea7502f0736e223a42e9b8f1f30a030ad6613c7",
          "sha256": "2852e85489fa1a31405d12b25736918a0ea58f969856a57608efbaffc2582b72",
          "sha1": "a694f278da9d0b3696dd3d4a60b6c974cc18f7b0",
          "md5": "7a55b49c32e0b9aeacb4ff8a6d137061"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.2-javadoc.jar",
          "url": "ConnectorAPI-0.1.2-javadoc.jar",
          "size": 138765,
          "sha512": "88a7fd726b62295006e1f00ce183f29e00fac212dd2dc740ec258cdb958986df2801c1ad212f94fe28d3b613519c220907f5daa9427df0b5029e7181c199728a",
          "sha256": "3f3698d72c7efe81dbe9ef64543d705fa3fc32b962c850c583cff7d57f65db28",
          "sha1": "e6db649855505ce432c0fe6d574ed98532f8b385",
          "md5": "ae76292f6a008efff76cfd28010db735"
        }
      ]
    }
  ]
}
