{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectorAPI",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.2.jar",
          "url": "ConnectorAPI-0.1.2.jar",
          "size": 23882,
          "sha512": "dd4cbf8df1a5ee66b76c4b60e0eb6bde101c3dc99cd3662eca5e50f538f13a22cf013d497b7afb10b1f8a6a4e02ffbee94a0a833b1ab5a3611c65822153a3419",
          "sha256": "2e50602cb63c6109b0e678df417afa7821705ca7a2069109aa3972d498493b6e",
          "sha1": "b5a2c371ba3d52a854d921f30365ab2afaea58e3",
          "md5": "c1e6a97ea383dd338f2ae063273f5c12"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-base",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-base",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-graphics",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-graphics",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-controls",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-controls",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-fxml",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-fxml",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "ConnectorAPI-0.1.2.jar",
          "url": "ConnectorAPI-0.1.2.jar",
          "size": 23882,
          "sha512": "dd4cbf8df1a5ee66b76c4b60e0eb6bde101c3dc99cd3662eca5e50f538f13a22cf013d497b7afb10b1f8a6a4e02ffbee94a0a833b1ab5a3611c65822153a3419",
          "sha256": "2e50602cb63c6109b0e678df417afa7821705ca7a2069109aa3972d498493b6e",
          "sha1": "b5a2c371ba3d52a854d921f30365ab2afaea58e3",
          "md5": "c1e6a97ea383dd338f2ae063273f5c12"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.2-sources.jar",
          "url": "ConnectorAPI-0.1.2-sources.jar",
          "size": 12890,
          "sha512": "f64ebfc908ad553660443afe3e16b1e4e747ed22de28958cada78141a024f701b442b5356690e17bcb4c1a0f5a85601615d334e54f642a2fe55894765c5e254e",
          "sha256": "aa14eadacbc750e1c88e8cec595fbe0a9d8ed4b01fa553b32c58eba96023e990",
          "sha1": "c6f2fb5e40043c3145356af7cbd2eeadd0e3b7d5",
          "md5": "5768a4f3a2dbf38aae08a7d666a75839"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.2-javadoc.jar",
          "url": "ConnectorAPI-0.1.2-javadoc.jar",
          "size": 135836,
          "sha512": "e10e1f4489c19205a59868fc56d241a43755d40a24a82fc0d9d95815845cdd97559f0932147d7da1a475abc0b3606e9144682ae69a52c03c658b6028ffa90d29",
          "sha256": "44c96155ea293fe3a43a34fcda5e5bf7418fd179bc0514c2beb76a8a2b016740",
          "sha1": "1c038aac71b14e05731434a78445c8cd98c7d7a4",
          "md5": "cd81cc147e00ebf7cbae0800d08057ad"
        }
      ]
    }
  ]
}
