{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectorAPI",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.2.jar",
          "url": "ConnectorAPI-0.1.2.jar",
          "size": 24201,
          "sha512": "46039544f42a70d299a1450e3d249b8da0e9b218159b8fc72d4d6d4783621e3e8cfe32e5858c035b88f40763d57e7ba8d917707b4430303842e4fc0087f51fe9",
          "sha256": "c8aeab4de5abcafa31bd8a8ea502c4b92207b81cc908f7a5c26799e13f2c4fca",
          "sha1": "1dacef6b7d0c3cb984841ca2f6744dea5385c486",
          "md5": "4fe01791b8e554476752a1dfcd6b5eb5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-base",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-base",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-graphics",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-graphics",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-controls",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-controls",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-fxml",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-fxml",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "ConnectorAPI-0.1.2.jar",
          "url": "ConnectorAPI-0.1.2.jar",
          "size": 24201,
          "sha512": "46039544f42a70d299a1450e3d249b8da0e9b218159b8fc72d4d6d4783621e3e8cfe32e5858c035b88f40763d57e7ba8d917707b4430303842e4fc0087f51fe9",
          "sha256": "c8aeab4de5abcafa31bd8a8ea502c4b92207b81cc908f7a5c26799e13f2c4fca",
          "sha1": "1dacef6b7d0c3cb984841ca2f6744dea5385c486",
          "md5": "4fe01791b8e554476752a1dfcd6b5eb5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.2-sources.jar",
          "url": "ConnectorAPI-0.1.2-sources.jar",
          "size": 13332,
          "sha512": "431b194259c8698846e06b4d3ef88fb773f71b7e9e1dee6e86a05ef02dcaeb2a4f446c428dd45d4256ffc3a8cb89f266aa37f4d453da48cf24b54d2268b48da1",
          "sha256": "39a70917262dc111201efe7c2422c4615fa2a5a72889a41758935e972bbc26bf",
          "sha1": "b4a813e6ab538a66975b7835f464a5bd30634c5d",
          "md5": "c776440421648541a9db77a710a9fcb3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.2-javadoc.jar",
          "url": "ConnectorAPI-0.1.2-javadoc.jar",
          "size": 138765,
          "sha512": "d4aaf9994fee9bd97d5405a91d9498958a0b4eec8d7906a8aa8de1f12dcc4b344854fc4f378a4adfdbcd1fdddb9744aaaf960ccec6e8b14359839aba94b8439f",
          "sha256": "57c9614afda146466575312c19a1576a50821dffbb77302f75b9e71efa604ef4",
          "sha1": "a5a0584799bbabca3a9163a6a49f7183485a6e01",
          "md5": "1c9fd5db4bea80ef55326b56877f4ad0"
        }
      ]
    }
  ]
}
