{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectorAPI",
    "version": "0.1.3.9-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.9-SNAPSHOT.jar",
          "url": "ConnectorAPI-0.1.3.9-SNAPSHOT.jar",
          "size": 27764,
          "sha512": "def484d3a10af029f15133747eeeab1d882eaedb67a73e1d4e7010b876807171a4fdbb106df5a59e808f5f75e15e11c49a7a3495e0bf337b1b22f94889687cae",
          "sha256": "7227af46ce0de839b92a3bcda6d588c17c24d96dcf55e0d4018d8a0d3b397833",
          "sha1": "af0cf7852b73dd7c35e20e386a4d3edb9b619300",
          "md5": "2be9fd3ff290817e5a4b0cb76abb7921"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-base",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-base",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-graphics",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-graphics",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-controls",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-controls",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-fxml",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-fxml",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.9-SNAPSHOT.jar",
          "url": "ConnectorAPI-0.1.3.9-SNAPSHOT.jar",
          "size": 27764,
          "sha512": "def484d3a10af029f15133747eeeab1d882eaedb67a73e1d4e7010b876807171a4fdbb106df5a59e808f5f75e15e11c49a7a3495e0bf337b1b22f94889687cae",
          "sha256": "7227af46ce0de839b92a3bcda6d588c17c24d96dcf55e0d4018d8a0d3b397833",
          "sha1": "af0cf7852b73dd7c35e20e386a4d3edb9b619300",
          "md5": "2be9fd3ff290817e5a4b0cb76abb7921"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.9-SNAPSHOT-sources.jar",
          "url": "ConnectorAPI-0.1.3.9-SNAPSHOT-sources.jar",
          "size": 16227,
          "sha512": "017abb3402de411bca362ced52bcc7781bcf1cfa08660d22fb07a7c55c97b5821a2fb091d4f98c734fe0adeedbdb0f30aabfe11c340fc359e2aeb7427b264e3c",
          "sha256": "d8571f490c57bf470e052626cf00c5f0387a6f4cf3078989971cb96f0e59064f",
          "sha1": "156e5655828a773695bcf757367cb6d1c18798bd",
          "md5": "d9732607434c0843fc13cb06cc571569"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.9-SNAPSHOT-javadoc.jar",
          "url": "ConnectorAPI-0.1.3.9-SNAPSHOT-javadoc.jar",
          "size": 149044,
          "sha512": "75583438e44446c9add356e24c1107747a46a9cc0a8bb3c455d10b7223f6291263b481b5021019be7f34c4556ee978ac43602c4b6518c739973fa67ee80405f6",
          "sha256": "fb4b08f024d78d1e3a921a71b6d154282e90621cd3f524944c1e36387bb20cdc",
          "sha1": "7f50360fac3da465fcd0c658813a400943346994",
          "md5": "5e77fc8c6781269c3c9480a9b8d7e767"
        }
      ]
    }
  ]
}
