{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectorAPI",
    "version": "0.1.3.9-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.9-SNAPSHOT.jar",
          "url": "ConnectorAPI-0.1.3.9-SNAPSHOT.jar",
          "size": 29314,
          "sha512": "4e7c7bd5062d2276334913f3b3c8fe1e5aba523f0d49004ae003117b296adb09c1c5bf43728dcb8827b2eed1bf997e3255b130ca74aa84ab409119900f80dd5e",
          "sha256": "893bfd907dfe59b3023e000d9e42aac9e43aaffa5216d715d7ca2dc491643124",
          "sha1": "0d02a8aae850c48ad90c9bf60d55e8e7341b54cb",
          "md5": "06dad399f248306d3351bb6602775cab"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-base",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-base",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-graphics",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-graphics",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-controls",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-controls",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-fxml",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-fxml",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.9-SNAPSHOT.jar",
          "url": "ConnectorAPI-0.1.3.9-SNAPSHOT.jar",
          "size": 29314,
          "sha512": "4e7c7bd5062d2276334913f3b3c8fe1e5aba523f0d49004ae003117b296adb09c1c5bf43728dcb8827b2eed1bf997e3255b130ca74aa84ab409119900f80dd5e",
          "sha256": "893bfd907dfe59b3023e000d9e42aac9e43aaffa5216d715d7ca2dc491643124",
          "sha1": "0d02a8aae850c48ad90c9bf60d55e8e7341b54cb",
          "md5": "06dad399f248306d3351bb6602775cab"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.9-SNAPSHOT-sources.jar",
          "url": "ConnectorAPI-0.1.3.9-SNAPSHOT-sources.jar",
          "size": 17202,
          "sha512": "c3f22c8736a10617aa29af66730e5c8acb9a249d0af9e36861a31305ba9317d2d99c5f5d8c82ea2635cc936d1e6bfac8df289b09f8db7ae24ded9809f1e45166",
          "sha256": "71873abd23318be9d170eef34f27b7b6e680c856f105f685d56bee233d593962",
          "sha1": "f353d3856bb7488baebe15bd5789b8f08bae4076",
          "md5": "0d4cb7ff521576dbdba1d8dfd85a31ce"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.9-SNAPSHOT-javadoc.jar",
          "url": "ConnectorAPI-0.1.3.9-SNAPSHOT-javadoc.jar",
          "size": 152410,
          "sha512": "1fb7a87eb580849b48d04cd7a2843a1afb9331a6057ff08f9f59449653553ff726d31f036da7c2fa5f1661145f1ec9bc11d44a8b7ce9a7492c1ed22f930a68f8",
          "sha256": "e04b1f0802ba9bd87b73737d883899a99f6e9b40d85442068122efd17c83c950",
          "sha1": "d3d2c723fd34d8f20a8b27e59743bee996ad2124",
          "md5": "7504da09ed574e23475de4ce88077293"
        }
      ]
    }
  ]
}
