{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectLib",
    "version": "0.2.3-STABLE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectLib-0.2.3-STABLE.jar",
          "url": "ConnectLib-0.2.3-STABLE.jar",
          "size": 25988,
          "sha512": "bb84496704697d1a5b27788121d2cbf7c3172e98ffeb00f5f2ae0bebbd43f6656fdbf8b50c8087bef7d6ab6ffd78b16babde11bb4cc1268611fe520ce6b9d59a",
          "sha256": "f71962fa58f883a7fbecb9883defde1fd25a5b823f591a75b47388a4d0dfe4e1",
          "sha1": "7036c306f1a428d8405e7b2b4f3ab219c13529ef",
          "md5": "6fb4e8d81ea620c3cb5883f6eda27198"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "ConnectLib-0.2.3-STABLE.jar",
          "url": "ConnectLib-0.2.3-STABLE.jar",
          "size": 25988,
          "sha512": "bb84496704697d1a5b27788121d2cbf7c3172e98ffeb00f5f2ae0bebbd43f6656fdbf8b50c8087bef7d6ab6ffd78b16babde11bb4cc1268611fe520ce6b9d59a",
          "sha256": "f71962fa58f883a7fbecb9883defde1fd25a5b823f591a75b47388a4d0dfe4e1",
          "sha1": "7036c306f1a428d8405e7b2b4f3ab219c13529ef",
          "md5": "6fb4e8d81ea620c3cb5883f6eda27198"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectLib-0.2.3-STABLE-sources.jar",
          "url": "ConnectLib-0.2.3-STABLE-sources.jar",
          "size": 15730,
          "sha512": "20d47c3baa57485043f43a31d9f1f349e9ccf5185ce95fed2527bd25ba118b7c3ddcafd867b685ec83b46582025a17863150d95045e2bcd902cdb1fe436f84f4",
          "sha256": "a2325da489f21abf7af253f10bd125aff0ca2cc17d879749076eaf026c37eb64",
          "sha1": "37f0a207574ce6951a93147215efcf8e6cb64479",
          "md5": "804a91da3f3a9b91f653c0302dc95058"
        }
      ]
    }
  ]
}
