{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectorAPI",
    "version": "0.1.9.2-STABLE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.9.2-STABLE.jar",
          "url": "ConnectorAPI-0.1.9.2-STABLE.jar",
          "size": 30997,
          "sha512": "83453f1cfd8455502627d245dd7798b7f1ee899fb185ae8d7f09348e505d6b343f0f80778a6db7ea340e4f7323bc36cf244d3414edbe2009491e507c72526fce",
          "sha256": "11fd909b5674de26febd53e87a1ce8bbd3e65b86e1487d46c0e9e603a18860ed",
          "sha1": "e16f988d54d1ea5348b2133def1eddb814ebe635",
          "md5": "da810c0fc1b58bbbaeef594140751999"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "ConnectorAPI-0.1.9.2-STABLE.jar",
          "url": "ConnectorAPI-0.1.9.2-STABLE.jar",
          "size": 30997,
          "sha512": "83453f1cfd8455502627d245dd7798b7f1ee899fb185ae8d7f09348e505d6b343f0f80778a6db7ea340e4f7323bc36cf244d3414edbe2009491e507c72526fce",
          "sha256": "11fd909b5674de26febd53e87a1ce8bbd3e65b86e1487d46c0e9e603a18860ed",
          "sha1": "e16f988d54d1ea5348b2133def1eddb814ebe635",
          "md5": "da810c0fc1b58bbbaeef594140751999"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.9.2-STABLE-sources.jar",
          "url": "ConnectorAPI-0.1.9.2-STABLE-sources.jar",
          "size": 17455,
          "sha512": "955aea790a1661b69c47bfd428c41daf54aa011ef20e7715954ccd34dd0c358ed69c03b4e23337bb5c14bc355742055eed6946b06586e6ca6767e31f6d021262",
          "sha256": "9ddc025dde656719fc13aac62f02849f461cfee30e6db0f925fc943497c2cb2a",
          "sha1": "f5b1f9e1a53edf8b8d8a5dbf124259e50328df5e",
          "md5": "535071617c1b24108cc9c119aabbfc38"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.9.2-STABLE-javadoc.jar",
          "url": "ConnectorAPI-0.1.9.2-STABLE-javadoc.jar",
          "size": 154320,
          "sha512": "ee27c4195f2285c949662d4497372b6788fcbb6fa6776a05676e3cdbfbc7dca7ff21823db8ad6ec6cc2c830eb3ea4e0da2242ad78f6a5edcefe18dc837efd5fc",
          "sha256": "077e0fbde7c7da5168413593515bdd5cc3996142e8d1549296ef297d166e4c42",
          "sha1": "9427c8e02b4e4bd2a2a35bf2d67fa1faa65f60e8",
          "md5": "52d51c1961d2e58139661aac29eccc30"
        }
      ]
    }
  ]
}
