{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectorAPI",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.1.jar",
          "url": "ConnectorAPI-0.1.1.jar",
          "size": 21472,
          "sha512": "c16f1a8790d22fc85b5f4da09c27c4338c82dff59690036afab50119dfb8eb9d50e6502ab0998e492fefc7de4e3e8e7f10add4b935b104d3e9ee0f9573551e12",
          "sha256": "dcfb85f9a4afa79124aea1c8fe1efab759e5fe8fd9bd50629f72d3ed89a30db2",
          "sha1": "6c036ca388e5e7e5d62df0b3afdf97fb66b73443",
          "md5": "4919570f5e71111c1aacc39e01824dd4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-base",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-base",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-graphics",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-graphics",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-controls",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-controls",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-fxml",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-fxml",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "ConnectorAPI-0.1.1.jar",
          "url": "ConnectorAPI-0.1.1.jar",
          "size": 21472,
          "sha512": "c16f1a8790d22fc85b5f4da09c27c4338c82dff59690036afab50119dfb8eb9d50e6502ab0998e492fefc7de4e3e8e7f10add4b935b104d3e9ee0f9573551e12",
          "sha256": "dcfb85f9a4afa79124aea1c8fe1efab759e5fe8fd9bd50629f72d3ed89a30db2",
          "sha1": "6c036ca388e5e7e5d62df0b3afdf97fb66b73443",
          "md5": "4919570f5e71111c1aacc39e01824dd4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.1-sources.jar",
          "url": "ConnectorAPI-0.1.1-sources.jar",
          "size": 12726,
          "sha512": "5c9bbf10620f1c6c5c099edab17f948453bae90439c58de1f37f40de0f4394a5ed5328764c944ca356a27bfa29da94553003979065cb9ad91549d3401b0bb35f",
          "sha256": "2b409c673150ba18f1e7df0313f14912cfab88c431624b789bde030bf2d7e244",
          "sha1": "d73f5e5f30f6a88815c5fb4768695b6b85ae1afa",
          "md5": "45a4dcc37f0cc9ba1c0512bcab35512f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.1-javadoc.jar",
          "url": "ConnectorAPI-0.1.1-javadoc.jar",
          "size": 135520,
          "sha512": "4ad8544791d9b3f3408ecf4ba56080562512ebe9bcc7bdd0f45622d820a4dbece5962078683f9efbd7d38b872fa7da6853148c4493bc6fb99d6a1e17bc749fe8",
          "sha256": "cd8285b2b6111bca9ddbb36a182adb39eebda1f604f6499de3c4f6adedf77a99",
          "sha1": "935b7495ba700fb710238777b18fbeea116a4fb8",
          "md5": "fa28d519b43d8035f4a7e33f2abee5eb"
        }
      ]
    }
  ]
}
