{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectorAPI",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.1.jar",
          "url": "ConnectorAPI-0.1.1.jar",
          "size": 21472,
          "sha512": "b55cc79dc5eefd13837817e43a3b6d99ee87b4cc5c7d8904e39deb597c541a7b087f24df60c03a39e57a08c93cc9fa35ed54aca2a205b40dcf1429798b1d2856",
          "sha256": "c57afdb0aef4ef84566913a8a7fbcb1f3b04aa8c954261bc5fccfb9d36f010d2",
          "sha1": "70bc6a3ead2736056cb297e54e788060c1687a7a",
          "md5": "66d73752506e787a873a3f571fc1cf5b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-base",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-base",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-graphics",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-graphics",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-controls",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-controls",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-fxml",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-fxml",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "ConnectorAPI-0.1.1.jar",
          "url": "ConnectorAPI-0.1.1.jar",
          "size": 21472,
          "sha512": "b55cc79dc5eefd13837817e43a3b6d99ee87b4cc5c7d8904e39deb597c541a7b087f24df60c03a39e57a08c93cc9fa35ed54aca2a205b40dcf1429798b1d2856",
          "sha256": "c57afdb0aef4ef84566913a8a7fbcb1f3b04aa8c954261bc5fccfb9d36f010d2",
          "sha1": "70bc6a3ead2736056cb297e54e788060c1687a7a",
          "md5": "66d73752506e787a873a3f571fc1cf5b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.1-sources.jar",
          "url": "ConnectorAPI-0.1.1-sources.jar",
          "size": 12726,
          "sha512": "9daa99df743e5214c8a0569ec6c9e48ba150514e95656e5d48062938569520fa2d5c082bb5091491902f3b5cc7a78c34c659ef8c78aead8d0f5e4ea197ce2916",
          "sha256": "9b8252367465fd91d426899faabf830afc3413759550cbbc7ded8ae24b0dc5c2",
          "sha1": "2632b8d24945f2b8d9348f38092d87f1448151da",
          "md5": "d9bf0af67519d83bda1a308e0a216d4c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.1-javadoc.jar",
          "url": "ConnectorAPI-0.1.1-javadoc.jar",
          "size": 135520,
          "sha512": "3fe11201ea29e8ed095e67fb26e815b9a141cf8774b26a5feab141ace78e12e99ffaa292c52b1b6724a039622db24a68b948fff58753f3ca045982f9099b5ab5",
          "sha256": "7fe81c3b385c79ed23b8e4be31df48011c250a4320a4aea1ea02753bfd18e2a0",
          "sha1": "35ec46774b14547ee926aa427dcda97ba0fac067",
          "md5": "d8ac896d606cf2258a4fe8a5993d02c3"
        }
      ]
    }
  ]
}
