{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectorAPI",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.1.jar",
          "url": "ConnectorAPI-0.1.1.jar",
          "size": 21472,
          "sha512": "8020c2ae2998542f2fcac75536837d39267298e764592424cc2ddb869c159d192c4545b4708f6012ca44fc45e1db471515ed3701d9af32daa91b228c041ab271",
          "sha256": "498e4cde6189211d0654941b21634813726656b67540df855716a0bd9a27ecab",
          "sha1": "85fccd32ba28ade8cd2d8fdf3dfc1a907b9ed7c0",
          "md5": "8dc2152e25335be2192676db5ff40686"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-base",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-base",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-graphics",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-graphics",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-controls",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-controls",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-fxml",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-fxml",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "ConnectorAPI-0.1.1.jar",
          "url": "ConnectorAPI-0.1.1.jar",
          "size": 21472,
          "sha512": "8020c2ae2998542f2fcac75536837d39267298e764592424cc2ddb869c159d192c4545b4708f6012ca44fc45e1db471515ed3701d9af32daa91b228c041ab271",
          "sha256": "498e4cde6189211d0654941b21634813726656b67540df855716a0bd9a27ecab",
          "sha1": "85fccd32ba28ade8cd2d8fdf3dfc1a907b9ed7c0",
          "md5": "8dc2152e25335be2192676db5ff40686"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.1-sources.jar",
          "url": "ConnectorAPI-0.1.1-sources.jar",
          "size": 12726,
          "sha512": "8ed7e56ed7fb03402097aff95cfa3a7ecb63cc4aec091c7ec09897b03d5e449102fb3fad42f4ce3166db311b294db49c200741e676e701ca8b0ac51e64d9e92c",
          "sha256": "4b257fb02355051fd77f26b747b3e954f41d164f85a928376fca44baf2ae7708",
          "sha1": "3d2a9366fa04fea47716b3773765e8a165245426",
          "md5": "32bc60e0db19a69019fcbacb5b49851b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.1-javadoc.jar",
          "url": "ConnectorAPI-0.1.1-javadoc.jar",
          "size": 135520,
          "sha512": "3bac401e833299fe8071e98644a4cd6bedce3a62b0083ba9a42866d65a821dd9973b7e36aa6c3a38dc8fa617d4c1476fc2cd2cff482cbd801b23a4cc7327fa9f",
          "sha256": "32dcb8fe1dc8731219f116cea2e8468bcefe63d9d13d121673296b9428b78f54",
          "sha1": "9c221a1386fe6d2856bfdef1c01dfe61a8aa6fc4",
          "md5": "ecdc0368f628ed2c39aa3c0afd14aa1f"
        }
      ]
    }
  ]
}
