{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectorAPI",
    "version": "0.1.6-STABLE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.6-STABLE.jar",
          "url": "ConnectorAPI-0.1.6-STABLE.jar",
          "size": 25475,
          "sha512": "249aa3ed664cf1c050aba88f640a4dd52c6b70537e05b9d216d04f3ca50390ee5297771ffb1cce5763f93e458853777215936daaa5715a8fee9480596bfacd27",
          "sha256": "294afa7968a2a5bc6f0669aff35632df4c7bfcb3e61bac6905ff076f1f5c58ac",
          "sha1": "5baca5885d1b5a36140f9ee898cb7fde07d6d35f",
          "md5": "62be243a1d855afd991d2295b0db618e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-base",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-base",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-graphics",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-graphics",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-controls",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-controls",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-fxml",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-fxml",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "ConnectorAPI-0.1.6-STABLE.jar",
          "url": "ConnectorAPI-0.1.6-STABLE.jar",
          "size": 25475,
          "sha512": "249aa3ed664cf1c050aba88f640a4dd52c6b70537e05b9d216d04f3ca50390ee5297771ffb1cce5763f93e458853777215936daaa5715a8fee9480596bfacd27",
          "sha256": "294afa7968a2a5bc6f0669aff35632df4c7bfcb3e61bac6905ff076f1f5c58ac",
          "sha1": "5baca5885d1b5a36140f9ee898cb7fde07d6d35f",
          "md5": "62be243a1d855afd991d2295b0db618e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.6-STABLE-sources.jar",
          "url": "ConnectorAPI-0.1.6-STABLE-sources.jar",
          "size": 14630,
          "sha512": "5f2d0a68a5de23e54afd3d9c8b43c1d55e561a98432a666da19aeac83029cf662ad50276fb947bed83762fa33676e5d7cdf1e32109de98ca1953a82f9cc8a5b4",
          "sha256": "ba304be97fbafc2bd9377e7103ecec1025bc1672b8bd271a1ab9756a76838089",
          "sha1": "e34d252ed7d6826fb97c7b4c6ac25dc0feaf0bc8",
          "md5": "a9e1e52c96aada1227d22086fd0d76ea"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.6-STABLE-javadoc.jar",
          "url": "ConnectorAPI-0.1.6-STABLE-javadoc.jar",
          "size": 145054,
          "sha512": "306046290992acff37c1b8bc5d2e4280c6a5a8b81e644e5954ef12ea5c72956c6a9349b766680f8531e283e98df63c1d601f4469d88a1750615f96ffbacebf77",
          "sha256": "3f156a9dd5c064e62050117ca7010f7d79db63c4d0ba7382eabeff18f5ba4470",
          "sha1": "f5a24df60a5a7b734987e23f00beec067ab1c3b3",
          "md5": "6c29b533f73d253215468739d9af6d38"
        }
      ]
    }
  ]
}
