{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectorAPI",
    "version": "0.1.6-STABLE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.6-STABLE.jar",
          "url": "ConnectorAPI-0.1.6-STABLE.jar",
          "size": 25475,
          "sha512": "cf1e7ea4179e1f69ec6d5276e43bb26cf5f6b3b5dc0f184a88248e768904ffedcbc030001dd66b37f8dfad5412ab80b752dbf7e2ce24e1c8f97954e4721b9053",
          "sha256": "8d300d448b4fffc56382445f5a806b3ac55aa7bcc4852a4cd46df004e956227b",
          "sha1": "b5b03d9d12cbbe365ac23e69300d3ab998bb34bc",
          "md5": "cf8e661be48e5ec8b853b100c54fe65b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-base",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-base",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-graphics",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-graphics",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-controls",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-controls",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-fxml",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-fxml",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "ConnectorAPI-0.1.6-STABLE.jar",
          "url": "ConnectorAPI-0.1.6-STABLE.jar",
          "size": 25475,
          "sha512": "cf1e7ea4179e1f69ec6d5276e43bb26cf5f6b3b5dc0f184a88248e768904ffedcbc030001dd66b37f8dfad5412ab80b752dbf7e2ce24e1c8f97954e4721b9053",
          "sha256": "8d300d448b4fffc56382445f5a806b3ac55aa7bcc4852a4cd46df004e956227b",
          "sha1": "b5b03d9d12cbbe365ac23e69300d3ab998bb34bc",
          "md5": "cf8e661be48e5ec8b853b100c54fe65b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.6-STABLE-sources.jar",
          "url": "ConnectorAPI-0.1.6-STABLE-sources.jar",
          "size": 14630,
          "sha512": "64cec2128219ff1f24e217777d9650167d3bd03fc6ab8a2680d7b5e50eed4988a85b919d4b952c48dac86b5aef7bcf3db2055ae67cbb918577068d7e26332b92",
          "sha256": "b236c19607ca8e99df7250cd7e61d47a67c4b4904bd93cb906f051e7f65b9653",
          "sha1": "dfe552398accd156dd53fc77cc559ed67b987549",
          "md5": "319a299e91004ef76d8bf2ed9b6c2b36"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.6-STABLE-javadoc.jar",
          "url": "ConnectorAPI-0.1.6-STABLE-javadoc.jar",
          "size": 145054,
          "sha512": "57c9679b4613b07d0bd8a35a12cd5afb3831702521d31f69615ab09e1dfe7b32cbdc20e1d0e8996b64dfb3852486d5b8f734c72e11472b465492e5769964f0bf",
          "sha256": "b0593eda19e6ead7baefe461aea0bcff4327a6519cd6b5808488668b69f6c926",
          "sha1": "37cee813f35bae2cdc8fa1f201365977110cbaee",
          "md5": "e8e1dc915bc2622777711b253683f005"
        }
      ]
    }
  ]
}
