{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectorAPI",
    "version": "0.1.6-STABLE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.6-STABLE.jar",
          "url": "ConnectorAPI-0.1.6-STABLE.jar",
          "size": 25475,
          "sha512": "50d576fcf36880b1f878f6bfae4b0de630e3516180c1b7b5de049675489a1b93e11d9757b560ead0dc4f48ffe2b9ac24a381c92b7f6d6b380b4d4790d7f325c5",
          "sha256": "028bb10f49773ab26880ae19c1e696d0bca259860a1588e8390a5be0246194e8",
          "sha1": "d6aa5a07b455a5df04a2bfad587090ccde8f76c8",
          "md5": "221637eee8ba463874290854e7b2c368"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-base",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-base",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-graphics",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-graphics",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-controls",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-controls",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-fxml",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-fxml",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "ConnectorAPI-0.1.6-STABLE.jar",
          "url": "ConnectorAPI-0.1.6-STABLE.jar",
          "size": 25475,
          "sha512": "50d576fcf36880b1f878f6bfae4b0de630e3516180c1b7b5de049675489a1b93e11d9757b560ead0dc4f48ffe2b9ac24a381c92b7f6d6b380b4d4790d7f325c5",
          "sha256": "028bb10f49773ab26880ae19c1e696d0bca259860a1588e8390a5be0246194e8",
          "sha1": "d6aa5a07b455a5df04a2bfad587090ccde8f76c8",
          "md5": "221637eee8ba463874290854e7b2c368"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.6-STABLE-sources.jar",
          "url": "ConnectorAPI-0.1.6-STABLE-sources.jar",
          "size": 14630,
          "sha512": "3b095049f4794b567093a4902e5ae110f4fc269d9cfd117c72c30adbc3b8feb9ea10e9d03ee503a2097708d20499c88eaea413f9b8d374ba9445d31576ab3a91",
          "sha256": "a6892b44342816d746f52184911315d3a70b70d657212535d103df91b4b29656",
          "sha1": "b8a45131ebcdb4b5464ec1b32a142d36866cfeba",
          "md5": "dee13592e570dd40fe87faef4702d225"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.6-STABLE-javadoc.jar",
          "url": "ConnectorAPI-0.1.6-STABLE-javadoc.jar",
          "size": 145054,
          "sha512": "61a848d9fe6ffa209cb9e9265a4371a9322f293306917a0346b1c1c5e6fe1f576d52ff45034ace9f17628bb19b08ea706339f7e3d4e725e7085457dad378f1c2",
          "sha256": "e60a5e96150ce807c8fa76d009fe0029cb2a6cafadc6148f540c556252353aa1",
          "sha1": "c5a5a984fed1afccef860d211c5f168e512002d6",
          "md5": "86910b95653aac15ce09667f951967d3"
        }
      ]
    }
  ]
}
