{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectorAPI",
    "version": "0.1.3.2-Alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.2-Alpha.jar",
          "url": "ConnectorAPI-0.1.3.2-Alpha.jar",
          "size": 25584,
          "sha512": "0fb8a432548c76cb4d206fa6c5102dfd84efc0abdaa241902c66859f9fe60fd1f8e9fbd88a43381a58568c8e848e8c4f212941db941eff87d3407cbea753172c",
          "sha256": "dda144a67df7c196b9acf28132bf747b5488cf18f591d3b806ef584ecce262b9",
          "sha1": "6ecd5a67670db9df34a56ef1ad043fe91ed44580",
          "md5": "ebf3bf613d8ae64a5d5107d2ff7a8db0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-base",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-base",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-graphics",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-graphics",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-controls",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-controls",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-fxml",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-fxml",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.2-Alpha.jar",
          "url": "ConnectorAPI-0.1.3.2-Alpha.jar",
          "size": 25584,
          "sha512": "0fb8a432548c76cb4d206fa6c5102dfd84efc0abdaa241902c66859f9fe60fd1f8e9fbd88a43381a58568c8e848e8c4f212941db941eff87d3407cbea753172c",
          "sha256": "dda144a67df7c196b9acf28132bf747b5488cf18f591d3b806ef584ecce262b9",
          "sha1": "6ecd5a67670db9df34a56ef1ad043fe91ed44580",
          "md5": "ebf3bf613d8ae64a5d5107d2ff7a8db0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.2-Alpha-sources.jar",
          "url": "ConnectorAPI-0.1.3.2-Alpha-sources.jar",
          "size": 14559,
          "sha512": "b96f116bfbab48c0d20e743c6f4b4620bc3e9cc49e9c487d1b21ae811e4d00247f5887dcf41cfdd5687f1b58fda3f8a71820ae4b43fac99492d6a581b276473b",
          "sha256": "f6fb4c2b2141b04c27475402be4bf94b5a6ffcb1516e47b6a856925ae6539f5d",
          "sha1": "b63dc2b75cd0c92aefae86e0dbafe1355bcfab75",
          "md5": "68ed1f2fb15faec9ddae175f9004faad"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.2-Alpha-javadoc.jar",
          "url": "ConnectorAPI-0.1.3.2-Alpha-javadoc.jar",
          "size": 145522,
          "sha512": "664a7fb224a6e07e70f986e5d70591b97beade02479aaef2a6e02d0468173bddf99f5ba532c26758b7cc2112f4c9da5309777a6bda8faea746fc5d40293a3eee",
          "sha256": "2245f45ca545575d093a3e5922099e57579ffd508f135cb09e5b4a30198f4957",
          "sha1": "812ca9dca29d680341252d5d0b03c416669e08c0",
          "md5": "c1cd03461157842f3fe4d3fbba7d3b11"
        }
      ]
    }
  ]
}
