{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectorAPI",
    "version": "0.1.3.2-Alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.2-Alpha.jar",
          "url": "ConnectorAPI-0.1.3.2-Alpha.jar",
          "size": 25886,
          "sha512": "6fc6a79580b1c39c77c4e9ffe791a75b29db8ba44bf09c91e3d93b21463943976e21573cd9c1300bd93ab14678956bf51e3a426c7cc977a39224cee7a8af1598",
          "sha256": "f0cd7f78d1194bcfbe160f199bbbd09680ca4813d3d4e013d35f1163238154e7",
          "sha1": "8b9cab05b34db847995bb51e8dd420b33d03691c",
          "md5": "bf382fe1fd128f75406300c2eb710726"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-base",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-base",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-graphics",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-graphics",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-controls",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-controls",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-fxml",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-fxml",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.2-Alpha.jar",
          "url": "ConnectorAPI-0.1.3.2-Alpha.jar",
          "size": 25886,
          "sha512": "6fc6a79580b1c39c77c4e9ffe791a75b29db8ba44bf09c91e3d93b21463943976e21573cd9c1300bd93ab14678956bf51e3a426c7cc977a39224cee7a8af1598",
          "sha256": "f0cd7f78d1194bcfbe160f199bbbd09680ca4813d3d4e013d35f1163238154e7",
          "sha1": "8b9cab05b34db847995bb51e8dd420b33d03691c",
          "md5": "bf382fe1fd128f75406300c2eb710726"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.2-Alpha-sources.jar",
          "url": "ConnectorAPI-0.1.3.2-Alpha-sources.jar",
          "size": 14917,
          "sha512": "9e4b34febe83202816e8d9307e5c5116714df5b7be1244a3a2587fe2a7c73af4117255ab466aec3757ed732d9f38b43f652f92c45bfe3eae584f7992b82fc2e8",
          "sha256": "562345e3e40bbf1c8c95c02a822acb84fad0dede21fb640938f24d5dab57f43b",
          "sha1": "cc2e6a47daf8f8c823aa87e5055f50b6f200cfa3",
          "md5": "4d0f88fd52bdfb1059a8feb800a0596c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.2-Alpha-javadoc.jar",
          "url": "ConnectorAPI-0.1.3.2-Alpha-javadoc.jar",
          "size": 145756,
          "sha512": "cac336beb824697aa01385775dde71ff02427c47c057df304fd4bc7acc4c576c3dda3effec18b1a85529eea8679ed198260a4edb783cf5379b09d45489001564",
          "sha256": "7185259f823d6f18ddafa117e7d09d2dcca0e0bca94eb9cf8aa34368a42e3dc2",
          "sha1": "15aadb6f1d8b05e3765cd86da7eede93679d38e7",
          "md5": "586f663b379f0248849f27bf8da2ca26"
        }
      ]
    }
  ]
}
