{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectorAPI",
    "version": "0.1.3.2-Alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.2-Alpha.jar",
          "url": "ConnectorAPI-0.1.3.2-Alpha.jar",
          "size": 25584,
          "sha512": "5bcf029a0c549ab2a0eef3ebb40001047276531c8ca34a0166fa9037d8b16a54f8a20198c376b44b85cbf8af50ce1b9abaa27cb532e69f831554819860f9b0a0",
          "sha256": "8adc267d951b3a84e7585bef70f9e158d92d48b659c9123d1fe8d9ef1e3b4a9c",
          "sha1": "d9101e9f49d92e9f43531799ab79786d2ff885cb",
          "md5": "cdde3c177a749d025058fc50fb4aacd9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-base",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-base",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-graphics",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-graphics",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-controls",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-controls",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-fxml",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-fxml",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.2-Alpha.jar",
          "url": "ConnectorAPI-0.1.3.2-Alpha.jar",
          "size": 25584,
          "sha512": "5bcf029a0c549ab2a0eef3ebb40001047276531c8ca34a0166fa9037d8b16a54f8a20198c376b44b85cbf8af50ce1b9abaa27cb532e69f831554819860f9b0a0",
          "sha256": "8adc267d951b3a84e7585bef70f9e158d92d48b659c9123d1fe8d9ef1e3b4a9c",
          "sha1": "d9101e9f49d92e9f43531799ab79786d2ff885cb",
          "md5": "cdde3c177a749d025058fc50fb4aacd9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.2-Alpha-sources.jar",
          "url": "ConnectorAPI-0.1.3.2-Alpha-sources.jar",
          "size": 14559,
          "sha512": "703e817b01b858c0d82480346ccff4d98b58b39f639a9f9c70522accc7b6a803d4bea51cb811dad9942f4008ad6d09fd30a9a605875533ed22809db5b28b25e4",
          "sha256": "4834432187ff633d9114f421255031bb7f073840e5f714403b294be45aab748e",
          "sha1": "a964c952aa6ffb2b1f149579fe7a498e769c6bef",
          "md5": "d6342e06d3c06186075905896e8f0bdc"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.2-Alpha-javadoc.jar",
          "url": "ConnectorAPI-0.1.3.2-Alpha-javadoc.jar",
          "size": 145522,
          "sha512": "1d427349b757bacbd4f47cabb201e1818b19be84a059b922561b7d63afd2780a8b4429f8758048e22c8fa6301fc588e528855c49be948c79ae24a15efab9ece9",
          "sha256": "4c26e4988c31cb87bf340c25720dc15852af2c053fe35e574e961c7352d171af",
          "sha1": "6c6526d329216e366713f1db82349810b6acf244",
          "md5": "c0ee5bce673e61d6b046f5c74868fc94"
        }
      ]
    }
  ]
}
