{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectLib",
    "version": "0.3.2.1-STABLE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectLib-0.3.2.1-STABLE.jar",
          "url": "ConnectLib-0.3.2.1-STABLE.jar",
          "size": 47198,
          "sha512": "5b346dc0c9a1efafbf1aa9f9e519b46a503442d57307c91ad83b427f6a7a2951f83dd880db2f4df548c4f0d8833dcebc104016937faeaea1fdc3baf6108c8136",
          "sha256": "99d1ef04a669fc3d72a43fa009277ad1e4df9d7205f0d388b9577c84cf81c35a",
          "sha1": "381cd9c9653bb419d234a21d072ae8d7fe751f61",
          "md5": "0c543367aae465534eedf2cb2629c76a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "ConnectLib-0.3.2.1-STABLE.jar",
          "url": "ConnectLib-0.3.2.1-STABLE.jar",
          "size": 47198,
          "sha512": "5b346dc0c9a1efafbf1aa9f9e519b46a503442d57307c91ad83b427f6a7a2951f83dd880db2f4df548c4f0d8833dcebc104016937faeaea1fdc3baf6108c8136",
          "sha256": "99d1ef04a669fc3d72a43fa009277ad1e4df9d7205f0d388b9577c84cf81c35a",
          "sha1": "381cd9c9653bb419d234a21d072ae8d7fe751f61",
          "md5": "0c543367aae465534eedf2cb2629c76a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectLib-0.3.2.1-STABLE-sources.jar",
          "url": "ConnectLib-0.3.2.1-STABLE-sources.jar",
          "size": 27902,
          "sha512": "cc68d5bfcba51888ef6f0f4cbba3fe1955a00910bca25d0eb31d6a34f102b3caf2191e20ec3579438e6dd39953e3376618f1a8d96f5080d0c6d5e50883fd2b5f",
          "sha256": "ce75321389c6fc272d5912c6f782a789fef7887ac09ce64ce298c6d467347faf",
          "sha1": "c57cee1c84e6f9e2cc4d3e8040c0a68cb3797104",
          "md5": "c2b01eb945defbe13a0784501954a383"
        }
      ]
    }
  ]
}
