{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectLib",
    "version": "0.3.2.1-STABLE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectLib-0.3.2.1-STABLE.jar",
          "url": "ConnectLib-0.3.2.1-STABLE.jar",
          "size": 47198,
          "sha512": "28e96123c0ce190e5abe952237d13dd07db02b953f460cce42f1ebb17d886eca9563684355575b01e93ad55f8ef9dc6d1cb9ebd46160208180eb6114d76f2e77",
          "sha256": "ba4de1cff5341522dddff8ed3c930bf2f110887630f2f86b1088175fb18263be",
          "sha1": "ee8904090f0dbfe77c048e4705cecd1bec4d67f1",
          "md5": "f3e5f8aaf2fff1bc454b09f404734536"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "ConnectLib-0.3.2.1-STABLE.jar",
          "url": "ConnectLib-0.3.2.1-STABLE.jar",
          "size": 47198,
          "sha512": "28e96123c0ce190e5abe952237d13dd07db02b953f460cce42f1ebb17d886eca9563684355575b01e93ad55f8ef9dc6d1cb9ebd46160208180eb6114d76f2e77",
          "sha256": "ba4de1cff5341522dddff8ed3c930bf2f110887630f2f86b1088175fb18263be",
          "sha1": "ee8904090f0dbfe77c048e4705cecd1bec4d67f1",
          "md5": "f3e5f8aaf2fff1bc454b09f404734536"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectLib-0.3.2.1-STABLE-sources.jar",
          "url": "ConnectLib-0.3.2.1-STABLE-sources.jar",
          "size": 27942,
          "sha512": "482bc1bd8b0f81ba50e4b809b7b9eff1008c6c9bf8f2b3144cd8e7bf4721ea7738c303b307da7affbf71bf1b926932ed4c0993695d8626a65f99ac7f2564ee73",
          "sha256": "a0c7ce8661ba827961e5c7cfde0fc65f83ce7fb6101ef623364c330ea4a5edd2",
          "sha1": "c0422afdfd0f204edf889b395ac1ccf76b0bd8cc",
          "md5": "8841007cc3d4e77008f24c8f683cfb0d"
        }
      ]
    }
  ]
}
