{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectLib",
    "version": "0.3.8.1-DEV_BUILD",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectLib-0.3.8.1-DEV_BUILD.jar",
          "url": "ConnectLib-0.3.8.1-DEV_BUILD.jar",
          "size": 52828,
          "sha512": "5f337874ea744f32d3d3dbe15b968724ec1b7bc46a2f7bb0dcaf9da2ca0465a0dc7ed17833da6a158c62a2df1fcf602b12602a7663766b07b5df2ed1cdcbccfe",
          "sha256": "b4cc5e09351f4bda72551abf9e9d03c72203456a37515813a3e1f64dc65c409e",
          "sha1": "03a4aa4835ea8eb5660d77b1765d2090e3527304",
          "md5": "fd5308862ed8080e8733cb2cf04e0ff8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "ConnectLib-0.3.8.1-DEV_BUILD.jar",
          "url": "ConnectLib-0.3.8.1-DEV_BUILD.jar",
          "size": 52828,
          "sha512": "5f337874ea744f32d3d3dbe15b968724ec1b7bc46a2f7bb0dcaf9da2ca0465a0dc7ed17833da6a158c62a2df1fcf602b12602a7663766b07b5df2ed1cdcbccfe",
          "sha256": "b4cc5e09351f4bda72551abf9e9d03c72203456a37515813a3e1f64dc65c409e",
          "sha1": "03a4aa4835ea8eb5660d77b1765d2090e3527304",
          "md5": "fd5308862ed8080e8733cb2cf04e0ff8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectLib-0.3.8.1-DEV_BUILD-sources.jar",
          "url": "ConnectLib-0.3.8.1-DEV_BUILD-sources.jar",
          "size": 29789,
          "sha512": "4ca83d460b9b9347db3081b4dd1aaf215cfdd3806d97a4a120b751ccd657820a5c117db5d74d90eb96c4ff5d765dbe81712888db08a5340334b055feda8a462f",
          "sha256": "dd69fde4bae9509e94b6ed5d946288052df861dadae673ac3e372be76d9b4490",
          "sha1": "95e933baeeefa4f4bf89c9fb65aa8ca3e7866bef",
          "md5": "26d603eef7f6aea6645c21b7507f96e6"
        }
      ]
    }
  ]
}
