{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectLib",
    "version": "0.3.8.1-DEV_BUILD",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectLib-0.3.8.1-DEV_BUILD.jar",
          "url": "ConnectLib-0.3.8.1-DEV_BUILD.jar",
          "size": 52828,
          "sha512": "72661ce2e077d1f0a54fd94512ba6b4e7b1a93b7725c419737aeb7ddd82c61a7265154d69b5925b47afcfb9afaae57ca4ba4411b0d44a5c7281cef9ce5993de4",
          "sha256": "8b1c7b42d2382861c86b6ec7fd2934bc5e6422c48ceae2641421d3455bad8290",
          "sha1": "90f653f7ff7e3f42bd0a7f01727e2f39b74d7297",
          "md5": "6d615973330b99019cd1dfc1df7c35f5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "ConnectLib-0.3.8.1-DEV_BUILD.jar",
          "url": "ConnectLib-0.3.8.1-DEV_BUILD.jar",
          "size": 52828,
          "sha512": "72661ce2e077d1f0a54fd94512ba6b4e7b1a93b7725c419737aeb7ddd82c61a7265154d69b5925b47afcfb9afaae57ca4ba4411b0d44a5c7281cef9ce5993de4",
          "sha256": "8b1c7b42d2382861c86b6ec7fd2934bc5e6422c48ceae2641421d3455bad8290",
          "sha1": "90f653f7ff7e3f42bd0a7f01727e2f39b74d7297",
          "md5": "6d615973330b99019cd1dfc1df7c35f5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectLib-0.3.8.1-DEV_BUILD-sources.jar",
          "url": "ConnectLib-0.3.8.1-DEV_BUILD-sources.jar",
          "size": 29789,
          "sha512": "bc698083bc866a3671f94939b42ea15af056e8f181c298c725d58030f03bef7fc88f4706eb4b8a4fe3b75615d958ec3eb5c236cc23714828aa84726b32a782b1",
          "sha256": "04258c65a4041916366554f4908477500830462c6d96ae2ffd6422f321b530f7",
          "sha1": "44165e99ff99434cfbd0cc7628a19717b3e507e5",
          "md5": "232abd39188036c4bc3b5032a9d1f136"
        }
      ]
    }
  ]
}
