{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectLib",
    "version": "0.3.8.1-DEV_BUILD",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectLib-0.3.8.1-DEV_BUILD.jar",
          "url": "ConnectLib-0.3.8.1-DEV_BUILD.jar",
          "size": 52828,
          "sha512": "aed06afab278ebbe836ee5465129b673899cfbdcbfcd224c45b19b23bbc679ee36b1411040a11ce73fa67fe8b6a233417917a08de3ffc8109d31f196e88f6db5",
          "sha256": "88136f58910b7d6578e7e36f0506e6012e1fab041ceaa715ab9b03772c87f07b",
          "sha1": "bdbb0ceefe0d7581811e7fdb4e4c14b03dbf753f",
          "md5": "80fa45af88345227968c421d3fbd2469"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "ConnectLib-0.3.8.1-DEV_BUILD.jar",
          "url": "ConnectLib-0.3.8.1-DEV_BUILD.jar",
          "size": 52828,
          "sha512": "aed06afab278ebbe836ee5465129b673899cfbdcbfcd224c45b19b23bbc679ee36b1411040a11ce73fa67fe8b6a233417917a08de3ffc8109d31f196e88f6db5",
          "sha256": "88136f58910b7d6578e7e36f0506e6012e1fab041ceaa715ab9b03772c87f07b",
          "sha1": "bdbb0ceefe0d7581811e7fdb4e4c14b03dbf753f",
          "md5": "80fa45af88345227968c421d3fbd2469"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectLib-0.3.8.1-DEV_BUILD-sources.jar",
          "url": "ConnectLib-0.3.8.1-DEV_BUILD-sources.jar",
          "size": 29789,
          "sha512": "a516079bb7ec97b8bcc85f399607519a562fa839d393667c2655dba1f352bdcd815258f771b51ebb3c1796442d8c3ee470e0002cbbe9d7afa738d7170177c003",
          "sha256": "09bce46896e89735bbf1c0b7c280fb1a295c769f2278f8a5ec73dca47de31fff",
          "sha1": "58ee544e9a65fd5df51044835eefdbd2c7087d38",
          "md5": "e5d7471ddf9b35c6743c453992e0af30"
        }
      ]
    }
  ]
}
