{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectorAPI",
    "version": "0.1.3.0-Alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.0-Alpha.jar",
          "url": "ConnectorAPI-0.1.3.0-Alpha.jar",
          "size": 24711,
          "sha512": "e4a401c4abba0e1231fbecc710aafcd44feae8a701fd3719325935056dd7a5978561fcc1eeae7ddf1edf9521d557c28df242941a58d7d541faf8ae65e5572893",
          "sha256": "ee3aabd9c3d7cf184547e5b7b444d24f8db5281269de1b7e54ea739c846e0e2a",
          "sha1": "b050318afed41cb6e4f0bc6317db0be5d2577848",
          "md5": "d18ae9a07d06d7b24db1803db9c7d7b5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-base",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-base",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-graphics",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-graphics",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-controls",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-controls",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-fxml",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-fxml",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.0-Alpha.jar",
          "url": "ConnectorAPI-0.1.3.0-Alpha.jar",
          "size": 24711,
          "sha512": "e4a401c4abba0e1231fbecc710aafcd44feae8a701fd3719325935056dd7a5978561fcc1eeae7ddf1edf9521d557c28df242941a58d7d541faf8ae65e5572893",
          "sha256": "ee3aabd9c3d7cf184547e5b7b444d24f8db5281269de1b7e54ea739c846e0e2a",
          "sha1": "b050318afed41cb6e4f0bc6317db0be5d2577848",
          "md5": "d18ae9a07d06d7b24db1803db9c7d7b5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.0-Alpha-sources.jar",
          "url": "ConnectorAPI-0.1.3.0-Alpha-sources.jar",
          "size": 13681,
          "sha512": "7fa80e596382c8203b1cc37653edb9628f38976bb6299355884956572f7bd5cc86e79b96be38be94167ae2a53f28d99fd877bdd317e327f212908811f2461de8",
          "sha256": "0cd0b88a334f697491a9a5338bb0a6c15a4aa6c4203ca00f33acd0dc91441c3c",
          "sha1": "ed0e6126a439f612d4f1ad2437f58b07f37161d3",
          "md5": "2281d8b135924372f3386c9da175f2bc"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.0-Alpha-javadoc.jar",
          "url": "ConnectorAPI-0.1.3.0-Alpha-javadoc.jar",
          "size": 144011,
          "sha512": "2c4b905c44d361409320c310f5bf59ca2cb8117cb77fd48753c9946d85e6fe23cb290a1d852a954165821eb114dfae5608e023c8c973a46f4d606b009101b7ec",
          "sha256": "4e74c67d0cf99f5195623186ccbd6510c74d5079752cbbb88854fca53074b55d",
          "sha1": "0bbfa446aa88783f864d03e99e5265dbb5535263",
          "md5": "aa07ebfc5f037095d4ee340cbc1447a1"
        }
      ]
    }
  ]
}
