{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectorAPI",
    "version": "0.1.3.0-Alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.0-Alpha.jar",
          "url": "ConnectorAPI-0.1.3.0-Alpha.jar",
          "size": 25646,
          "sha512": "5969957a37ba131eab91ebee9a3e7a9bbde2ead7130204071a909f975ef98b74a1490e94c1e0fc003dc5cd0ea3638fb6388bb0eac160ff309d1b9a78c5331832",
          "sha256": "87df6c66deeb65b1d28b8378405f36633fde05451c6210ba396f0a2d63811200",
          "sha1": "c13c8f1756fc336f7e872dda85d4f928ae1e6a9d",
          "md5": "a6a1a218d99c6dd3804b14dcd3f638f8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-base",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-base",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-graphics",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-graphics",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-controls",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-controls",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-fxml",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-fxml",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.0-Alpha.jar",
          "url": "ConnectorAPI-0.1.3.0-Alpha.jar",
          "size": 25646,
          "sha512": "5969957a37ba131eab91ebee9a3e7a9bbde2ead7130204071a909f975ef98b74a1490e94c1e0fc003dc5cd0ea3638fb6388bb0eac160ff309d1b9a78c5331832",
          "sha256": "87df6c66deeb65b1d28b8378405f36633fde05451c6210ba396f0a2d63811200",
          "sha1": "c13c8f1756fc336f7e872dda85d4f928ae1e6a9d",
          "md5": "a6a1a218d99c6dd3804b14dcd3f638f8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.0-Alpha-sources.jar",
          "url": "ConnectorAPI-0.1.3.0-Alpha-sources.jar",
          "size": 14549,
          "sha512": "e44c78a8ca53b132ebb131629dc01a45fa5e2dbdc7c369768aaf189f396b5f59117448902c6d7f95f31f49bd0592203b7381f594dcad314a01f7a2b076b1bbbb",
          "sha256": "0b5cb31e0da0e00f1617806683f3067bbeae64acf079ed0fcd3be5bfad1fea11",
          "sha1": "c2c03a07071feeabe8dcafb3d29bb4679460772f",
          "md5": "37d0b75cd86d71c993c1ae5b233c7247"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.0-Alpha-javadoc.jar",
          "url": "ConnectorAPI-0.1.3.0-Alpha-javadoc.jar",
          "size": 144911,
          "sha512": "49e8de665cedcd5c1460cb9d69aa9b076694bd53319514dec54a31d3a69305d11968b223b0b5e07071dca7a0671eff47bb1df6d398b8a34ca9386af45528f0cc",
          "sha256": "aac3840b852a37e71424a871d2ff5912ac99cd7b5ae635a83bb1244918ae7bef",
          "sha1": "472feb816754f4a0f665bf5d31f77047ded689c6",
          "md5": "0eba5ba648de50d465c9cb619ca7b976"
        }
      ]
    }
  ]
}
