{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectorAPI",
    "version": "0.1.3.16-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.16-SNAPSHOT.jar",
          "url": "ConnectorAPI-0.1.3.16-SNAPSHOT.jar",
          "size": 31910,
          "sha512": "d52926502dc13ddcc7bf5d54c9e3be13798eae315f2cdcdc3265389f951bce3154d727de2ca81f86d3b53cf3038d1aeab9e903e7da9cc9db6695218e30ed868c",
          "sha256": "9e21c40d3affb99b9fb9ff18f9def20a21f497820888c763384f5ec20ec07af7",
          "sha1": "40358e6a4a172fa9d56b3f7fa447f15a9ae9e951",
          "md5": "e28c53b8d3ee2f7487ed0a32a7c7717a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-base",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-base",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-graphics",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-graphics",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-controls",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-controls",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-fxml",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-fxml",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.16-SNAPSHOT.jar",
          "url": "ConnectorAPI-0.1.3.16-SNAPSHOT.jar",
          "size": 31910,
          "sha512": "d52926502dc13ddcc7bf5d54c9e3be13798eae315f2cdcdc3265389f951bce3154d727de2ca81f86d3b53cf3038d1aeab9e903e7da9cc9db6695218e30ed868c",
          "sha256": "9e21c40d3affb99b9fb9ff18f9def20a21f497820888c763384f5ec20ec07af7",
          "sha1": "40358e6a4a172fa9d56b3f7fa447f15a9ae9e951",
          "md5": "e28c53b8d3ee2f7487ed0a32a7c7717a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.16-SNAPSHOT-sources.jar",
          "url": "ConnectorAPI-0.1.3.16-SNAPSHOT-sources.jar",
          "size": 18271,
          "sha512": "51ed1bed6b337a9631dc6bab47651d216cdb5fa084af0aa7de6a93b9b22c946e4d8da812854e571b6d225a976daff25c31595e688e3bf0503e48a907007a3809",
          "sha256": "680517f960d20e2a0c3177b05dffb74235ffa9ba9c8f2d4c17bfbdc99c4296f8",
          "sha1": "1af19644762a10626add43f0a00f584db5641118",
          "md5": "a22b3e3ec188b83347358e14c251ae49"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.16-SNAPSHOT-javadoc.jar",
          "url": "ConnectorAPI-0.1.3.16-SNAPSHOT-javadoc.jar",
          "size": 152540,
          "sha512": "2acc7b5df7bd1e89db651f3ce0307da27a7954a01ae5b43e4261b37b15473fc2cd1dfc196848597d9e3c4d34114018caca3a98f23266042b6cdaba36d3db9129",
          "sha256": "78c06e6e2d186e2f104bc38b842e389722c3e05870271bf659105b9c35786de0",
          "sha1": "3228b9b6d80e0a770cf1e2d1947887675f0c838c",
          "md5": "5e7444bffb882f30590241e7a6b32c40"
        }
      ]
    }
  ]
}
