{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectorAPI",
    "version": "0.1.3.16-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.16-SNAPSHOT.jar",
          "url": "ConnectorAPI-0.1.3.16-SNAPSHOT.jar",
          "size": 31910,
          "sha512": "d766279df73e7d88949905776a2a22f238dea5fc788cc8c32c732b8cfc8e6b62e43036d33e8352dab55f0eab9590c153516644865bd9a9caf8edd141a43f7558",
          "sha256": "4f99b1e7f0b9ae6637c970199af6011180f77ab50b58a1700a4ff285146d3357",
          "sha1": "b991f5ee628684d81dcefb53fcbe2b56853095cf",
          "md5": "8b3f6f54c764d6ebead6f39a00169753"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-base",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-base",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-graphics",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-graphics",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-controls",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-controls",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-fxml",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-fxml",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.16-SNAPSHOT.jar",
          "url": "ConnectorAPI-0.1.3.16-SNAPSHOT.jar",
          "size": 31910,
          "sha512": "d766279df73e7d88949905776a2a22f238dea5fc788cc8c32c732b8cfc8e6b62e43036d33e8352dab55f0eab9590c153516644865bd9a9caf8edd141a43f7558",
          "sha256": "4f99b1e7f0b9ae6637c970199af6011180f77ab50b58a1700a4ff285146d3357",
          "sha1": "b991f5ee628684d81dcefb53fcbe2b56853095cf",
          "md5": "8b3f6f54c764d6ebead6f39a00169753"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.16-SNAPSHOT-sources.jar",
          "url": "ConnectorAPI-0.1.3.16-SNAPSHOT-sources.jar",
          "size": 18271,
          "sha512": "05654cacbb8a278dc3f64111faf1d8b83d198e8b8112738c432c6ad65f09ffae18d21bb286a4460da2b4a682df8cbb96149337214e772673aa22007da1065dfd",
          "sha256": "02a962faf1d630e47e6fa9cf6335324192c1f437f5179782a20c431ecc53defd",
          "sha1": "f894a1da9a7bd32e287a6caafcb30ae5fbe6827a",
          "md5": "dcd399b87bfcab2615e1b78db828cfcc"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.16-SNAPSHOT-javadoc.jar",
          "url": "ConnectorAPI-0.1.3.16-SNAPSHOT-javadoc.jar",
          "size": 152540,
          "sha512": "328cd377cd19aa9949f2db512c0292639d39af498d92dd9674554b643371d6616d33e0c55a16cfb3f05de25deced4c1a272ea5022f60f3728211486c31ebc36c",
          "sha256": "1438ea01e64e4e00e6b3433bf30ae9be28be5728b8bd38bc9f4e57f27132a138",
          "sha1": "ec0103153e893cc9c30759015bb751f4a88b951a",
          "md5": "f2a60f0e3a0c806f48c294840216f8b9"
        }
      ]
    }
  ]
}
