{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectLib",
    "version": "0.3.9.1-STABLE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectLib-0.3.9.1-STABLE.jar",
          "url": "ConnectLib-0.3.9.1-STABLE.jar",
          "size": 53151,
          "sha512": "703c7e408c02febdf23beecbf8fce08e32d38774132e25860aa83578ab647740e070c478760f9af8065c33c28ce3066759dead6d3cabbd779195948874f1299b",
          "sha256": "86015ea16204485737ca1ad5c31da63f7da55556e0a4ee014ba3338a61cb2ee3",
          "sha1": "ad1a40b680f47b576e3c78d0a89463f6ec9f1612",
          "md5": "df4d3f8306986753c5357e885494c0dc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "ConnectLib-0.3.9.1-STABLE.jar",
          "url": "ConnectLib-0.3.9.1-STABLE.jar",
          "size": 53151,
          "sha512": "703c7e408c02febdf23beecbf8fce08e32d38774132e25860aa83578ab647740e070c478760f9af8065c33c28ce3066759dead6d3cabbd779195948874f1299b",
          "sha256": "86015ea16204485737ca1ad5c31da63f7da55556e0a4ee014ba3338a61cb2ee3",
          "sha1": "ad1a40b680f47b576e3c78d0a89463f6ec9f1612",
          "md5": "df4d3f8306986753c5357e885494c0dc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectLib-0.3.9.1-STABLE-sources.jar",
          "url": "ConnectLib-0.3.9.1-STABLE-sources.jar",
          "size": 30221,
          "sha512": "65184c90ed1a36cac302aa9f63463e7cccbe7d5a2ccf7b936acaa593e27a2794653f92d2e95210940e2071824fe9bb47f634d5359f41eae47b187891b5643ead",
          "sha256": "8df92f1593f432db0806da8aca494da2dbb90ebd07a13f42591b2a04823d4b38",
          "sha1": "1dd7688f21ee8e6846b59f34333ff1679e7f516c",
          "md5": "ae228845a99d07c93928912001b99251"
        }
      ]
    }
  ]
}
