{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.orbit",
    "module": "Orbit",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "Orbit-0.2.0.jar",
          "url": "Orbit-0.2.0.jar",
          "size": 16907,
          "sha512": "071a35c5306ad1e9c5c288f3517547b1feb8c18256d80c70e08a9daa91bb58aafdf7c164fa60d336a8ea121b6626da0e96d2a85cbea078d08a0edc8b8bc999cd",
          "sha256": "7cf9d3d96a4e7f7cad55e49381ccd0bbe1f5672c1cdffd4971510f139aeb769b",
          "sha1": "c6560d5bd7d6fd0cc2d1898fd0be283eaa43fa6f",
          "md5": "3debf11ba23be9d55fd46c2e3b8ae45c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "6.10.0.202406032230-r"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.4.14"
          }
        }
      ],
      "files": [
        {
          "name": "Orbit-0.2.0.jar",
          "url": "Orbit-0.2.0.jar",
          "size": 16907,
          "sha512": "071a35c5306ad1e9c5c288f3517547b1feb8c18256d80c70e08a9daa91bb58aafdf7c164fa60d336a8ea121b6626da0e96d2a85cbea078d08a0edc8b8bc999cd",
          "sha256": "7cf9d3d96a4e7f7cad55e49381ccd0bbe1f5672c1cdffd4971510f139aeb769b",
          "sha1": "c6560d5bd7d6fd0cc2d1898fd0be283eaa43fa6f",
          "md5": "3debf11ba23be9d55fd46c2e3b8ae45c"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "Orbit-0.2.0-fat.jar",
          "url": "Orbit-0.2.0-fat.jar",
          "size": 6629019,
          "sha512": "3c034909bb7a98d1cc2b9ae3cf38b780db030d31241078232ad8a66edbdaa73237bacc3fe993b7e8e762efec3493b3de06048fe3113470f3d1e81a94b130308c",
          "sha256": "da60663f2d71df1b3de302d44d461b50ccf50a12632306b615f15faf08fa5f01",
          "sha1": "19ffbbef2451a5e04d4f4bb07ce2029e886a3f3a",
          "md5": "24031b2a10040cde8bc4239508ebbbe8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "Orbit-0.2.0-sources.jar",
          "url": "Orbit-0.2.0-sources.jar",
          "size": 8126,
          "sha512": "8a0f0ff01cb1f4977dd6161b4cd68dfd83f12dbd97ea29f745646471f68a93de6da5b64cb1323b3d70deabaae9d4f149cf88bac9c30299bbb9a35c3d90daa67d",
          "sha256": "fd5586ae65e537d11b94b1f31a6680a221241c62c6a8d8d49d812a85d086238f",
          "sha1": "e413f4ba2ef7b91125315050f1c2056f3520495c",
          "md5": "d808e6757b909d8b2f5c0a8415e2edc8"
        }
      ]
    }
  ]
}
