{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.orbit",
    "module": "Orbit",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "Orbit-0.2.0.jar",
          "url": "Orbit-0.2.0.jar",
          "size": 6623213,
          "sha512": "b191a1a9d60d0a54b0b6e7f89f73a6804b4808c7e3a8e969bd242065a692a0e0bc2f0b0806a8db275cc7b3a2aee93f07b2a8840509a4a3b0dda063e5977f34f3",
          "sha256": "65a100f3304311307f4ebd749da826455570fced2e3dded7bada04d1adfb94b2",
          "sha1": "aea56ae3ef43b3ab60c1d3fcc6af872edba4b76b",
          "md5": "44de310d009990926aa51ee1bac8562b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "6.10.0.202406032230-r"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.4.14"
          }
        }
      ],
      "files": [
        {
          "name": "Orbit-0.2.0.jar",
          "url": "Orbit-0.2.0.jar",
          "size": 6623213,
          "sha512": "b191a1a9d60d0a54b0b6e7f89f73a6804b4808c7e3a8e969bd242065a692a0e0bc2f0b0806a8db275cc7b3a2aee93f07b2a8840509a4a3b0dda063e5977f34f3",
          "sha256": "65a100f3304311307f4ebd749da826455570fced2e3dded7bada04d1adfb94b2",
          "sha1": "aea56ae3ef43b3ab60c1d3fcc6af872edba4b76b",
          "md5": "44de310d009990926aa51ee1bac8562b"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "Orbit-0.2.0.jar",
          "url": "Orbit-0.2.0.jar",
          "size": 6623213,
          "sha512": "b191a1a9d60d0a54b0b6e7f89f73a6804b4808c7e3a8e969bd242065a692a0e0bc2f0b0806a8db275cc7b3a2aee93f07b2a8840509a4a3b0dda063e5977f34f3",
          "sha256": "65a100f3304311307f4ebd749da826455570fced2e3dded7bada04d1adfb94b2",
          "sha1": "aea56ae3ef43b3ab60c1d3fcc6af872edba4b76b",
          "md5": "44de310d009990926aa51ee1bac8562b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "Orbit-0.2.0-sources.jar",
          "url": "Orbit-0.2.0-sources.jar",
          "size": 6200,
          "sha512": "79591fae16461bb6186a8db51059f7c404941f8fbbd96e0ea6d01e5d3e9b6cfcd8842d1f6078dc246d102e21ea2ed5b1d02b74df610ce80b00a287ace958a97d",
          "sha256": "64f3db6bc27b16d6e21c9a22d84a2f26233458b6c8cb2f67fc50e0b1f62c7c8f",
          "sha1": "8bb2ec0a270c95f67c3a66709149e89a02724212",
          "md5": "b70153b45636a899da63c9ea25b6edaa"
        }
      ]
    }
  ]
}
