{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectorAPI",
    "version": "0.1.9.1-STABLE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.9.1-STABLE.jar",
          "url": "ConnectorAPI-0.1.9.1-STABLE.jar",
          "size": 30936,
          "sha512": "eb1691d12b99aed97fb62bbe5b7c2725b31f2043670f866f186ea146b646128a3af81aab19410f307dcaed66fdd2d2a81e835426be0315a53a15bbb2969d43fb",
          "sha256": "af09b26fc25e69ed3c57f20ca763fcf9934b5a1c2a85d70eb2b3a6cef7e17410",
          "sha1": "27b355669bff37ff1f786db4cb5fb80a1fe50fd6",
          "md5": "155c604d460395faa9a9297af7365100"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "ConnectorAPI-0.1.9.1-STABLE.jar",
          "url": "ConnectorAPI-0.1.9.1-STABLE.jar",
          "size": 30936,
          "sha512": "eb1691d12b99aed97fb62bbe5b7c2725b31f2043670f866f186ea146b646128a3af81aab19410f307dcaed66fdd2d2a81e835426be0315a53a15bbb2969d43fb",
          "sha256": "af09b26fc25e69ed3c57f20ca763fcf9934b5a1c2a85d70eb2b3a6cef7e17410",
          "sha1": "27b355669bff37ff1f786db4cb5fb80a1fe50fd6",
          "md5": "155c604d460395faa9a9297af7365100"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.9.1-STABLE-sources.jar",
          "url": "ConnectorAPI-0.1.9.1-STABLE-sources.jar",
          "size": 17402,
          "sha512": "28f80c46cf30626a70414fc277a7a97455c5548264696ba08af1575e2fe91c9a14cbb0994a1bcdc37743301d2e3ffcbc97b667b723abe1454419a314720fb0fe",
          "sha256": "469129be81e5e6f1cc9e2099375b626c1be96a1520fd4426528bc4e8052b876c",
          "sha1": "7d6445914ccc2b084f3f806cda1cef966bee890c",
          "md5": "0ca7636c0f84b09913aea3978ecd534d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.9.1-STABLE-javadoc.jar",
          "url": "ConnectorAPI-0.1.9.1-STABLE-javadoc.jar",
          "size": 154364,
          "sha512": "4ec20bdaacb69954e6f56ac87677b06743d03e347383afff298183172ebe608dd2e389c6fd6404865ccf74f8d86cad261fbef511644b6bbc684d5082a9dde5ce",
          "sha256": "1759b81ddbe1c0461f9d16ff20932049101de5e427b084460a9264425ccd471c",
          "sha1": "9150d451accb27431c5d58679a4c82fecc82d7cf",
          "md5": "24abe5734708caae8cda8e4d4d3238e0"
        }
      ]
    }
  ]
}
