{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectLib",
    "version": "0.2.6-STABLE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectLib-0.2.6-STABLE.jar",
          "url": "ConnectLib-0.2.6-STABLE.jar",
          "size": 26010,
          "sha512": "acab274ccec401b350a93f610eaa879caac0163f72485c1861a2e6ed98e901b3963d539814e8dd7a053df2d3af0166296680141f25bcd1b72a0a131684ae9357",
          "sha256": "141b4b4522864ccabbce19f8703966e035e27fd6cd2fcae78d09b378d45d614a",
          "sha1": "ca361e187896b717f0dbab10f691e982e1b0e612",
          "md5": "dc319365cfba6acf83faa4177bed48ea"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "ConnectLib-0.2.6-STABLE.jar",
          "url": "ConnectLib-0.2.6-STABLE.jar",
          "size": 26010,
          "sha512": "acab274ccec401b350a93f610eaa879caac0163f72485c1861a2e6ed98e901b3963d539814e8dd7a053df2d3af0166296680141f25bcd1b72a0a131684ae9357",
          "sha256": "141b4b4522864ccabbce19f8703966e035e27fd6cd2fcae78d09b378d45d614a",
          "sha1": "ca361e187896b717f0dbab10f691e982e1b0e612",
          "md5": "dc319365cfba6acf83faa4177bed48ea"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectLib-0.2.6-STABLE-sources.jar",
          "url": "ConnectLib-0.2.6-STABLE-sources.jar",
          "size": 15744,
          "sha512": "f149f70ea79856f5269bc6ca14d71e38215c20178b112e62589bc0c62fb280f5f5c7c85a4d82732f94b1ec0759cac7f86c913f597f265cc9eb3d84d5db40e5cc",
          "sha256": "0aff40f7b60076d8dcf41f2f47f32c4deda27d94da5e41b773613fd1fe62498c",
          "sha1": "3a07b8aa853a3ceeec1fe1a16f7429dcbe921f89",
          "md5": "15c5e9ca2c8637ac6204bc011bdfd02b"
        }
      ]
    }
  ]
}
