{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectorAPI",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.0.jar",
          "url": "ConnectorAPI-0.1.0.jar",
          "size": 30299789,
          "sha512": "7ea3043e8682a66712403b6447d4c1551765ae5a27e530d8066b45ec0a63374c9d8e650812407e65befe650ef065ccbec71f7689ebed027510123ee9fbd78ad2",
          "sha256": "e78775b6c7d95772ead18b12ce66c9694c994e888dcec43569cdd69f82bfda5b",
          "sha1": "301573cf210a76be8f3f4915bcdf737a08d0494e",
          "md5": "62908d6e1350fb8dacfe7c2374a293e1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-base",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-base",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-graphics",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-graphics",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-controls",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-controls",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-fxml",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-fxml",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "ConnectorAPI-0.1.0.jar",
          "url": "ConnectorAPI-0.1.0.jar",
          "size": 30299789,
          "sha512": "7ea3043e8682a66712403b6447d4c1551765ae5a27e530d8066b45ec0a63374c9d8e650812407e65befe650ef065ccbec71f7689ebed027510123ee9fbd78ad2",
          "sha256": "e78775b6c7d95772ead18b12ce66c9694c994e888dcec43569cdd69f82bfda5b",
          "sha1": "301573cf210a76be8f3f4915bcdf737a08d0494e",
          "md5": "62908d6e1350fb8dacfe7c2374a293e1"
        }
      ]
    }
  ]
}
