{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectorAPI",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.0.jar",
          "url": "ConnectorAPI-0.1.0.jar",
          "size": 21530,
          "sha512": "892c3f0a2a5619b09a000d23b246ac4c29231a460b107b458841daff78d2b55f5edd2f2637297a1bd1674180e5adac6faf1d1f1feea6a0f9a205d1981521c96f",
          "sha256": "fd975e93eafcaa349c4b5ca1a28fa62920f6a3465d961b5da8542031ae5b4507",
          "sha1": "ec73b1967b343be0162cd28a8997d7ad9a865c73",
          "md5": "21d1c04fd1604470a8c7642347ac6331"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-base",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-base",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-graphics",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-graphics",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-controls",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-controls",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-fxml",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-fxml",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "ConnectorAPI-0.1.0.jar",
          "url": "ConnectorAPI-0.1.0.jar",
          "size": 21530,
          "sha512": "892c3f0a2a5619b09a000d23b246ac4c29231a460b107b458841daff78d2b55f5edd2f2637297a1bd1674180e5adac6faf1d1f1feea6a0f9a205d1981521c96f",
          "sha256": "fd975e93eafcaa349c4b5ca1a28fa62920f6a3465d961b5da8542031ae5b4507",
          "sha1": "ec73b1967b343be0162cd28a8997d7ad9a865c73",
          "md5": "21d1c04fd1604470a8c7642347ac6331"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.0-sources.jar",
          "url": "ConnectorAPI-0.1.0-sources.jar",
          "size": 12740,
          "sha512": "f2ef64ec71824e788930c10816de36876c7ae9d6d25ef5ea83b7033237acfcee9e9fc427641e4818e5b11d3f9f0d3c437d855fa744e2bb2722039fc90c01952e",
          "sha256": "7dffc94773ff78061c95db32f99bfaae2efe8e9a715fefc477d49bf500a051f4",
          "sha1": "4836e260ccf3154022f5b4afdb08be0a55cc82ba",
          "md5": "bfda74344886c2609154881095054a40"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.0-javadoc.jar",
          "url": "ConnectorAPI-0.1.0-javadoc.jar",
          "size": 135395,
          "sha512": "192556b704a57243e872c202075c3454c0f0ce7baa62ef39062ec581d798409f30874369bf40ec816fbd4f60cb75c540dced10194113f487e9a8cd6fc06e99f6",
          "sha256": "a267c3ae51e1d9356502eda88903803f5604cb85ff5b6fd61be3505fe19d60ff",
          "sha1": "65a9aa11a691600295cb7f6d7e9646142e3bbd1c",
          "md5": "c951f8ce3a49b2c63059c733b93fa2a5"
        }
      ]
    }
  ]
}
