{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectorAPI",
    "version": "0.1.3.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.3-SNAPSHOT.jar",
          "url": "ConnectorAPI-0.1.3.3-SNAPSHOT.jar",
          "size": 25886,
          "sha512": "62cf89955699b3a7cc314047da80bad012b541c86b560f56c9ea9029c72c8637a3d595ada35db55312c9103336b08cebe94f4bbf320598f9048e2ee9c2919495",
          "sha256": "37883aaf549fd3c1848e8d02374b5a284916192edf8666d553e747da674a3988",
          "sha1": "84acc050ef795af75d434607c46cddea12a206fc",
          "md5": "1580b1e45a94b59405275a16b66f2665"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-base",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-base",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-graphics",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-graphics",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-controls",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-controls",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-fxml",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-fxml",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.3-SNAPSHOT.jar",
          "url": "ConnectorAPI-0.1.3.3-SNAPSHOT.jar",
          "size": 25886,
          "sha512": "62cf89955699b3a7cc314047da80bad012b541c86b560f56c9ea9029c72c8637a3d595ada35db55312c9103336b08cebe94f4bbf320598f9048e2ee9c2919495",
          "sha256": "37883aaf549fd3c1848e8d02374b5a284916192edf8666d553e747da674a3988",
          "sha1": "84acc050ef795af75d434607c46cddea12a206fc",
          "md5": "1580b1e45a94b59405275a16b66f2665"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.3-SNAPSHOT-sources.jar",
          "url": "ConnectorAPI-0.1.3.3-SNAPSHOT-sources.jar",
          "size": 14917,
          "sha512": "00aad0be1aaa01c4bf050162be8ef545a940c8fe5f74f2a01e48187a7f4b36ea90bda7255052f6e037e550e42198d20bd3cf06dca6b0f5873de2c1cb29e3fae0",
          "sha256": "101415a652bf9fc914ecf32fa56eaa51cabbf3fa3f1e4d63dd8cd37e8a67ef7e",
          "sha1": "a8b0939a3bcdf2bd52ded9e336c90228b4995c78",
          "md5": "9484df559bdfa4091f8bea358dfebadf"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.3-SNAPSHOT-javadoc.jar",
          "url": "ConnectorAPI-0.1.3.3-SNAPSHOT-javadoc.jar",
          "size": 145896,
          "sha512": "5a180fdef74f01e78cad35b3e453b8aca763b7c5ea4ad699a0157c315619dc6708450ad23d0d582ae26e3d8125feb5c82cde11ae7f26c460483c4160f22bd0ed",
          "sha256": "3d67752875535e3bc2844987f0ff4ed76b811210aec2eec837a06828cccc3c38",
          "sha1": "74b6ceed1f188a4d415241c30c2d62470024c354",
          "md5": "a57b29120c8e61d57b7504a8c22a7205"
        }
      ]
    }
  ]
}
