{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectLib",
    "version": "0.4.0-STABLE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectLib-0.4.0-STABLE.jar",
          "url": "ConnectLib-0.4.0-STABLE.jar",
          "size": 65462,
          "sha512": "12fb42ca3bb3eebe811bf12c7fcf719bd0fa0a7360e5faac00ef6957c1ab17d98d728338704f01829b3ddfdf5746629403403ca1aead264129a86862735c0417",
          "sha256": "15e7e96c230a0cb0af55b303638af960c8b870dc23f55d7b256b88abf1cc09f4",
          "sha1": "815c4dd713db74db701ffead1d5b7d9478c9fcb6",
          "md5": "4bdd958bbdc0ace94e810299eaba5796"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "ConnectLib-0.4.0-STABLE.jar",
          "url": "ConnectLib-0.4.0-STABLE.jar",
          "size": 65462,
          "sha512": "12fb42ca3bb3eebe811bf12c7fcf719bd0fa0a7360e5faac00ef6957c1ab17d98d728338704f01829b3ddfdf5746629403403ca1aead264129a86862735c0417",
          "sha256": "15e7e96c230a0cb0af55b303638af960c8b870dc23f55d7b256b88abf1cc09f4",
          "sha1": "815c4dd713db74db701ffead1d5b7d9478c9fcb6",
          "md5": "4bdd958bbdc0ace94e810299eaba5796"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectLib-0.4.0-STABLE-sources.jar",
          "url": "ConnectLib-0.4.0-STABLE-sources.jar",
          "size": 39949,
          "sha512": "723e33d2c77f103371505ac74fb9b2440193a5fd868846d602fb8ec1d6d9a2744edeb6eb63b31aabcbb0a531d04d304c47c55433350a4989c6cbc5ce8fe7f636",
          "sha256": "d63b17878dcd285909ae00e3af71b571b75b4e3125d8609b2fb483204d04262c",
          "sha1": "ad8772440b2b56d217fd8cf91c6dc102bbfbb743",
          "md5": "4fde8c2c43688c00d9a8114976afdb48"
        }
      ]
    }
  ]
}
