{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectLib",
    "version": "0.3.8-STABLE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectLib-0.3.8-STABLE.jar",
          "url": "ConnectLib-0.3.8-STABLE.jar",
          "size": 52841,
          "sha512": "54b3e0cfcbc9fb14db4864b334654873967c3a7bff94f86655b1d9b96b8b2fc82e1351ed6c0492b996d3449b084200359e42035945b167ac71145e8afe4df4a1",
          "sha256": "9ed6fdb01ecf233e08a50fdf7950efc67228065e50ef19a5c5cdb811cd1956cc",
          "sha1": "8fba2d4c1f18a03213b41ac5d1ba586433535604",
          "md5": "fcb1f1c754756e9cbb087f5361f07585"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "ConnectLib-0.3.8-STABLE.jar",
          "url": "ConnectLib-0.3.8-STABLE.jar",
          "size": 52841,
          "sha512": "54b3e0cfcbc9fb14db4864b334654873967c3a7bff94f86655b1d9b96b8b2fc82e1351ed6c0492b996d3449b084200359e42035945b167ac71145e8afe4df4a1",
          "sha256": "9ed6fdb01ecf233e08a50fdf7950efc67228065e50ef19a5c5cdb811cd1956cc",
          "sha1": "8fba2d4c1f18a03213b41ac5d1ba586433535604",
          "md5": "fcb1f1c754756e9cbb087f5361f07585"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectLib-0.3.8-STABLE-sources.jar",
          "url": "ConnectLib-0.3.8-STABLE-sources.jar",
          "size": 29680,
          "sha512": "2b150cfb7e882e6daa6819004c0e356b4b7b55646d44bd37b42dc00ae03f50ff8df7532907d4611b6b60f09e8257281b5978fe9659ac745dc06cef2f19900edf",
          "sha256": "862805507bdcd178f0d8d21ccad7129c16936c31fb1b577e683ce9c1061b556c",
          "sha1": "6c9d6f4ae0910bd7ddc014346599f8f1d3b898e7",
          "md5": "47f12a30c8ebfcda0b87ed21a5ec2dca"
        }
      ]
    }
  ]
}
