{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectLib",
    "version": "0.3.8-STABLE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectLib-0.3.8-STABLE.jar",
          "url": "ConnectLib-0.3.8-STABLE.jar",
          "size": 52841,
          "sha512": "0a7825640ea569c68328968da07fe50a7f975983fae9a4b72edd5ba8117502bccfa45ca952d694c24c9f741754321c11dfee1a56f2e6a4919b91ee08fad293b7",
          "sha256": "555a135e357c600cf333f88ff8b242484fdcbe5373b17e6bf44ebf85d5b438ac",
          "sha1": "1615def5bf3ac81c19e841e216b7782152a34134",
          "md5": "2ea8b33cebdeb870731fa261a0aed75f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "ConnectLib-0.3.8-STABLE.jar",
          "url": "ConnectLib-0.3.8-STABLE.jar",
          "size": 52841,
          "sha512": "0a7825640ea569c68328968da07fe50a7f975983fae9a4b72edd5ba8117502bccfa45ca952d694c24c9f741754321c11dfee1a56f2e6a4919b91ee08fad293b7",
          "sha256": "555a135e357c600cf333f88ff8b242484fdcbe5373b17e6bf44ebf85d5b438ac",
          "sha1": "1615def5bf3ac81c19e841e216b7782152a34134",
          "md5": "2ea8b33cebdeb870731fa261a0aed75f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectLib-0.3.8-STABLE-sources.jar",
          "url": "ConnectLib-0.3.8-STABLE-sources.jar",
          "size": 29680,
          "sha512": "1fdb2bbe0cc43dd19c9a03433fc2868f4cf9d6bd2865339216c883587c720fa48015419b78ee52398bbb8cf62503a6e24c7115d4527f127a4481ceb9c67e4a0e",
          "sha256": "2aa88efe467903ea034c4d59f11d66222f51dbe97fcbdee12bde5b052ce6bcb4",
          "sha1": "bbefb3374e81190dacfddcd287424dd52ca92e32",
          "md5": "844acdc64b04c54a1507035f22fa5643"
        }
      ]
    }
  ]
}
