{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectLib",
    "version": "0.3.8-STABLE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectLib-0.3.8-STABLE.jar",
          "url": "ConnectLib-0.3.8-STABLE.jar",
          "size": 52841,
          "sha512": "997e66e1c4d5aae26f181d169fa09593282807a5ef8e2e1170c5856779829a975ce0787f83d7d92e5ff746f33a556b60bb8b7c40ec1314dce30cbb59ec884845",
          "sha256": "2e848c6fa0acfa14ffa55bf23e0f4ef15b97c43beaaf9f30bfe99105b75a9521",
          "sha1": "59187108fe641e7bf060ff4d9b490b50348a4f74",
          "md5": "33b6b1e723ca4ac45332b7770071bf75"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "ConnectLib-0.3.8-STABLE.jar",
          "url": "ConnectLib-0.3.8-STABLE.jar",
          "size": 52841,
          "sha512": "997e66e1c4d5aae26f181d169fa09593282807a5ef8e2e1170c5856779829a975ce0787f83d7d92e5ff746f33a556b60bb8b7c40ec1314dce30cbb59ec884845",
          "sha256": "2e848c6fa0acfa14ffa55bf23e0f4ef15b97c43beaaf9f30bfe99105b75a9521",
          "sha1": "59187108fe641e7bf060ff4d9b490b50348a4f74",
          "md5": "33b6b1e723ca4ac45332b7770071bf75"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectLib-0.3.8-STABLE-sources.jar",
          "url": "ConnectLib-0.3.8-STABLE-sources.jar",
          "size": 29680,
          "sha512": "6ec4a63237a95021cd4010b07b7d51ebfee3b12adb6f6f4b276defe45b12fe3cf5894f0d34e22b1f6a7e05272b58259d4838d4dbccdd909b77b1184f6293e10a",
          "sha256": "3db7641655b5ecdb3aec2e9f99ec21af5ab2ca0705d794c3399d6bc6ecc411db",
          "sha1": "c613d8f34e4c9d1a44302fc5dfcbd5425af6c1fd",
          "md5": "083d1f0e6e283b69f508dd92c1c51565"
        }
      ]
    }
  ]
}
