{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectLib",
    "version": "0.4.3.1-STABLE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectLib-0.4.3.1-STABLE.jar",
          "url": "ConnectLib-0.4.3.1-STABLE.jar",
          "size": 65508,
          "sha512": "e776091371c243ff4525c34bc60c9f0fb05a6f1e9e3725647825c5659cc8c93721e9e29a9aa5a9556bac3ef28a14cce31a26bd468967643c7f6a94a0ce15db92",
          "sha256": "5f2c32c17bbb0baf5d7953a0a7954700a428e871a21548455642c1c4b30051dc",
          "sha1": "346c782a041a1efbc3895f652073512571a42d6f",
          "md5": "3b82cfb300c9b866542bcdd5155f5edf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "ConnectLib-0.4.3.1-STABLE.jar",
          "url": "ConnectLib-0.4.3.1-STABLE.jar",
          "size": 65508,
          "sha512": "e776091371c243ff4525c34bc60c9f0fb05a6f1e9e3725647825c5659cc8c93721e9e29a9aa5a9556bac3ef28a14cce31a26bd468967643c7f6a94a0ce15db92",
          "sha256": "5f2c32c17bbb0baf5d7953a0a7954700a428e871a21548455642c1c4b30051dc",
          "sha1": "346c782a041a1efbc3895f652073512571a42d6f",
          "md5": "3b82cfb300c9b866542bcdd5155f5edf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectLib-0.4.3.1-STABLE-sources.jar",
          "url": "ConnectLib-0.4.3.1-STABLE-sources.jar",
          "size": 39644,
          "sha512": "01cf4ab3cd97dda06dc4169503d3f629caf5f8268ebe4846ab48a56734cd32106414f966fd5f50ae4c426575853c219e530cf7d8400f0f7487bb72a14e114f5b",
          "sha256": "d88948915dfcce3dad4578cd3d8793b2ad586d7044f7fe42480140ea4517e030",
          "sha1": "c214df6bb021377ad1bb2f8a3fa13e218039e407",
          "md5": "257de1e6ee2569ae02db50025196d7fc"
        }
      ]
    }
  ]
}
