{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectLib",
    "version": "0.4.3.1-STABLE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectLib-0.4.3.1-STABLE.jar",
          "url": "ConnectLib-0.4.3.1-STABLE.jar",
          "size": 65508,
          "sha512": "085b555f646c450853cf9741767b4bccea878b23aa62f662d8a36126fcb431d2e8a3ce87be27b6d8cafae5ac8a65ede53150fb3ca2ce28a9c4546ec2797ae6d1",
          "sha256": "237c7566f5d642437192956da84b957ff5a7b5df6c836b1b95b99913456e13de",
          "sha1": "1362e07e3e5c7bda7c6b75dcb8b86687c4dd611c",
          "md5": "ca60aa294d8dda899256765e933cbab0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "ConnectLib-0.4.3.1-STABLE.jar",
          "url": "ConnectLib-0.4.3.1-STABLE.jar",
          "size": 65508,
          "sha512": "085b555f646c450853cf9741767b4bccea878b23aa62f662d8a36126fcb431d2e8a3ce87be27b6d8cafae5ac8a65ede53150fb3ca2ce28a9c4546ec2797ae6d1",
          "sha256": "237c7566f5d642437192956da84b957ff5a7b5df6c836b1b95b99913456e13de",
          "sha1": "1362e07e3e5c7bda7c6b75dcb8b86687c4dd611c",
          "md5": "ca60aa294d8dda899256765e933cbab0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectLib-0.4.3.1-STABLE-sources.jar",
          "url": "ConnectLib-0.4.3.1-STABLE-sources.jar",
          "size": 39644,
          "sha512": "2fb23373ffdaf7a632c23034723dd9c7d74efb1c460e096fdf1d71f7562356d146fa11ed4dd0c7f2bd99cc2f5e78d122d9c8c46253aab80a15137a7880d2ad00",
          "sha256": "63d077752076054db5a756abd5daafcd9e6e9361337467d3b505ea5982f6707a",
          "sha1": "37679e20c8bdaa845cbcc8c1fea0a7fecc122180",
          "md5": "738cb6c382a33e6fcdb9f580dabd512b"
        }
      ]
    }
  ]
}
