{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectLib",
    "version": "0.4.3.1-STABLE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectLib-0.4.3.1-STABLE.jar",
          "url": "ConnectLib-0.4.3.1-STABLE.jar",
          "size": 65508,
          "sha512": "5b02e112e9b545524ccfc20ae073b0790defa4c64e2bc515f7632498bcb91495c87874537bdf7b252ac8e69949e0e8885814642e79080a8458cf144351741f99",
          "sha256": "d7c557224e4f912f8984d1a5be11d47ee36668268106f8198b8ef49d29eea293",
          "sha1": "887ccd7f2fecb915f4e5a1184b739c85753a20d6",
          "md5": "5eb8db1504ab747cfa1cddcce667cd24"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "ConnectLib-0.4.3.1-STABLE.jar",
          "url": "ConnectLib-0.4.3.1-STABLE.jar",
          "size": 65508,
          "sha512": "5b02e112e9b545524ccfc20ae073b0790defa4c64e2bc515f7632498bcb91495c87874537bdf7b252ac8e69949e0e8885814642e79080a8458cf144351741f99",
          "sha256": "d7c557224e4f912f8984d1a5be11d47ee36668268106f8198b8ef49d29eea293",
          "sha1": "887ccd7f2fecb915f4e5a1184b739c85753a20d6",
          "md5": "5eb8db1504ab747cfa1cddcce667cd24"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectLib-0.4.3.1-STABLE-sources.jar",
          "url": "ConnectLib-0.4.3.1-STABLE-sources.jar",
          "size": 39644,
          "sha512": "e2efa656667254092c05e346218061d2818a322b9dcc73f893f7fa3443061e67ed1d0021514dbc8e99207c4ca632367702821285e179893c044e89a297aa0870",
          "sha256": "92235d496766bccfb4e110d3ee3639606314b979feb70ef9d313232c0cc0e090",
          "sha1": "da7fbbbe86aa6e7bba21bc01ac77c07fec4a7780",
          "md5": "384e0e06dafc2d77e75f7dd3b09bc5f9"
        }
      ]
    }
  ]
}
