{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectorAPI",
    "version": "0.1.3.12-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.12-SNAPSHOT.jar",
          "url": "ConnectorAPI-0.1.3.12-SNAPSHOT.jar",
          "size": 29297,
          "sha512": "53d0a181b687edfb28af3c3f7a1a78615fcfa8115b062e0fb21b1a907f94b4f5c62718aff66d3a92f29c3bd9aae7acb9460d24df1f77849e096c33f0baf9f6ec",
          "sha256": "1596c3ca8400c8e4b270a1205019da16027a505921902613deae0501a00dd795",
          "sha1": "d0a8b9ca35d42e714fa65c689ceb8bce0e66f228",
          "md5": "17b41fb354108fd6ee0d98f32a089824"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-base",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-base",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-graphics",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-graphics",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-controls",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-controls",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-fxml",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-fxml",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.12-SNAPSHOT.jar",
          "url": "ConnectorAPI-0.1.3.12-SNAPSHOT.jar",
          "size": 29297,
          "sha512": "53d0a181b687edfb28af3c3f7a1a78615fcfa8115b062e0fb21b1a907f94b4f5c62718aff66d3a92f29c3bd9aae7acb9460d24df1f77849e096c33f0baf9f6ec",
          "sha256": "1596c3ca8400c8e4b270a1205019da16027a505921902613deae0501a00dd795",
          "sha1": "d0a8b9ca35d42e714fa65c689ceb8bce0e66f228",
          "md5": "17b41fb354108fd6ee0d98f32a089824"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.12-SNAPSHOT-sources.jar",
          "url": "ConnectorAPI-0.1.3.12-SNAPSHOT-sources.jar",
          "size": 17225,
          "sha512": "f231031eabc010bac86aec08d50f3a06599cca24497972926c58837102f3347b913dd485eb7ed2263cf1156890a8264a7ce104be7a428ecb98657ce349d24c70",
          "sha256": "803c836c05aa63ecf3513c52d1e84e9def61b881153f2ca772282dca9b6c661a",
          "sha1": "62562bb94ae69bd0bf11c2dbf810ada87f6ab08f",
          "md5": "15e6020dd4213c41522ba74beeaf5f20"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.12-SNAPSHOT-javadoc.jar",
          "url": "ConnectorAPI-0.1.3.12-SNAPSHOT-javadoc.jar",
          "size": 152527,
          "sha512": "2bf11454e6cf6be6a77211a7cc40141d4a3475a08f8b66d2e380afe7715a02b74bfd571d5d18a6ce87f86387333595b5d125fd5d63bc7f1c735b65c50c0fb1b8",
          "sha256": "f11acc07e1aa6c11b94f6cae0bb08e515225f334831ee1f299287d2f703ce9d3",
          "sha1": "1e7020e3e5d5d95c2bfb9615a9aef30ef26b9a81",
          "md5": "29c369c07d0ae42fb0c868dd8b658fc5"
        }
      ]
    }
  ]
}
