{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectorAPI",
    "version": "0.1.3.1-Alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.1-Alpha.jar",
          "url": "ConnectorAPI-0.1.3.1-Alpha.jar",
          "size": 25646,
          "sha512": "68aab556443c21a6e2e417ae20be9c4b1240359b9d31659fc290cf7980557332a1b79d0c8bd27269c8cf7d53ebdef56a3a3d7320c7e71c16a929edf2a7f178cc",
          "sha256": "1bd4234fd89b66da334f71c21450f7b4036f456d656c66df150ff29b960bf45a",
          "sha1": "6996b804329d74d46da092902f1f6ba570b87a6a",
          "md5": "08d225e4523f17491c0e0ea3c350e4aa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-base",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-base",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-graphics",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-graphics",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-controls",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-controls",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-fxml",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-fxml",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.1-Alpha.jar",
          "url": "ConnectorAPI-0.1.3.1-Alpha.jar",
          "size": 25646,
          "sha512": "68aab556443c21a6e2e417ae20be9c4b1240359b9d31659fc290cf7980557332a1b79d0c8bd27269c8cf7d53ebdef56a3a3d7320c7e71c16a929edf2a7f178cc",
          "sha256": "1bd4234fd89b66da334f71c21450f7b4036f456d656c66df150ff29b960bf45a",
          "sha1": "6996b804329d74d46da092902f1f6ba570b87a6a",
          "md5": "08d225e4523f17491c0e0ea3c350e4aa"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.1-Alpha-sources.jar",
          "url": "ConnectorAPI-0.1.3.1-Alpha-sources.jar",
          "size": 14551,
          "sha512": "e3fa5a1bafb569ee21946c90c60ae4fc70bb7ae6c295d44b24c3dc3b186cd3c497ca04cad1030c67048a47a8baf99d65a5e8cd1b6cbbf67783c087ca5b59aa5a",
          "sha256": "d6ecef9a0a3627494ed27b431f185511b02ee48c5e19b91d1061bbe3f791ff04",
          "sha1": "387e221aee5eddf6e6ada60bf9aa3b3a33010b69",
          "md5": "ed0f0f8f9866089df578fb00806b2c31"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.1-Alpha-javadoc.jar",
          "url": "ConnectorAPI-0.1.3.1-Alpha-javadoc.jar",
          "size": 145356,
          "sha512": "efed5a6fb9e1f2d5319f35f18b293e7a91c6fe58bff1795a2f7f790b98d83a97c324e08bff21b508efcba5146816c1a0ed2623e1bfc2ee55d26ab4efc75a3260",
          "sha256": "f652431a82ec45e59a0c59488ae5b7d7aae530eddf18ed2fb2cf1d799fa68fe4",
          "sha1": "4404850a25871e20def719940818044391db9367",
          "md5": "909e268cb7dfc7df7192630828267089"
        }
      ]
    }
  ]
}
