{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectorAPI",
    "version": "0.1.3.1-Alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.1-Alpha.jar",
          "url": "ConnectorAPI-0.1.3.1-Alpha.jar",
          "size": 25584,
          "sha512": "962358aa01c17d0bf99196749a4b469ce066eb932c89994f184aae654fe72735ae63da595e3c67f7638222fb34d880a1b71ae3ee4762e74693f9eb6f970a4834",
          "sha256": "4492475da27288bb3116d3ba399141c8ec8c7913661b210476be5c786828c815",
          "sha1": "b7fbe86e2dc33afa0a297fa98b4817baa7f059b7",
          "md5": "69b8f51d023c8b4ca761d1eb3757bb86"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-base",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-base",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-graphics",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-graphics",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-controls",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-controls",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-fxml",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-fxml",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.1-Alpha.jar",
          "url": "ConnectorAPI-0.1.3.1-Alpha.jar",
          "size": 25584,
          "sha512": "962358aa01c17d0bf99196749a4b469ce066eb932c89994f184aae654fe72735ae63da595e3c67f7638222fb34d880a1b71ae3ee4762e74693f9eb6f970a4834",
          "sha256": "4492475da27288bb3116d3ba399141c8ec8c7913661b210476be5c786828c815",
          "sha1": "b7fbe86e2dc33afa0a297fa98b4817baa7f059b7",
          "md5": "69b8f51d023c8b4ca761d1eb3757bb86"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.1-Alpha-sources.jar",
          "url": "ConnectorAPI-0.1.3.1-Alpha-sources.jar",
          "size": 14559,
          "sha512": "e6f444cf0f75d6ae054f633f70fe173bca0507aab8d87cf4ded00fb5341db04c2b9079601c8d95f5fdb0b76d1d6d4a164440e19df040d5ebf7af00cff4464b1d",
          "sha256": "594cb9a2bd309d24dacbdec4431540457ee63911a0cdcf9285c67e0509e578ef",
          "sha1": "519942cc85a0676716806ba548a68e11dde81f20",
          "md5": "31ca0b3e4ebcc283e04d9675f3aa735d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.1-Alpha-javadoc.jar",
          "url": "ConnectorAPI-0.1.3.1-Alpha-javadoc.jar",
          "size": 145515,
          "sha512": "c10378249e2cb2bf3adab1d1fb8da34f86ec87ad57e0201162925dca92acfdb225a2b06bd21fa292e7aa16b822a9c253e085d5933c2623a2ea343788381d4423",
          "sha256": "28d7f91857236d760383b82209bbe3232cb85354efcdd79ad3f9a30b704f0994",
          "sha1": "b17fd2162418a862a31893c12773565546697716",
          "md5": "97b0f25b3fc406c975a2235f865e399e"
        }
      ]
    }
  ]
}
