{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectorAPI",
    "version": "0.1.3.1-Alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.1-Alpha.jar",
          "url": "ConnectorAPI-0.1.3.1-Alpha.jar",
          "size": 25584,
          "sha512": "5e845d05da7b4068c6cf193cc8762d38c7f855ba32a9a6c0a097393c66c053a553187524b9f0da5b9cdba7880976a60b72798c9042195459a5f6c84dbe6f3f8f",
          "sha256": "e5fb027c842aa6b9d31cd9d5e7441dfd3391d40f24f2b7adadc9781bd7a77b16",
          "sha1": "119dc37c1956608e0ef267faad47c69dbb0b20b8",
          "md5": "93fe1815a4a35c3a836a3a6e189f434d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-base",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-base",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-graphics",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-graphics",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-controls",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-controls",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-fxml",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-fxml",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.1-Alpha.jar",
          "url": "ConnectorAPI-0.1.3.1-Alpha.jar",
          "size": 25584,
          "sha512": "5e845d05da7b4068c6cf193cc8762d38c7f855ba32a9a6c0a097393c66c053a553187524b9f0da5b9cdba7880976a60b72798c9042195459a5f6c84dbe6f3f8f",
          "sha256": "e5fb027c842aa6b9d31cd9d5e7441dfd3391d40f24f2b7adadc9781bd7a77b16",
          "sha1": "119dc37c1956608e0ef267faad47c69dbb0b20b8",
          "md5": "93fe1815a4a35c3a836a3a6e189f434d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.1-Alpha-sources.jar",
          "url": "ConnectorAPI-0.1.3.1-Alpha-sources.jar",
          "size": 14559,
          "sha512": "cd05a5ca2505c4ecd63eee8ef6113463ca2b24dd2c338135ab3d955104fc93ad783b390271e0ef4c188bf0dea5eaa48bbcea9acd818bfecb211ca3cb7f8cb861",
          "sha256": "d4fbe12450eb3b7704484d0b2beae1ea5a4208560d1e4dbd7635aecfd645057b",
          "sha1": "c3e40b316a8a3332d135f270dd075635b44a5a9c",
          "md5": "6be1e82c260d35be9a731981f95e8c95"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.1-Alpha-javadoc.jar",
          "url": "ConnectorAPI-0.1.3.1-Alpha-javadoc.jar",
          "size": 145515,
          "sha512": "b2cc2db653f266800c863f429effa6a30d7f06b1cd978eb6903b8238e3892369f3bed8786b9bdf5192de9b6348d5af34b656de2e44874b35fddda220c8dec835",
          "sha256": "b88aec86917d3553beedace760dfea1f9003c549b9d00f95693ac7c6630d9eef",
          "sha1": "0f112888c42de716482d01c06aac9a029b2d22d3",
          "md5": "5cb7de2609a59d4668381583357736de"
        }
      ]
    }
  ]
}
