{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectorAPI",
    "version": "0.1.3.7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.7-SNAPSHOT.jar",
          "url": "ConnectorAPI-0.1.3.7-SNAPSHOT.jar",
          "size": 25809,
          "sha512": "cd228c9c01d68c4642ee3f6fd9bde02f7f6d9daea4a5061c4339a9567f12ddb6fd96132fbe2ca725fcb998ceb729afaeedf2c59bf262ca314a1ea3e956ce9528",
          "sha256": "634355cc1ccc03c1ec096fc016ca6ef2d20b64e7b2c107950e289d5443415b4a",
          "sha1": "f3f5555714d0cad9acbf17b969f4197b5d23fd5f",
          "md5": "a97734dfc7028ba8c05bb76095c7d119"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-base",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-base",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-graphics",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-graphics",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-controls",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-controls",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-fxml",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-fxml",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.7-SNAPSHOT.jar",
          "url": "ConnectorAPI-0.1.3.7-SNAPSHOT.jar",
          "size": 25809,
          "sha512": "cd228c9c01d68c4642ee3f6fd9bde02f7f6d9daea4a5061c4339a9567f12ddb6fd96132fbe2ca725fcb998ceb729afaeedf2c59bf262ca314a1ea3e956ce9528",
          "sha256": "634355cc1ccc03c1ec096fc016ca6ef2d20b64e7b2c107950e289d5443415b4a",
          "sha1": "f3f5555714d0cad9acbf17b969f4197b5d23fd5f",
          "md5": "a97734dfc7028ba8c05bb76095c7d119"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.7-SNAPSHOT-sources.jar",
          "url": "ConnectorAPI-0.1.3.7-SNAPSHOT-sources.jar",
          "size": 14922,
          "sha512": "fd44c08d7c38aa3b6a9b7d384f6331c8a270b7c90bf56abb6726d023c121b9aab3412ddc3c6d5cb7bb0c4eb6a294091ab25ae4b83654090f1983900bb5238549",
          "sha256": "01c4a4c2ffe60fd4f6a357fea144d5d481f45206683a9481d5c2a5ba774ff182",
          "sha1": "4aea43940b0cbb73beefb3262b0c8c368e282ec5",
          "md5": "a8649de0c81bb414046b84872d32095b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.7-SNAPSHOT-javadoc.jar",
          "url": "ConnectorAPI-0.1.3.7-SNAPSHOT-javadoc.jar",
          "size": 145743,
          "sha512": "1afa4d9b1eb7aeeb5772e86a5f29323182f12efe9c99d9e226cf19e2c4bd765cd9f23e11435f7220bbe59bdbd4ba68bd62914ee1ffa02a9cc6b1111cf1890751",
          "sha256": "8674385bfbbd66a7dcd51f5660f2137a3f6a774102200de784ef0c38842d9b7f",
          "sha1": "2a7053013200b4513fdb08b85977cf8cf310ee33",
          "md5": "442ae4a62391a0e619ec63cbe6e80907"
        }
      ]
    }
  ]
}
