{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectorAPI",
    "version": "0.1.3.7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.7-SNAPSHOT.jar",
          "url": "ConnectorAPI-0.1.3.7-SNAPSHOT.jar",
          "size": 25808,
          "sha512": "31f9952054d67b19da5e6db9c7009cb87cc02fc176594063254168c65ad40df13943fbf6b7018c981bbc20883a299d9750b9cc11874223daf83b9c4b61d156b4",
          "sha256": "b20bae68962d7cb54df3ff7281fe4eea124518b68ddb3a8efa656a6975f8304e",
          "sha1": "17d34b7b1226e5b4b386f6e8641862f4b63833c0",
          "md5": "20a70060284d43e739fed5ef6f1953a4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-base",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-base",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-graphics",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-graphics",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-controls",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-controls",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-fxml",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-fxml",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.7-SNAPSHOT.jar",
          "url": "ConnectorAPI-0.1.3.7-SNAPSHOT.jar",
          "size": 25808,
          "sha512": "31f9952054d67b19da5e6db9c7009cb87cc02fc176594063254168c65ad40df13943fbf6b7018c981bbc20883a299d9750b9cc11874223daf83b9c4b61d156b4",
          "sha256": "b20bae68962d7cb54df3ff7281fe4eea124518b68ddb3a8efa656a6975f8304e",
          "sha1": "17d34b7b1226e5b4b386f6e8641862f4b63833c0",
          "md5": "20a70060284d43e739fed5ef6f1953a4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.7-SNAPSHOT-sources.jar",
          "url": "ConnectorAPI-0.1.3.7-SNAPSHOT-sources.jar",
          "size": 14906,
          "sha512": "5866594923e2bb555e713b776cad0e56a85de114c98048c1b79d30150cb95cff67aa597b2b2087acbceea8c1f72623dcf5792a6b45a50528cd3468a794ff4f6c",
          "sha256": "1068d2bc074f5c9a5db478d7de9eff4dda3e65a0f004978b80f88cad3031a308",
          "sha1": "71cd532ab5d2c3bfa6b690a99fde791559e81816",
          "md5": "2199e5865e985fa9e2ce006c074db969"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.7-SNAPSHOT-javadoc.jar",
          "url": "ConnectorAPI-0.1.3.7-SNAPSHOT-javadoc.jar",
          "size": 145743,
          "sha512": "fdfb4345017faddfaf057bc16393700cb103250d2372c19d3661f57a5012d159362d36862f0f2e96e2f2b1a31562e95213f0f4788b0513ecdc5431c12fb30f8c",
          "sha256": "b9a03661686899adf8387e29e17230618ae487158308b4a8dcdb66941df25f7b",
          "sha1": "d415a8bad04f5fda91917ece5f0c726fc8101bcc",
          "md5": "eba4e7091ae4972ccdaab0eadbc5d6ee"
        }
      ]
    }
  ]
}
