{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectorAPI",
    "version": "0.2.0-STABLE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.2.0-STABLE.jar",
          "url": "ConnectorAPI-0.2.0-STABLE.jar",
          "size": 25219,
          "sha512": "e508f2a0fcc5041e52fec5da8e392383c32f074b4c7ef020078db42edea44a75b16a045a73f1e05657598919e9afdf06d19e8da05aa5cf9fffb055db5fe9b5cf",
          "sha256": "bb1aec40f3467ff5b4d45ef7939b08b2826d16de52ac26b9bbcfb955c0a601f5",
          "sha1": "0bafd3fb7e5331a2a6ba2a259142ec34727fea9d",
          "md5": "fb25a9ce2b469024853d7ff164143a61"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "ConnectorAPI-0.2.0-STABLE.jar",
          "url": "ConnectorAPI-0.2.0-STABLE.jar",
          "size": 25219,
          "sha512": "e508f2a0fcc5041e52fec5da8e392383c32f074b4c7ef020078db42edea44a75b16a045a73f1e05657598919e9afdf06d19e8da05aa5cf9fffb055db5fe9b5cf",
          "sha256": "bb1aec40f3467ff5b4d45ef7939b08b2826d16de52ac26b9bbcfb955c0a601f5",
          "sha1": "0bafd3fb7e5331a2a6ba2a259142ec34727fea9d",
          "md5": "fb25a9ce2b469024853d7ff164143a61"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.2.0-STABLE-sources.jar",
          "url": "ConnectorAPI-0.2.0-STABLE-sources.jar",
          "size": 14830,
          "sha512": "c6cd7bf109b26809e0f7ad54816b7e049dab575d8f48bffc134c6f73ec9b213be8657b41f5728a548c318fff7e2aafe6d891a61fa8798c197eba73c3f380d254",
          "sha256": "2fa411731c04cc71cf2bcbba8ebb48d4b3615987d29ca303da5f86a5bdeca72e",
          "sha1": "c5f66e874a7bf3738c804fa87120af18af4d2474",
          "md5": "f1238de0ef7f224338a78fc6fff0a18d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.2.0-STABLE-javadoc.jar",
          "url": "ConnectorAPI-0.2.0-STABLE-javadoc.jar",
          "size": 147240,
          "sha512": "4f8f22b627cf353e9501a28df00d5ebb7068b468f08fc08217735a4cc9eb18e755a4c893b5cdd6d8bf1ffe09f3df12ab0f391798608755cc2952328bc1290383",
          "sha256": "877ac8c1879d3734270d2b0dd92b39648cf5f4ce79db1d07acc8846b80f03113",
          "sha1": "d45acc35662d791b9337fdbe54172a70a95f01b6",
          "md5": "d9c9b8405d73861393f901217a5d55ee"
        }
      ]
    }
  ]
}
