{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectorAPI",
    "version": "0.1.5-STABLE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.5-STABLE.jar",
          "url": "ConnectorAPI-0.1.5-STABLE.jar",
          "size": 25475,
          "sha512": "165f9c41bfe558bd02791a31b1b9d2baae76538558a1a0a432437910614bf351ed8e905255caadcf0f263b0568195d4db037a447f19bfd2248ab0cb74eb845b6",
          "sha256": "0bbdb54cc6df4a1368bea51fefc551ccaf20f42cb79ca89af1e4f781e1fbb062",
          "sha1": "e9f0cc4af8df5493aa1a860da1d566ba1d5bb9c7",
          "md5": "a2b3495529f3cd7eea34b11c90339be0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-base",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-base",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-graphics",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-graphics",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-controls",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-controls",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-fxml",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-fxml",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "ConnectorAPI-0.1.5-STABLE.jar",
          "url": "ConnectorAPI-0.1.5-STABLE.jar",
          "size": 25475,
          "sha512": "165f9c41bfe558bd02791a31b1b9d2baae76538558a1a0a432437910614bf351ed8e905255caadcf0f263b0568195d4db037a447f19bfd2248ab0cb74eb845b6",
          "sha256": "0bbdb54cc6df4a1368bea51fefc551ccaf20f42cb79ca89af1e4f781e1fbb062",
          "sha1": "e9f0cc4af8df5493aa1a860da1d566ba1d5bb9c7",
          "md5": "a2b3495529f3cd7eea34b11c90339be0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.5-STABLE-sources.jar",
          "url": "ConnectorAPI-0.1.5-STABLE-sources.jar",
          "size": 14630,
          "sha512": "b28cd90ec4beb96e1dc105fd095586d118306d4f8b9a2e46edfdbfb026a0f0a82aa3d302b3554e14eb0b4c7425477da06bb8471bd5ac3ec709f48d7e9b59d9c2",
          "sha256": "d90937433b998aca6de75d1b9025acc43b9339059d0b8fdcd27f88c56fcdcc03",
          "sha1": "151a7f923dd666e09bca75cc3f5348f62b27a34a",
          "md5": "1912a851fd7790dbb6898d89ec01e8bf"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.5-STABLE-javadoc.jar",
          "url": "ConnectorAPI-0.1.5-STABLE-javadoc.jar",
          "size": 145059,
          "sha512": "20db661272f11219668f6139e9d471602f22ea671fc6349d609f093c5a78d67255d0a9a78de02cfc14202b8c91732850b0b737facac63d3206a8120a96029e37",
          "sha256": "130bfad5aa4562259338c4c0c7cbf5dae33d54665d90a5245cfea7447c181029",
          "sha1": "deffbbf7ee6c5663614a51c69209384a3405d080",
          "md5": "e1ca59f202faf6bebd6a72cba43d9150"
        }
      ]
    }
  ]
}
