{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectorAPI",
    "version": "0.1.5-STABLE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.5-STABLE.jar",
          "url": "ConnectorAPI-0.1.5-STABLE.jar",
          "size": 25740,
          "sha512": "0e49d7f5bd66711e88665104d350776bd007692c39a8ba5a8eebf87f59b4405a8d42ee1a05a31af0ec4990d12f2e95856055e67d8fe47068b8bcd954c10a141f",
          "sha256": "f840200e5434ef01202cd969e47b9daccfb4c8a47bac454f06308d415e609738",
          "sha1": "80541cad425f05edf62e943f7d9d3812e2cc9e07",
          "md5": "87ecfa65536df2c0d8b3af1e6a38b229"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-base",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-base",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-graphics",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-graphics",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-controls",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-controls",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-fxml",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-fxml",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "ConnectorAPI-0.1.5-STABLE.jar",
          "url": "ConnectorAPI-0.1.5-STABLE.jar",
          "size": 25740,
          "sha512": "0e49d7f5bd66711e88665104d350776bd007692c39a8ba5a8eebf87f59b4405a8d42ee1a05a31af0ec4990d12f2e95856055e67d8fe47068b8bcd954c10a141f",
          "sha256": "f840200e5434ef01202cd969e47b9daccfb4c8a47bac454f06308d415e609738",
          "sha1": "80541cad425f05edf62e943f7d9d3812e2cc9e07",
          "md5": "87ecfa65536df2c0d8b3af1e6a38b229"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.5-STABLE-sources.jar",
          "url": "ConnectorAPI-0.1.5-STABLE-sources.jar",
          "size": 14656,
          "sha512": "2b0de02d758003c0e3ada2951b6d6f9cf86cb9c90bcd0693dbec0b98e8efd0e198855936b5e58dfb7f9c7d7ebe32d2f3b762cde4734d0963fc10d928febecda2",
          "sha256": "b02bfff70bd828ab0f982867e2739bb3c1f77bb0f3cc6a6fa7cc6b3e0094a9db",
          "sha1": "c5ce2d7c4e34066d9fcdb8352f62175f5cf9ce87",
          "md5": "5887dcf061f2cf6009a88054777ef617"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.5-STABLE-javadoc.jar",
          "url": "ConnectorAPI-0.1.5-STABLE-javadoc.jar",
          "size": 145204,
          "sha512": "269b56ae7b9b935eb6228d1dc0f49c87c84716c5c35201e6db68cdf5cbb230447da71640ebaa3d4527775e4aa08fd35cc645ecccfa9501671def559f06dc450c",
          "sha256": "6299d31c8c8f9124211e65ec6616fb66e6966e04f8d2525b43685d371103b6cf",
          "sha1": "7402cdb1b92c721c5d3c626e6cc3a834a86d6678",
          "md5": "505739bb08d9017cc24e3a9e91d487a9"
        }
      ]
    }
  ]
}
