{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectorAPI",
    "version": "0.1.5-STABLE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.5-STABLE.jar",
          "url": "ConnectorAPI-0.1.5-STABLE.jar",
          "size": 25740,
          "sha512": "5699109cbbee18ce2b90fb15b99eae6707acc308919a5fe67d3b50a6d3850f76c82e71c1d2c42e981984b3a3dd133ee7e6f3a49e3ce520f32a8c0b8a943cb22a",
          "sha256": "77680492cbed4694539624eeab215ea63e28f56b13552e8f0de3518167a5d5be",
          "sha1": "2fbbe20db76bc4c1b5068b1caede63d24805822c",
          "md5": "7d6554412d1919909edc2d4b0f9d88fc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-base",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-base",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-graphics",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-graphics",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-controls",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-controls",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-fxml",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-fxml",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "ConnectorAPI-0.1.5-STABLE.jar",
          "url": "ConnectorAPI-0.1.5-STABLE.jar",
          "size": 25740,
          "sha512": "5699109cbbee18ce2b90fb15b99eae6707acc308919a5fe67d3b50a6d3850f76c82e71c1d2c42e981984b3a3dd133ee7e6f3a49e3ce520f32a8c0b8a943cb22a",
          "sha256": "77680492cbed4694539624eeab215ea63e28f56b13552e8f0de3518167a5d5be",
          "sha1": "2fbbe20db76bc4c1b5068b1caede63d24805822c",
          "md5": "7d6554412d1919909edc2d4b0f9d88fc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.5-STABLE-sources.jar",
          "url": "ConnectorAPI-0.1.5-STABLE-sources.jar",
          "size": 14656,
          "sha512": "5904c807640479b8718aaa1b7a4b3abafa6944fb9dafb6e843bea619f741fe77269b64723c07fd1c31eefc40bc40ccf39325457836a4d380f5d1744c8a4d46a4",
          "sha256": "d7f2bafe3fba2815c1b0af148a124503cb38ff40fde38ae967798d11ab4e9117",
          "sha1": "fc9b38b2e49d0a2eb82d3f70aac3614633cd9e49",
          "md5": "7231e05c76d77c3c470ec9328c6c63e0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.5-STABLE-javadoc.jar",
          "url": "ConnectorAPI-0.1.5-STABLE-javadoc.jar",
          "size": 145204,
          "sha512": "37fddf50b00718e2bc319a53533ce33e2d7c1cc00bc6e9e7bd51ebce11b777dabce2764d74009ef8330c675ca72d17b8e882350a930ed0e7a48704140c0ae0da",
          "sha256": "eb52acd85533e093706b90f8379927d7fe936efc9d9ae4457146169d69acdf4f",
          "sha1": "d2ea66430b3d95ea0480198b275731cc2ee5ce43",
          "md5": "07f1dd4eb42b427e393b314a06191bea"
        }
      ]
    }
  ]
}
