{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectorAPI",
    "version": "0.1.8-STABLE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.8-STABLE.jar",
          "url": "ConnectorAPI-0.1.8-STABLE.jar",
          "size": 30263,
          "sha512": "2032b6b14e952347e5cef18c1104046cb97b24c574efa4cd3d5f21658a502d0c83a2a0d1af1a0118cb25759cc1cc901af8cf59f4798ed0179207dbb9279c5486",
          "sha256": "27f4258bfaf1c3aa45005e9394a411f3a23a8fc5fa525071ebd1bfefdeef264c",
          "sha1": "df1c5c97db080de86295bf948ad196576b157146",
          "md5": "bc8895072afc180999c29d6300b2e2f8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "ConnectorAPI-0.1.8-STABLE.jar",
          "url": "ConnectorAPI-0.1.8-STABLE.jar",
          "size": 30263,
          "sha512": "2032b6b14e952347e5cef18c1104046cb97b24c574efa4cd3d5f21658a502d0c83a2a0d1af1a0118cb25759cc1cc901af8cf59f4798ed0179207dbb9279c5486",
          "sha256": "27f4258bfaf1c3aa45005e9394a411f3a23a8fc5fa525071ebd1bfefdeef264c",
          "sha1": "df1c5c97db080de86295bf948ad196576b157146",
          "md5": "bc8895072afc180999c29d6300b2e2f8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.8-STABLE-sources.jar",
          "url": "ConnectorAPI-0.1.8-STABLE-sources.jar",
          "size": 16563,
          "sha512": "833f8104cc5d44ccf0654192acec4ee9fd4d330479c75d386da1c9cbfe3b8da79fd8a429b547597bf971fa1befec722c01b37275ca7ac30b77e5100062068a95",
          "sha256": "84436cf81964e242dc24e6174d449dabf8826f128ff665f0ee314acee176f7d9",
          "sha1": "7d02f2c8ae59174b9cc338b348f689e102e33504",
          "md5": "9e7832bdff3d84e9d27b4ec4ed1babc9"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.8-STABLE-javadoc.jar",
          "url": "ConnectorAPI-0.1.8-STABLE-javadoc.jar",
          "size": 153881,
          "sha512": "c66a66846060fb8d1832f87d96ab286d13066007236253519d51e994d7a80a821b7b2766c9985e6ca0ee102ab27e05e40acf7e68809c34031ec9c24753ad3083",
          "sha256": "c9ddf6d1a4e2f6f79c54a7aa64ac9aba919cdc5d5f9017e55f0ddbc2cd6b7dba",
          "sha1": "7a4430e4fe9b6d1d746430815bc8d010e0fcfa99",
          "md5": "a092fe6beb8b367dc3eb167d73d7fbf2"
        }
      ]
    }
  ]
}
