{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectorAPI",
    "version": "0.1.8-STABLE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.8-STABLE.jar",
          "url": "ConnectorAPI-0.1.8-STABLE.jar",
          "size": 30263,
          "sha512": "61a033b157decc7049f41f841c834a3b4240a8a4ec71cf75b14696b0c6f29e03798b7c2400415eefd02d6eeadcf833a4e4d3698a3d486c9f663a1c4439eba6c6",
          "sha256": "f588db59140f57040e41f73b5f0049b65e69612d1624f7043bf3d26812f4e36a",
          "sha1": "d158483bac49aff5664314174c74753e255684c9",
          "md5": "aaa7edc12dcba939d48f3c19d65898b7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "ConnectorAPI-0.1.8-STABLE.jar",
          "url": "ConnectorAPI-0.1.8-STABLE.jar",
          "size": 30263,
          "sha512": "61a033b157decc7049f41f841c834a3b4240a8a4ec71cf75b14696b0c6f29e03798b7c2400415eefd02d6eeadcf833a4e4d3698a3d486c9f663a1c4439eba6c6",
          "sha256": "f588db59140f57040e41f73b5f0049b65e69612d1624f7043bf3d26812f4e36a",
          "sha1": "d158483bac49aff5664314174c74753e255684c9",
          "md5": "aaa7edc12dcba939d48f3c19d65898b7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.8-STABLE-sources.jar",
          "url": "ConnectorAPI-0.1.8-STABLE-sources.jar",
          "size": 16563,
          "sha512": "dadc829d31f919627cb9b488b9ed02bbf2ac83188c45a05f56bcfd14fe2813195c977b0d7737cf6e2e3c75e76b913264704089e0de10cb6a62761023fd3b79fe",
          "sha256": "2b9facbccb07c2b8cad29f90454ebf6fd0901b96b87f52934292ff0ec423a748",
          "sha1": "6faee7fc09eb1595b890d914651c478a83c3736c",
          "md5": "57364f8165c4d55641c9a175162f5af6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.8-STABLE-javadoc.jar",
          "url": "ConnectorAPI-0.1.8-STABLE-javadoc.jar",
          "size": 153881,
          "sha512": "24d58599f2a79736b377a2233e26c004833919aac60776e66b062ce47c7dfcc27065193b7c2d81570f0e85c7e9eeaea45e044f633fce105f03b6d405dcd9db85",
          "sha256": "37ed68a82fafe7b5f2e12cf65723e33f2ece505d54f558901efd843f9106e70e",
          "sha1": "a6d6acd8720a6514f2cd4c68430ae6c916e76797",
          "md5": "97563db376acda6b54bf82d501c1493c"
        }
      ]
    }
  ]
}
