{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectLib",
    "version": "0.3.4-STABLE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectLib-0.3.4-STABLE.jar",
          "url": "ConnectLib-0.3.4-STABLE.jar",
          "size": 43632,
          "sha512": "f1b0906f1447a52b8971dd0d0f4b8605dc0c72d02304d2e4c3d1e5e95543f35cee28aceecc9d78c8e9c7397578a083062ecc962d65642ace7428dbb86f8b9755",
          "sha256": "3fc9cc09e3dbd47a9d45b2f0782502340340d2fe881c163ba7b6b419420c9ee8",
          "sha1": "65b39abd0b5e2f0cd8a9052b5f988c5bab320a21",
          "md5": "e523eddbf4b027a7cc2ce8cb0326a346"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "ConnectLib-0.3.4-STABLE.jar",
          "url": "ConnectLib-0.3.4-STABLE.jar",
          "size": 43632,
          "sha512": "f1b0906f1447a52b8971dd0d0f4b8605dc0c72d02304d2e4c3d1e5e95543f35cee28aceecc9d78c8e9c7397578a083062ecc962d65642ace7428dbb86f8b9755",
          "sha256": "3fc9cc09e3dbd47a9d45b2f0782502340340d2fe881c163ba7b6b419420c9ee8",
          "sha1": "65b39abd0b5e2f0cd8a9052b5f988c5bab320a21",
          "md5": "e523eddbf4b027a7cc2ce8cb0326a346"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectLib-0.3.4-STABLE-sources.jar",
          "url": "ConnectLib-0.3.4-STABLE-sources.jar",
          "size": 26624,
          "sha512": "78dd89b9032c27b3b1fefda9624deb542f61d59e27c90a1a363e81a905356cf07a7b6b542a95da367b5dadea6269b86ff646adbf1214b84db0fd3444a06487ca",
          "sha256": "34282dcc41a48a223723e5f66ba5ebe4fe03be75c61a6834f56da14bb57c9ea3",
          "sha1": "42f99c67c461005f448d8aba79e837770f5f8ee5",
          "md5": "bae73d9ad3eb1d260def8986483b1db9"
        }
      ]
    }
  ]
}
