{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectLib",
    "version": "0.3.4-STABLE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectLib-0.3.4-STABLE.jar",
          "url": "ConnectLib-0.3.4-STABLE.jar",
          "size": 43632,
          "sha512": "ad5573cba9f46e7329176ac0d59335260b8ac76272522aae6944a358f13a099fa3a11e06e7668034552897bef9d01e0952e59baf549af1b6009f29fb3865185a",
          "sha256": "cb76d32010bf9c65501bbe994acb47b3a276c27dccb6ee4c5ce89440b5b2ab87",
          "sha1": "2960d3957fd53c0a0e15b17782a4091e6a3fc90d",
          "md5": "b3e1edfc8158272088ee75aa1a887cbe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "ConnectLib-0.3.4-STABLE.jar",
          "url": "ConnectLib-0.3.4-STABLE.jar",
          "size": 43632,
          "sha512": "ad5573cba9f46e7329176ac0d59335260b8ac76272522aae6944a358f13a099fa3a11e06e7668034552897bef9d01e0952e59baf549af1b6009f29fb3865185a",
          "sha256": "cb76d32010bf9c65501bbe994acb47b3a276c27dccb6ee4c5ce89440b5b2ab87",
          "sha1": "2960d3957fd53c0a0e15b17782a4091e6a3fc90d",
          "md5": "b3e1edfc8158272088ee75aa1a887cbe"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectLib-0.3.4-STABLE-sources.jar",
          "url": "ConnectLib-0.3.4-STABLE-sources.jar",
          "size": 26624,
          "sha512": "a8192bc5d5dd58831fca62b4239973f3215721b94b1a5f73bd1201ed9f13d4144c383935b87060278f9ab8e17bd61892531b24074b214a9f1df76eccb9e89f0a",
          "sha256": "8d45b842a8f19428ff770c158fcf063f666b840a31cfa6f40dfb428355dfb702",
          "sha1": "91197953457f78315a8c3598f2c7f1361745cc69",
          "md5": "a50b0a594c1813eb385db7eda73ee62c"
        }
      ]
    }
  ]
}
