{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectLib",
    "version": "0.3.4-STABLE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectLib-0.3.4-STABLE.jar",
          "url": "ConnectLib-0.3.4-STABLE.jar",
          "size": 43632,
          "sha512": "daae6461bd3dd72e67fa3254ee10bb180d8d508d4a938edef9f7f65c598911caf248f182f769e357541fcc8db32548cc0d2a241b1f44930580ee8b4c01c6dd79",
          "sha256": "affef27d172ce55b03a72aa5758472a4560a6551e3dfc2bd699b15c19c7bba0c",
          "sha1": "33ff0bc1f06845f31ea8cf4dd795a80211379f05",
          "md5": "1ab611a94897d5040b2be46eb9c4e4a1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "ConnectLib-0.3.4-STABLE.jar",
          "url": "ConnectLib-0.3.4-STABLE.jar",
          "size": 43632,
          "sha512": "daae6461bd3dd72e67fa3254ee10bb180d8d508d4a938edef9f7f65c598911caf248f182f769e357541fcc8db32548cc0d2a241b1f44930580ee8b4c01c6dd79",
          "sha256": "affef27d172ce55b03a72aa5758472a4560a6551e3dfc2bd699b15c19c7bba0c",
          "sha1": "33ff0bc1f06845f31ea8cf4dd795a80211379f05",
          "md5": "1ab611a94897d5040b2be46eb9c4e4a1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectLib-0.3.4-STABLE-sources.jar",
          "url": "ConnectLib-0.3.4-STABLE-sources.jar",
          "size": 26624,
          "sha512": "f0087c31c5621977c60b2933c18545621e47399d20c5f755af2f71fd79305261fd58a5015c1bcd95c511dfff855a573b954efd10e97bd5e0e1b7e030fe9e5bb2",
          "sha256": "be3a9374587b38c3c50364df14c3a045352cc441bfab84bba4a715bf1f197118",
          "sha1": "c9afd9f97600a9f571950653421c861fe0ade8c3",
          "md5": "050c1c13cbc6489f46c6ec40b556eb82"
        }
      ]
    }
  ]
}
