{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectorAPI",
    "version": "0.1.3.17.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.17.1-SNAPSHOT.jar",
          "url": "ConnectorAPI-0.1.3.17.1-SNAPSHOT.jar",
          "size": 25925,
          "sha512": "70cbc0c1966f68d5b6580fa88918054e286b272495a2dff78392aecb7c2dae02a0a93ccb04f76404492fd8f94f76edea482f80a9fde9f6b780fa86f3b5531ee6",
          "sha256": "77bc40b6345e59c1b64320b9c03aa8a15fd594e91a162fbd8f0e96763b0e3cb7",
          "sha1": "259b5c759ef9c2e839249c218052b426cfad9ac7",
          "md5": "80d0fa8aa049601d1b6885c37cd515e9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-base",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-base",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-graphics",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-graphics",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-controls",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-controls",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-fxml",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-fxml",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.17.1-SNAPSHOT.jar",
          "url": "ConnectorAPI-0.1.3.17.1-SNAPSHOT.jar",
          "size": 25925,
          "sha512": "70cbc0c1966f68d5b6580fa88918054e286b272495a2dff78392aecb7c2dae02a0a93ccb04f76404492fd8f94f76edea482f80a9fde9f6b780fa86f3b5531ee6",
          "sha256": "77bc40b6345e59c1b64320b9c03aa8a15fd594e91a162fbd8f0e96763b0e3cb7",
          "sha1": "259b5c759ef9c2e839249c218052b426cfad9ac7",
          "md5": "80d0fa8aa049601d1b6885c37cd515e9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.17.1-SNAPSHOT-sources.jar",
          "url": "ConnectorAPI-0.1.3.17.1-SNAPSHOT-sources.jar",
          "size": 14900,
          "sha512": "8cdc522b7f7b4af259d0d81ed58251b02f6a522ee8965f6caffc279d7d834bb9ff8624017facbeace872ced193158307c7541189fb463a5ed0c72566d144a976",
          "sha256": "31d8d2b58a9a628f6123e204301142ad289b10d662abb1876b3d350eef274d86",
          "sha1": "cb8365d95bc621ba6dcda82f40e02f97a6113949",
          "md5": "7c182c6921620a9c4cc593c46bf192e2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.17.1-SNAPSHOT-javadoc.jar",
          "url": "ConnectorAPI-0.1.3.17.1-SNAPSHOT-javadoc.jar",
          "size": 145789,
          "sha512": "00bfad72b4d546fc937d233df183c6bcc63b4387ec8a807ae91afa3caf77d362564bd02913d6b6cef5052f1e5a00ef75835efd766bc9e62eb6331a541000026f",
          "sha256": "16d70c857962ec94fb41dbe36dd01031849ad290d26416471ff17f24d61cdcbc",
          "sha1": "1a5063291ab43cc4ebe01776be37d8fc6ad47f58",
          "md5": "a4e62f0895b3bc9f15f11b80b337033c"
        }
      ]
    }
  ]
}
