{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectorAPI",
    "version": "0.1.3.17.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.17.1-SNAPSHOT.jar",
          "url": "ConnectorAPI-0.1.3.17.1-SNAPSHOT.jar",
          "size": 25925,
          "sha512": "376be07ebfedb17fcf6cb698a70c937b8621e8a1bb1729f35f85fcd82bb8dd4df30b9ef22230d132214059ebe2e0fd06cb4ead7fff8a5e5ca53f5e6fb8e6a3b5",
          "sha256": "ef0ec01c6f9c83f90e28711462ab5b0885ec8eef9441e55bfd8e7132e1424396",
          "sha1": "202af6b681a131385f6bb239c0188f5a056b0cd3",
          "md5": "dca8a962a2fc6087e67af0d0f1698260"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-base",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-base",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-graphics",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-graphics",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-controls",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-controls",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-fxml",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-fxml",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.17.1-SNAPSHOT.jar",
          "url": "ConnectorAPI-0.1.3.17.1-SNAPSHOT.jar",
          "size": 25925,
          "sha512": "376be07ebfedb17fcf6cb698a70c937b8621e8a1bb1729f35f85fcd82bb8dd4df30b9ef22230d132214059ebe2e0fd06cb4ead7fff8a5e5ca53f5e6fb8e6a3b5",
          "sha256": "ef0ec01c6f9c83f90e28711462ab5b0885ec8eef9441e55bfd8e7132e1424396",
          "sha1": "202af6b681a131385f6bb239c0188f5a056b0cd3",
          "md5": "dca8a962a2fc6087e67af0d0f1698260"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.17.1-SNAPSHOT-sources.jar",
          "url": "ConnectorAPI-0.1.3.17.1-SNAPSHOT-sources.jar",
          "size": 14900,
          "sha512": "cfeb5f3f2a974bc087203cec4cb2efa1126d2da787a47b0e509ae2ffaf80974b75294bd3156c72636c77ef0caaa12f9cf7471eef96ff6b4f2b7be2b940420147",
          "sha256": "470e57460f5ada19bf9f8150100e6ccac9d3f029ad240e9a6395c18710e45f22",
          "sha1": "a99b1f292577817fd30188772ad531e125429706",
          "md5": "8a7491990853a151850cd7d567cc1b45"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.17.1-SNAPSHOT-javadoc.jar",
          "url": "ConnectorAPI-0.1.3.17.1-SNAPSHOT-javadoc.jar",
          "size": 145789,
          "sha512": "92d06495787fdd4bd06497d74c19ab9bcd8222f20a68a931b5e82e96fb44a536eb6aba1ccf1cb13206c9718afa9151cc3c7e14d2f800897c4a94b8485cba7629",
          "sha256": "c0422e0fa8cd9f05685144c5aa33c463582a5d0117212f9cb18d5fbe0fa4a19d",
          "sha1": "29899efc9ae68fb3435753d18e4e12faa9311802",
          "md5": "f66a66b4279f2c2a554dc94c1ff4e7d9"
        }
      ]
    }
  ]
}
