{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectorAPI",
    "version": "0.1.3.17.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.17.1-SNAPSHOT.jar",
          "url": "ConnectorAPI-0.1.3.17.1-SNAPSHOT.jar",
          "size": 25925,
          "sha512": "be0b4f672e36953d93aa8438c1c55514ec8e76b6d95d83215f51de89501c430875ce96cb790c3e31e316f8fe1f6f9b7c883f14a9af256f205ef1122fe4d445af",
          "sha256": "ab07091b40947db13195eece69d17a1c9d54974529f004662121294a732253b7",
          "sha1": "e9fd05743eb5585e9aa85148e1d1c375b6fbe6fb",
          "md5": "44e140343de9607a8eefe1782109afe5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-base",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-base",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-graphics",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-graphics",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-controls",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-controls",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-fxml",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-fxml",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.17.1-SNAPSHOT.jar",
          "url": "ConnectorAPI-0.1.3.17.1-SNAPSHOT.jar",
          "size": 25925,
          "sha512": "be0b4f672e36953d93aa8438c1c55514ec8e76b6d95d83215f51de89501c430875ce96cb790c3e31e316f8fe1f6f9b7c883f14a9af256f205ef1122fe4d445af",
          "sha256": "ab07091b40947db13195eece69d17a1c9d54974529f004662121294a732253b7",
          "sha1": "e9fd05743eb5585e9aa85148e1d1c375b6fbe6fb",
          "md5": "44e140343de9607a8eefe1782109afe5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.17.1-SNAPSHOT-sources.jar",
          "url": "ConnectorAPI-0.1.3.17.1-SNAPSHOT-sources.jar",
          "size": 14900,
          "sha512": "eef174f4d9e093f328313da6e5788e7ef445538d39add88e0fb19a78534b7c8bc4a310ed4a58bcb107f5ffa78a58eb9c44c50038c287cab9d2e79d1a7d0a023b",
          "sha256": "75043bb964db28f18e7448a72b56d92437ceb08d5c3528cad3d926b48ab31898",
          "sha1": "b7bcc9902ff2adf9b08bd386ec04378ca51a3a15",
          "md5": "8519aeff094de1898b272dcaecccd24d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.17.1-SNAPSHOT-javadoc.jar",
          "url": "ConnectorAPI-0.1.3.17.1-SNAPSHOT-javadoc.jar",
          "size": 145789,
          "sha512": "aa17c6017b10e0bcb9f6121003dab4ca2f326738f4b1774f3cd29f5de323b854b21d6c3819eb8702f3b8e500d426f782e31844ec83fb5c639c57fa668a513ece",
          "sha256": "bbf178e8f68ff098c13834732cc0f6c29c1cd5bac2adbc714fb22b51062d972f",
          "sha1": "516fb63531091b5fe107da87bf3a1d0e7acefc66",
          "md5": "2acbcfdf61f65e6ae08769fc61a72f84"
        }
      ]
    }
  ]
}
