{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectorAPI",
    "version": "0.1.3.17.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.17.1-SNAPSHOT.jar",
          "url": "ConnectorAPI-0.1.3.17.1-SNAPSHOT.jar",
          "size": 25925,
          "sha512": "23c1b2208f8a7bb564d0250975de1b3f9dd1c13f6bb93b14f2f5e99e706d2d3089f3cec579b87b37ed98d67c72f8200d854765a39e122c6f0642a4adff46d71c",
          "sha256": "2445df6d6b3ac5e76b654f7fcdb9e4f25f04056f86a885dc9a62b3bf13cd325b",
          "sha1": "f8c28008a2e2eae21fbc2e1b08456e559446b1f9",
          "md5": "67444bd1923f79623817ee4aa2896ba3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-base",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-base",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-graphics",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-graphics",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-controls",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-controls",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-fxml",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-fxml",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.17.1-SNAPSHOT.jar",
          "url": "ConnectorAPI-0.1.3.17.1-SNAPSHOT.jar",
          "size": 25925,
          "sha512": "23c1b2208f8a7bb564d0250975de1b3f9dd1c13f6bb93b14f2f5e99e706d2d3089f3cec579b87b37ed98d67c72f8200d854765a39e122c6f0642a4adff46d71c",
          "sha256": "2445df6d6b3ac5e76b654f7fcdb9e4f25f04056f86a885dc9a62b3bf13cd325b",
          "sha1": "f8c28008a2e2eae21fbc2e1b08456e559446b1f9",
          "md5": "67444bd1923f79623817ee4aa2896ba3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.17.1-SNAPSHOT-sources.jar",
          "url": "ConnectorAPI-0.1.3.17.1-SNAPSHOT-sources.jar",
          "size": 14900,
          "sha512": "7400e22d5287fec61752e8538d65ef282e344da3c15bf04415f2960c19f59d8f99a13f89b3ebb9c47394142e320ee0b7bb1efee3a34617afee1445b01591938b",
          "sha256": "198f0eb7ef5a21f788b6144768d03815cdf223cfc6314a809683fab52e161442",
          "sha1": "71983f1fc4cedada3ee4a9145e7011b1f56ad698",
          "md5": "e9b294340571ed6eb4176c08f62d5236"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.17.1-SNAPSHOT-javadoc.jar",
          "url": "ConnectorAPI-0.1.3.17.1-SNAPSHOT-javadoc.jar",
          "size": 145789,
          "sha512": "77dab55cda5bfb11651b78c1e0c65bbe719ef2fc2f29ddf029cd2ebae3694f4897e8ad3060138bd90d6b5e211182e5743614822ce2d7176bf7a1aed740c81763",
          "sha256": "1775a151994db072348c05fd420832cb16562ed17f5f5cd9900a25d8e2a03594",
          "sha1": "cd96cd4cd8183e40868709c63e9fb5246df0ec5f",
          "md5": "8b0e5dd97ead2d2c8749c9a727208fab"
        }
      ]
    }
  ]
}
