{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectorAPI",
    "version": "0.1.3.17.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.17.1-SNAPSHOT.jar",
          "url": "ConnectorAPI-0.1.3.17.1-SNAPSHOT.jar",
          "size": 25925,
          "sha512": "e3f555512264a2c7e87b1a7fa3936d044d96c105c6702104bc8a7863d94177ed3ee484019e4acb351887549bb2b64197eda1af9130beae1a3f5d779a96ed32a3",
          "sha256": "012fafb6ae1c51e8b4adc3ed048956b72ede61551154c8fe5c2c0a6eddb6d9df",
          "sha1": "e9698874206cc5e0df3694c3858c528ea42caa07",
          "md5": "9ef6cae5500fb39844600991b0513cc0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-base",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-base",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-graphics",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-graphics",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-controls",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-controls",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-fxml",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-fxml",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.17.1-SNAPSHOT.jar",
          "url": "ConnectorAPI-0.1.3.17.1-SNAPSHOT.jar",
          "size": 25925,
          "sha512": "e3f555512264a2c7e87b1a7fa3936d044d96c105c6702104bc8a7863d94177ed3ee484019e4acb351887549bb2b64197eda1af9130beae1a3f5d779a96ed32a3",
          "sha256": "012fafb6ae1c51e8b4adc3ed048956b72ede61551154c8fe5c2c0a6eddb6d9df",
          "sha1": "e9698874206cc5e0df3694c3858c528ea42caa07",
          "md5": "9ef6cae5500fb39844600991b0513cc0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.17.1-SNAPSHOT-sources.jar",
          "url": "ConnectorAPI-0.1.3.17.1-SNAPSHOT-sources.jar",
          "size": 14900,
          "sha512": "261842d2bee48942ff140bd1abf713571848a43e9da9440e211a9c0d03517f04a9537f32975604e062ab504b6c73b27ccd6b9f31989fa9552d94775f18798a31",
          "sha256": "5224492f42955867887e510d48dedb8812c180282a22b44eeff2c87f82de397d",
          "sha1": "65deb753b39df80a7c0c50b95e0e88e576e113f4",
          "md5": "7b08a8f14ca5151f5bc43f1f3e6b11e7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.17.1-SNAPSHOT-javadoc.jar",
          "url": "ConnectorAPI-0.1.3.17.1-SNAPSHOT-javadoc.jar",
          "size": 145789,
          "sha512": "895190483bf2215caacfe3609352195790b70d778477330b50d4e499b388a3cdbe8b3257cce9db2746347dd7dafbf77f8820eb71921da3befeb9225b361af971",
          "sha256": "6891dd6c210756c3ed61932a2078265817b77ea0fdeb248588fdeee228dcde10",
          "sha1": "5f317913d62f631b102c4af2b727225fc18a98fa",
          "md5": "335646cce44e2b3c75e69fe1299a6767"
        }
      ]
    }
  ]
}
