{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectorAPI",
    "version": "0.1.3.17.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.17.1-SNAPSHOT.jar",
          "url": "ConnectorAPI-0.1.3.17.1-SNAPSHOT.jar",
          "size": 25925,
          "sha512": "f697a3e812d05158363543e22952c90cc5bb89301692303202ccd62c6aebe23d19d45de62fa82e3c1927cd17e2f9eb252fd6e10f4f04db23dd4cb115f1902235",
          "sha256": "74ef71a027d58e4d878acfb52aece9716e97746c3cc264d450fed45380644f4e",
          "sha1": "4c01ba0415da28698ed5a022949f773f40dd069e",
          "md5": "77b518526fd8c9436d25fd38866dc52b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-base",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-base",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-graphics",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-graphics",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-controls",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-controls",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-fxml",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-fxml",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.17.1-SNAPSHOT.jar",
          "url": "ConnectorAPI-0.1.3.17.1-SNAPSHOT.jar",
          "size": 25925,
          "sha512": "f697a3e812d05158363543e22952c90cc5bb89301692303202ccd62c6aebe23d19d45de62fa82e3c1927cd17e2f9eb252fd6e10f4f04db23dd4cb115f1902235",
          "sha256": "74ef71a027d58e4d878acfb52aece9716e97746c3cc264d450fed45380644f4e",
          "sha1": "4c01ba0415da28698ed5a022949f773f40dd069e",
          "md5": "77b518526fd8c9436d25fd38866dc52b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.17.1-SNAPSHOT-sources.jar",
          "url": "ConnectorAPI-0.1.3.17.1-SNAPSHOT-sources.jar",
          "size": 14900,
          "sha512": "e62804ba8de100687e1e4d8296e8abf5a8d7697e3b3e6a8efb533793822ab87d12f04f0b1535586306b6434355343934308b56cdae0bbf69af16b983dfbf4411",
          "sha256": "a176ce675a32fdcd608e5469b89ed45c02026ac8e4704fea21761de446079265",
          "sha1": "899b6ba0a3e109ab07e3bbea37477a545120323f",
          "md5": "0a7fa93a98deca7563bf2cf18fa28a4a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.17.1-SNAPSHOT-javadoc.jar",
          "url": "ConnectorAPI-0.1.3.17.1-SNAPSHOT-javadoc.jar",
          "size": 145789,
          "sha512": "f64bf7df04f4b507a86a67a5d1d464e1ace288ef1a79f1bb096db6d2a732d8096e0e7ea9b60091709a1f1c8daf1aba5eebef377d6ee4525098049a4c8a42075a",
          "sha256": "e4b0e7ee053c7fb1a63996b78afd479f0e85931b62a4a253f75911f9db1ea27e",
          "sha1": "d423c9cd1d9709af4c4fbdbeb496a75f1934a27b",
          "md5": "182539d952446e2d5b9a768b12ea8bbd"
        }
      ]
    }
  ]
}
