{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectorAPI",
    "version": "0.1.3.17.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.17.1-SNAPSHOT.jar",
          "url": "ConnectorAPI-0.1.3.17.1-SNAPSHOT.jar",
          "size": 25925,
          "sha512": "11205a3613eaae42bee08f42cf3e74a71a3d9c6aff9db0f0ce58dc2dc8b27816528a54f6959334ac0f3462f12929973a0d15b7c8c85d5b7dac3e8f6866d18fb7",
          "sha256": "043bed3a5f58b9d25e41a7461f54989f4d303bb2ecf39b814f25479a80dc2a4c",
          "sha1": "50e389f8cfff384500429cd1cf10003f4020cea4",
          "md5": "b68481484b3060307aa71add9d47661f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-base",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-base",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-graphics",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-graphics",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-controls",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-controls",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-fxml",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-fxml",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.17.1-SNAPSHOT.jar",
          "url": "ConnectorAPI-0.1.3.17.1-SNAPSHOT.jar",
          "size": 25925,
          "sha512": "11205a3613eaae42bee08f42cf3e74a71a3d9c6aff9db0f0ce58dc2dc8b27816528a54f6959334ac0f3462f12929973a0d15b7c8c85d5b7dac3e8f6866d18fb7",
          "sha256": "043bed3a5f58b9d25e41a7461f54989f4d303bb2ecf39b814f25479a80dc2a4c",
          "sha1": "50e389f8cfff384500429cd1cf10003f4020cea4",
          "md5": "b68481484b3060307aa71add9d47661f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.17.1-SNAPSHOT-sources.jar",
          "url": "ConnectorAPI-0.1.3.17.1-SNAPSHOT-sources.jar",
          "size": 14900,
          "sha512": "88c439acd1f8a575ff2962456b3b2488af8938594e4eb6bdc6b215dcb882486090669ca21a65190bd20419d5dc44fdf3c1bda4a7874302ef3e5d9072d315dd8e",
          "sha256": "d2b36e8ff3f0fea8621891a1e241a4dfdf3d317a82052592b1cc0b0e4d1d3e72",
          "sha1": "57a4b15fdf220c67f3b5071138648037c39b6da1",
          "md5": "16873cfb1e5e58a7df9dcfb1e488ecec"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.17.1-SNAPSHOT-javadoc.jar",
          "url": "ConnectorAPI-0.1.3.17.1-SNAPSHOT-javadoc.jar",
          "size": 145789,
          "sha512": "125ef6a00319a436cf6abe7569035baec6f964a7e7dd1921dabd7f5a93ebed1aed6a4f78649a5239fa0b083179b6c2c3aa95b342329bc5a02f77fd855fad1a5d",
          "sha256": "719a5615510979146a25a188aefc690eddcd28927429b5fc5f37dcf1bb6c9a2c",
          "sha1": "58893c739d885aeec9c39e051373fd93ffe15a1e",
          "md5": "8f9d7cd68b442059580526328ca0f3fb"
        }
      ]
    }
  ]
}
