{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectorAPI",
    "version": "0.1.3.17.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.17.1-SNAPSHOT.jar",
          "url": "ConnectorAPI-0.1.3.17.1-SNAPSHOT.jar",
          "size": 25925,
          "sha512": "b7dac2ec725dc8cfb3919faf1aa5b442e9d6fa137a86bffa9ce8ef8c4cf631d9069c06626c3e66ca7edd22abccd5b108fbe75b4e4ec3241d2083adfcd747e8f9",
          "sha256": "44e43a510809a3b207155d72e9c1a0111f7185f1516302fd446eff069f96ffc8",
          "sha1": "aa14cecfebcf4bb16a8d86eee94a94e8e84dd9f0",
          "md5": "571a8de111dc21cda5d3f6be47448553"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-base",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-base",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-graphics",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-graphics",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-controls",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-controls",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-fxml",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-fxml",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.17.1-SNAPSHOT.jar",
          "url": "ConnectorAPI-0.1.3.17.1-SNAPSHOT.jar",
          "size": 25925,
          "sha512": "b7dac2ec725dc8cfb3919faf1aa5b442e9d6fa137a86bffa9ce8ef8c4cf631d9069c06626c3e66ca7edd22abccd5b108fbe75b4e4ec3241d2083adfcd747e8f9",
          "sha256": "44e43a510809a3b207155d72e9c1a0111f7185f1516302fd446eff069f96ffc8",
          "sha1": "aa14cecfebcf4bb16a8d86eee94a94e8e84dd9f0",
          "md5": "571a8de111dc21cda5d3f6be47448553"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.17.1-SNAPSHOT-sources.jar",
          "url": "ConnectorAPI-0.1.3.17.1-SNAPSHOT-sources.jar",
          "size": 14900,
          "sha512": "93b6608d339d4c042aa4a4152f7c99b80d77566567b81f5e47a95a56640c3ec27a3930cb808843b939c7918737d254fb66eb6988ead4b7d4666ce570f15737d0",
          "sha256": "87737654127b09133ddd3d3a1d9a270e9b80583168222e51003e98bc98cc9ea0",
          "sha1": "1f304daa2a927e2e899acb8bd5bc7cd3bd396454",
          "md5": "ff9590a7e3e2c28e9933c3447dac03e6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.17.1-SNAPSHOT-javadoc.jar",
          "url": "ConnectorAPI-0.1.3.17.1-SNAPSHOT-javadoc.jar",
          "size": 145789,
          "sha512": "6041c0c9955d80cf53e08c474194b31dcaadd410e6d72277243d6e3bed746846f3055e9e598d6c25189e22b699f42a44bd90eeb82c51641c3335029a7687df50",
          "sha256": "2cfe03b880ed93b37d569189c5a30196947690c827f03834de23242706232c01",
          "sha1": "0fb03c5c846f9e4d978d4888f7d511250558e8b8",
          "md5": "1188baf04a5d84fdfb8f46fbe7dd8d72"
        }
      ]
    }
  ]
}
