{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectLib",
    "version": "0.4.6-STABLE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectLib-0.4.6-STABLE.jar",
          "url": "ConnectLib-0.4.6-STABLE.jar",
          "size": 63954,
          "sha512": "1d226cf744830bf43a3a03f974a126aef968f09616c737bf695db8ca74f5d86e8eedc52c80bc6cf5ef327af99f14a464fab8a9ca85c741a23b2ba82b10595594",
          "sha256": "070e3991238c38002dcc9504e82859921be1930d3b1336a7bef9803b933bca86",
          "sha1": "affbd6dff56f1bf325eb73922de9cfe87e98170d",
          "md5": "72b93922c443106c0c437faa7b5f5e05"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "ConnectLib-0.4.6-STABLE.jar",
          "url": "ConnectLib-0.4.6-STABLE.jar",
          "size": 63954,
          "sha512": "1d226cf744830bf43a3a03f974a126aef968f09616c737bf695db8ca74f5d86e8eedc52c80bc6cf5ef327af99f14a464fab8a9ca85c741a23b2ba82b10595594",
          "sha256": "070e3991238c38002dcc9504e82859921be1930d3b1336a7bef9803b933bca86",
          "sha1": "affbd6dff56f1bf325eb73922de9cfe87e98170d",
          "md5": "72b93922c443106c0c437faa7b5f5e05"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectLib-0.4.6-STABLE-sources.jar",
          "url": "ConnectLib-0.4.6-STABLE-sources.jar",
          "size": 38851,
          "sha512": "1cc3364d00fabfe943d22595e34697d4ad48c5c11b8711b095f2a255b348f0bade8c82798d0991b6351a0e9f2b25cdf14cd1d2eb2e2d680c2fbb57114fd2e9c3",
          "sha256": "018627c71bd8a32c7a36846d446c33d09ef6071b9ac8bd0bef4cc0451bc73231",
          "sha1": "9ee6fe7ab1112cc3b7c5efdc67e71ed2a13ea9dd",
          "md5": "4be51367e0fb5d39c4a1c8e22c950498"
        }
      ]
    }
  ]
}
