{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectLib",
    "version": "0.4.6-STABLE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectLib-0.4.6-STABLE.jar",
          "url": "ConnectLib-0.4.6-STABLE.jar",
          "size": 62459,
          "sha512": "1db2055a9865457668c6765db17b5f631efc20a2b2641b193fa4066f93a5c075d274ec6e715358977d5bad9f934dae7dec3485586445746c3be086dba2b740bd",
          "sha256": "d45c367054bc98ade48ccacab097bad6a6c75ebf6d890d2eee79e11c08fb3bdb",
          "sha1": "3eafee3beebaba0f66e708d27bfbd4d6d133efbc",
          "md5": "4f4d2da5b7d8de32911655cbc0e002f0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "ConnectLib-0.4.6-STABLE.jar",
          "url": "ConnectLib-0.4.6-STABLE.jar",
          "size": 62459,
          "sha512": "1db2055a9865457668c6765db17b5f631efc20a2b2641b193fa4066f93a5c075d274ec6e715358977d5bad9f934dae7dec3485586445746c3be086dba2b740bd",
          "sha256": "d45c367054bc98ade48ccacab097bad6a6c75ebf6d890d2eee79e11c08fb3bdb",
          "sha1": "3eafee3beebaba0f66e708d27bfbd4d6d133efbc",
          "md5": "4f4d2da5b7d8de32911655cbc0e002f0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectLib-0.4.6-STABLE-sources.jar",
          "url": "ConnectLib-0.4.6-STABLE-sources.jar",
          "size": 38199,
          "sha512": "ecc08af09d2c5a6b8a0c3c4f2c01cca8fc2b7edd0eb8bd49d4f9b846ccb352885d6aae8d73ec62a8dd12978794c890c8edc12b0ee9d18e33d8a866f08b20eef4",
          "sha256": "8ed79f771cfe117023d24ed37bdd2ee1cb596b9da8fddc8906972046d00445cc",
          "sha1": "b2f2e5f658ed49fef01368a77db9b50a9f6202c9",
          "md5": "ab64e3da96bddca302959d861c4ab695"
        }
      ]
    }
  ]
}
