{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectLib",
    "version": "0.4.6-STABLE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectLib-0.4.6-STABLE.jar",
          "url": "ConnectLib-0.4.6-STABLE.jar",
          "size": 62459,
          "sha512": "6bafe799864fd8d123b720fd8eb077d8163522af9ccb479f1f62ec3a0d9592d5b3e88c9f983695bb8b514e9edfd8c3b002825c30bd06357ebc6a19a3d719de45",
          "sha256": "ab34d5f6b9e8590edbd216ac1227dcbfe850759d43759cdd007e061404f7d54c",
          "sha1": "d313cad4e510b534e31039fe2bd6d1686347fe22",
          "md5": "9357cb7e3317d492fae465ae52685f28"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "ConnectLib-0.4.6-STABLE.jar",
          "url": "ConnectLib-0.4.6-STABLE.jar",
          "size": 62459,
          "sha512": "6bafe799864fd8d123b720fd8eb077d8163522af9ccb479f1f62ec3a0d9592d5b3e88c9f983695bb8b514e9edfd8c3b002825c30bd06357ebc6a19a3d719de45",
          "sha256": "ab34d5f6b9e8590edbd216ac1227dcbfe850759d43759cdd007e061404f7d54c",
          "sha1": "d313cad4e510b534e31039fe2bd6d1686347fe22",
          "md5": "9357cb7e3317d492fae465ae52685f28"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectLib-0.4.6-STABLE-sources.jar",
          "url": "ConnectLib-0.4.6-STABLE-sources.jar",
          "size": 38199,
          "sha512": "0391766255dbc9d1c7633d0df1385042cbb7f58f4f7680cc3d2b5569ecaae03b9183a47544189babecc49f89e4b1ad7ab8144f6703068958319ea55d43f8dea4",
          "sha256": "1be9f4c9438fa39c7fba5965087e6eb066129ed9a855af5229447610cea0f66a",
          "sha1": "0f5b49a527c5a2014b1d56557a6747be8337f048",
          "md5": "c02307cf0cd2ef52495f3e4c7fcee0df"
        }
      ]
    }
  ]
}
