{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectLib",
    "version": "0.4.1-STABLE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectLib-0.4.1-STABLE.jar",
          "url": "ConnectLib-0.4.1-STABLE.jar",
          "size": 64656,
          "sha512": "411e8ed1427b4761d50ad3d0a6ec6be7ee01fd336941dce97def3740ca75cf5aefa90ef068bbb488203f8c4108eb8187e53539ac045f48dece103a218c927559",
          "sha256": "12de5bc09a35a4ee8e458c68c1d6b59c3f059acf8941693f4f3b7d5f9eb00f33",
          "sha1": "74f6b84fe365c9bf2b590a819ec806374e2a7f98",
          "md5": "d3617d5f3ac5f809da42e5e779cf1b09"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "ConnectLib-0.4.1-STABLE.jar",
          "url": "ConnectLib-0.4.1-STABLE.jar",
          "size": 64656,
          "sha512": "411e8ed1427b4761d50ad3d0a6ec6be7ee01fd336941dce97def3740ca75cf5aefa90ef068bbb488203f8c4108eb8187e53539ac045f48dece103a218c927559",
          "sha256": "12de5bc09a35a4ee8e458c68c1d6b59c3f059acf8941693f4f3b7d5f9eb00f33",
          "sha1": "74f6b84fe365c9bf2b590a819ec806374e2a7f98",
          "md5": "d3617d5f3ac5f809da42e5e779cf1b09"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectLib-0.4.1-STABLE-sources.jar",
          "url": "ConnectLib-0.4.1-STABLE-sources.jar",
          "size": 39143,
          "sha512": "7b41f0e783e37cb6e233b99e3f36973e6063f7ec398d026f4bb3eb181a83f1382a56907c56a983ad73a3bbf070f23a4700a8d1405d31075f6c2805ff422066e7",
          "sha256": "1528388196abaa975497eef1262af2ba3738acde9da743cc8e8fffe77e581592",
          "sha1": "e13ee0006a5279323437501c5f074ea02c65e027",
          "md5": "37ec0b704265aeb8c2718c342bf73a9c"
        }
      ]
    }
  ]
}
