{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectLib",
    "version": "0.4.1-STABLE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectLib-0.4.1-STABLE.jar",
          "url": "ConnectLib-0.4.1-STABLE.jar",
          "size": 64656,
          "sha512": "43601d12bc34ddf443c26abcbbfe1bc81cd2fec8b36fea783ab0356ded4d897b59bd2ff5a5199ce3aa3c3fb5cb8ca2a914838eb8f4ee2f71728df39cc4b6d9dd",
          "sha256": "65b5c7d32b9bbf4837d6b2e79439f70ffc183b8f2df52ef3e1cf5f1011184b14",
          "sha1": "ce86625043971039352e2552e3fa9aeb77718278",
          "md5": "a92693011ae5738a643c53c721984828"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "ConnectLib-0.4.1-STABLE.jar",
          "url": "ConnectLib-0.4.1-STABLE.jar",
          "size": 64656,
          "sha512": "43601d12bc34ddf443c26abcbbfe1bc81cd2fec8b36fea783ab0356ded4d897b59bd2ff5a5199ce3aa3c3fb5cb8ca2a914838eb8f4ee2f71728df39cc4b6d9dd",
          "sha256": "65b5c7d32b9bbf4837d6b2e79439f70ffc183b8f2df52ef3e1cf5f1011184b14",
          "sha1": "ce86625043971039352e2552e3fa9aeb77718278",
          "md5": "a92693011ae5738a643c53c721984828"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectLib-0.4.1-STABLE-sources.jar",
          "url": "ConnectLib-0.4.1-STABLE-sources.jar",
          "size": 39143,
          "sha512": "fb0841fc8f40b022763076081bd51f1670e16ad89b0266e851f80ace38731556dad2e6b58a448bad22e4423cbef219ae98a002991e7ba6c3018f7915f08fd4b6",
          "sha256": "fef75bdc9f1be55a65a6fbf515b75b53f1f2e4de170b2b18f6b780a6f9c84235",
          "sha1": "df8843e76fb43c0278bec01fe1b2496353b5a27e",
          "md5": "5f25a51bde9f1bdd708b04add8360868"
        }
      ]
    }
  ]
}
