{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.orbit",
    "module": "Orbit",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "Orbit-0.1.0.jar",
          "url": "Orbit-0.1.0.jar",
          "size": 8927,
          "sha512": "343a403c7fce10a580547bca8f154f96f536588bc2d0ca55bbab647c35f430f667799a1e05aa907d4fcfc437627f6ee551df1c18b7d05698cb266359b6e092ff",
          "sha256": "f0df335e8f79580a313288666563822fc26da5871f18a689bf582c738eb8c057",
          "sha1": "de20278cb7a99d29d1f554e6a656ac6e468af033",
          "md5": "3d525aa9308bc2e0e4193e1f6b5cccd5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "6.10.0.202406032230-r"
          }
        }
      ],
      "files": [
        {
          "name": "Orbit-0.1.0.jar",
          "url": "Orbit-0.1.0.jar",
          "size": 8927,
          "sha512": "343a403c7fce10a580547bca8f154f96f536588bc2d0ca55bbab647c35f430f667799a1e05aa907d4fcfc437627f6ee551df1c18b7d05698cb266359b6e092ff",
          "sha256": "f0df335e8f79580a313288666563822fc26da5871f18a689bf582c738eb8c057",
          "sha1": "de20278cb7a99d29d1f554e6a656ac6e468af033",
          "md5": "3d525aa9308bc2e0e4193e1f6b5cccd5"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "Orbit-0.1.0-fat.jar",
          "url": "Orbit-0.1.0-fat.jar",
          "size": 5741265,
          "sha512": "3a0e2c613abe248496237c5b7b99f30ca8f47292842475a3d88c811ba542a35ce2fac53908ec7503e21e3146d7b0af4fe40e7ccc9a34a1a9aed8d47e7b6308fa",
          "sha256": "1c641b28556468da70fafd3e15d309e80a8d2f5ec6f7718a3d9cf27b62ce98cc",
          "sha1": "c7c281ae9f5c278f4e15c307a5404cf250fb3ef3",
          "md5": "c37cca22c485606f973c875a10c0b525"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "Orbit-0.1.0-sources.jar",
          "url": "Orbit-0.1.0-sources.jar",
          "size": 5167,
          "sha512": "71ab711b456e9a9908ce8c57bc6ccfd3d26d166ebeb1056f1a085abf3a4ffe9e43070fcf7a5724eef41c72e85e60c59057785e4e3d880e61fb887e0fa75aa397",
          "sha256": "ad78ed959b732b992298c0b84a8d194a9cdbe71570a9eae1f838d19d37326d7a",
          "sha1": "70d06402cdc41289824ae8a439427a620ccee76e",
          "md5": "5d93e91bfc197fc835cb13f61e69168c"
        }
      ]
    }
  ]
}
