{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectorAPI",
    "version": "0.1.3.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.8-SNAPSHOT.jar",
          "url": "ConnectorAPI-0.1.3.8-SNAPSHOT.jar",
          "size": 25804,
          "sha512": "2ae446172dfa1cb5035b035ca45d16b171403d6adc77a1fdf857e309c33e6fd27587816a983e0cae84bc2505200da58dec0bae65a695d14167d888328e16028d",
          "sha256": "0a77296de855c84f7e99f7fc85d930c3f019bea98cae511fa785c9991b59e48f",
          "sha1": "3960b9c53fccd3333672b44bb79d1c98f5cd1110",
          "md5": "80ceded99aabe9dcb656070167c78784"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-base",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-base",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-graphics",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-graphics",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-controls",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-controls",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-fxml",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-fxml",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.8-SNAPSHOT.jar",
          "url": "ConnectorAPI-0.1.3.8-SNAPSHOT.jar",
          "size": 25804,
          "sha512": "2ae446172dfa1cb5035b035ca45d16b171403d6adc77a1fdf857e309c33e6fd27587816a983e0cae84bc2505200da58dec0bae65a695d14167d888328e16028d",
          "sha256": "0a77296de855c84f7e99f7fc85d930c3f019bea98cae511fa785c9991b59e48f",
          "sha1": "3960b9c53fccd3333672b44bb79d1c98f5cd1110",
          "md5": "80ceded99aabe9dcb656070167c78784"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.8-SNAPSHOT-sources.jar",
          "url": "ConnectorAPI-0.1.3.8-SNAPSHOT-sources.jar",
          "size": 14921,
          "sha512": "2ad2e2539ceb9c89783655409e013c8171a470fba30d1b54a33a1b8a9a4e8f14ed083565a4bb627255b0552452ea9270816bf5fb69120a453844f1379115f105",
          "sha256": "0a50ad95b71fb118ac02d8282fa51de53d7f3520a133a6270116780897ea94d6",
          "sha1": "510f6aace5ee31e03943b158ba5e17714c4cebb7",
          "md5": "7afa01b9cfe5f8474032d686b4c9ca53"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.8-SNAPSHOT-javadoc.jar",
          "url": "ConnectorAPI-0.1.3.8-SNAPSHOT-javadoc.jar",
          "size": 145783,
          "sha512": "b54785a391fcdc2dc2c664f084a02265bd4ee7e07438159eb879fcf568055f03064ef7aff1a207632451718d43453be8412506ddc45680302ca82183314307db",
          "sha256": "107d938c6513557d371b8fc682b70a6fbbb6cdc5fd3b41e40aad5731c105d991",
          "sha1": "863ab89db32aabc8a16194556fe55f9ae7ba947d",
          "md5": "e91279bfae13a8b4eb8ac263a1fdc68e"
        }
      ]
    }
  ]
}
