{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectorAPI",
    "version": "0.1.3.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.8-SNAPSHOT.jar",
          "url": "ConnectorAPI-0.1.3.8-SNAPSHOT.jar",
          "size": 25804,
          "sha512": "86d266c65bddaae03349c2fbf417b8c61a849723e17ff5a5b25d3fec460ae7881dc7f8f7367df592f8e04944f0b3861a47dec0764b87d258a14dd76137d00159",
          "sha256": "759a5c5efa245c36d494ecd59fd629ad6100eed99405d2beaf56b1ad50345699",
          "sha1": "d4fc1663106cbec72746c2d55aaf2c2617f8421d",
          "md5": "3e2219d54e5f303840e53e47df0d8899"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-base",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-base",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-graphics",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-graphics",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-controls",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-controls",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-fxml",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-fxml",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.8-SNAPSHOT.jar",
          "url": "ConnectorAPI-0.1.3.8-SNAPSHOT.jar",
          "size": 25804,
          "sha512": "86d266c65bddaae03349c2fbf417b8c61a849723e17ff5a5b25d3fec460ae7881dc7f8f7367df592f8e04944f0b3861a47dec0764b87d258a14dd76137d00159",
          "sha256": "759a5c5efa245c36d494ecd59fd629ad6100eed99405d2beaf56b1ad50345699",
          "sha1": "d4fc1663106cbec72746c2d55aaf2c2617f8421d",
          "md5": "3e2219d54e5f303840e53e47df0d8899"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.8-SNAPSHOT-sources.jar",
          "url": "ConnectorAPI-0.1.3.8-SNAPSHOT-sources.jar",
          "size": 14921,
          "sha512": "bc2fc72554ff4cad9a394331de1e208475bdd2a3440a4fc6e4d7940a0d9552d056f81f9486c47d30d674f83d38b6a218039fef381177ccf72db0465fb3aba2d9",
          "sha256": "ffef04b0b00bba1afb3c87fe16ac18181ca3794f96bd4874a708e73b3c01c65f",
          "sha1": "926de1837143cd10ba053409cb7605cdfa8c4ab4",
          "md5": "a77e4bfe71c7d495142d44b5347c09c6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.8-SNAPSHOT-javadoc.jar",
          "url": "ConnectorAPI-0.1.3.8-SNAPSHOT-javadoc.jar",
          "size": 145783,
          "sha512": "dfeef45c1cadecd6301c3244056fe1430fb5abd60354ca9eacd612b3651512ba653039d9e30507de177cd0c24656b9d89f47211171b5680231ea53d890e7a163",
          "sha256": "c5e398cdaff518ee70b01040eac67cd7a133306cbccaf385ca1068991875695b",
          "sha1": "737d0d75dd90bb3e8b478a617bd256b121d4806e",
          "md5": "b88128162338f8ae4ab0d176b6edf2b0"
        }
      ]
    }
  ]
}
