{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectorAPI",
    "version": "0.1.7-STABLE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.7-STABLE.jar",
          "url": "ConnectorAPI-0.1.7-STABLE.jar",
          "size": 25478,
          "sha512": "35d88078c7fa53427d544df933fea3af8d29f2e872cb95511f654dcaebc3fa2b54517a6052df9df2950dc35027b665e986573a1e258d273d2f82dfda64f04f17",
          "sha256": "333a3d5056ae967b6d98774c27f3d335f60bc4ec0b2e6c747317ef1489d08d58",
          "sha1": "097eb9ba5c6ae71906456ba839261f7ce439240e",
          "md5": "80bd2272a3e905484f7383d11d9750c9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-base",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-base",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-graphics",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-graphics",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-controls",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-controls",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-fxml",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-fxml",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "ConnectorAPI-0.1.7-STABLE.jar",
          "url": "ConnectorAPI-0.1.7-STABLE.jar",
          "size": 25478,
          "sha512": "35d88078c7fa53427d544df933fea3af8d29f2e872cb95511f654dcaebc3fa2b54517a6052df9df2950dc35027b665e986573a1e258d273d2f82dfda64f04f17",
          "sha256": "333a3d5056ae967b6d98774c27f3d335f60bc4ec0b2e6c747317ef1489d08d58",
          "sha1": "097eb9ba5c6ae71906456ba839261f7ce439240e",
          "md5": "80bd2272a3e905484f7383d11d9750c9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.7-STABLE-sources.jar",
          "url": "ConnectorAPI-0.1.7-STABLE-sources.jar",
          "size": 14649,
          "sha512": "7bc1f12df41d8435c979a9df3cccefe85bf117be2cd9a13cea26335a7d0c4749fc9f98eaf6c3e78cdbd7962c94ec32147db58a921f7b914a75db4a975f910137",
          "sha256": "1139874e6277db5c7f748e26353b3b5180bc199c35a3159b30128cf0832ee9f8",
          "sha1": "fb56b12e1f0559c910ab01e87bb17c4ae5fb7c99",
          "md5": "74d04b1e5f4e1073b8e72d87b631e6cb"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.7-STABLE-javadoc.jar",
          "url": "ConnectorAPI-0.1.7-STABLE-javadoc.jar",
          "size": 145137,
          "sha512": "1d3d35b61f334ea9453a2931326d0336a26a9fa98bb8d84777315fd4fea060798693f98dc8d896ccd7cacd14c831684ed3c313ac02c1c99da6ecc5b400934837",
          "sha256": "6fb2b8f463eb6836a167c2af145cfcb535aa0b884c97a94fe8b99d76c0170bad",
          "sha1": "313173a316df8166d4cc2356fd7045d4e28041e0",
          "md5": "b779cf799d47a34b73d56475511585a3"
        }
      ]
    }
  ]
}
