{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectorAPI",
    "version": "0.1.7-STABLE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.7-STABLE.jar",
          "url": "ConnectorAPI-0.1.7-STABLE.jar",
          "size": 25478,
          "sha512": "afb7ceda67a364172e0a8393660bd9fc6bc9d3336d73cc0dc1313a2c50f968696ff933ef83df5d5c6f6908cf8e56544f45129cd81ec8b77694303b86819f5089",
          "sha256": "3261a430d4825269534fd8ab0e5f81f3b965712facd6db9aa4dabc3686286841",
          "sha1": "425ee256c666e0e96f9d4d2aacf3ceebdd74714a",
          "md5": "efefb1c261561e86a4ba753ae2f0f5ed"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-base",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-base",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-graphics",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-graphics",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-controls",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-controls",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-fxml",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-fxml",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "ConnectorAPI-0.1.7-STABLE.jar",
          "url": "ConnectorAPI-0.1.7-STABLE.jar",
          "size": 25478,
          "sha512": "afb7ceda67a364172e0a8393660bd9fc6bc9d3336d73cc0dc1313a2c50f968696ff933ef83df5d5c6f6908cf8e56544f45129cd81ec8b77694303b86819f5089",
          "sha256": "3261a430d4825269534fd8ab0e5f81f3b965712facd6db9aa4dabc3686286841",
          "sha1": "425ee256c666e0e96f9d4d2aacf3ceebdd74714a",
          "md5": "efefb1c261561e86a4ba753ae2f0f5ed"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.7-STABLE-sources.jar",
          "url": "ConnectorAPI-0.1.7-STABLE-sources.jar",
          "size": 14649,
          "sha512": "8c13e6f31f8e08df4f94908bb17a1c04d7eaa67f7e4b129ce2b4fa641107b109360f257774c719e8a3e3f1cedb7dcd119bb02b22f807a8a04977a45410658f66",
          "sha256": "44d5dfd13aaddfd89675584599cac709b127b9e18e8a8321d3ceda76edb9b2b2",
          "sha1": "98f0a85c659f5d291b991e11002f3855135fa22f",
          "md5": "fbbecebffe6a36ce3bd939f5ca4d2c67"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.7-STABLE-javadoc.jar",
          "url": "ConnectorAPI-0.1.7-STABLE-javadoc.jar",
          "size": 145137,
          "sha512": "cd6efb94dade19c5f1e745578dc879750855121949c90697968137ba761caa06d16b6b6c332894e2286f5a8e0bc4f45034d4d9546efcf74c4f6520380d1b9033",
          "sha256": "50f13f1f4d537147621e7985e58ab5d6653e3c5343a10172b06468ef8126693f",
          "sha1": "6af65b1371551004848de5b7ad6dd87cbd6d7502",
          "md5": "439aedd2f25ac0cf24ff65c83c382f34"
        }
      ]
    }
  ]
}
