{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectorAPI",
    "version": "0.1.7-STABLE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.7-STABLE.jar",
          "url": "ConnectorAPI-0.1.7-STABLE.jar",
          "size": 25478,
          "sha512": "6e02547e59b0c777b95d37d56ac606a4f578c51ccda27be9d87d41375880fcd93997d2039efee757cddd6e8a3eb1ade65e99aa7541cacc9c92ed9481df8c7791",
          "sha256": "9f91fb0534730735046c571986af11d4089fb53b86826ef731a8af577cc52f6e",
          "sha1": "ed366af6d648ad86491d412e03928265220adc1a",
          "md5": "93f8f16900f04dfbb70b7183adf94fc8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-base",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-base",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-graphics",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-graphics",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-controls",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-controls",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-fxml",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-fxml",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "ConnectorAPI-0.1.7-STABLE.jar",
          "url": "ConnectorAPI-0.1.7-STABLE.jar",
          "size": 25478,
          "sha512": "6e02547e59b0c777b95d37d56ac606a4f578c51ccda27be9d87d41375880fcd93997d2039efee757cddd6e8a3eb1ade65e99aa7541cacc9c92ed9481df8c7791",
          "sha256": "9f91fb0534730735046c571986af11d4089fb53b86826ef731a8af577cc52f6e",
          "sha1": "ed366af6d648ad86491d412e03928265220adc1a",
          "md5": "93f8f16900f04dfbb70b7183adf94fc8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.7-STABLE-sources.jar",
          "url": "ConnectorAPI-0.1.7-STABLE-sources.jar",
          "size": 14649,
          "sha512": "16f77183a1b2aa92c050e9d4271c090ae2533c5dd828713d0293ad7b0b69946fc91540666b1a96c95f8c5c79df3eb9632895fb07fb2113c7b03351b7a767be07",
          "sha256": "fb2ff1c7c2713c2944077354d2fae6ec87966b5de9739549e6ede28ab9c9da82",
          "sha1": "02f1b240b23414643f037b484a2b4f9ca6bdf10f",
          "md5": "d9155d27295778110a74dc93db3113c6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.7-STABLE-javadoc.jar",
          "url": "ConnectorAPI-0.1.7-STABLE-javadoc.jar",
          "size": 145137,
          "sha512": "a17471b0907aee25213b97b512857f1d35c83487aa51f122cd8b9ee206ffd073c032a6392e5c77d3dfd515f91af4a50dfa9a5649c0d811f5c8d3f8542ca78dcb",
          "sha256": "4bbfcc0ff651488c5e793251db9bf645c58b79eda986b020c347256c920f75be",
          "sha1": "bad0dbc147fd1e5628361fccd327419527ec4e43",
          "md5": "6c15dbb111eb2fbebc16859e76cf0d40"
        }
      ]
    }
  ]
}
