{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectorAPI",
    "version": "0.1.3.15-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.15-SNAPSHOT.jar",
          "url": "ConnectorAPI-0.1.3.15-SNAPSHOT.jar",
          "size": 31830,
          "sha512": "220e44d2a3ac951ec2acb44000110c4d82d867ea61e82369b7b8ac3aaa8c0fb324572b313fc82c7c5ca452caf19a5ddaa04792e3fbae09d32edfd560fb6ab03b",
          "sha256": "90977f643036df46082b0c47f931402d35dfabba95ac78baa4361954dfb03b78",
          "sha1": "433cbcc06b3d77d7d94f5a428b258e2e51de80d2",
          "md5": "62b35f1261cc0c3229157b0f038d964f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-base",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-base",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-graphics",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-graphics",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-controls",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-controls",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-fxml",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-fxml",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.15-SNAPSHOT.jar",
          "url": "ConnectorAPI-0.1.3.15-SNAPSHOT.jar",
          "size": 31830,
          "sha512": "220e44d2a3ac951ec2acb44000110c4d82d867ea61e82369b7b8ac3aaa8c0fb324572b313fc82c7c5ca452caf19a5ddaa04792e3fbae09d32edfd560fb6ab03b",
          "sha256": "90977f643036df46082b0c47f931402d35dfabba95ac78baa4361954dfb03b78",
          "sha1": "433cbcc06b3d77d7d94f5a428b258e2e51de80d2",
          "md5": "62b35f1261cc0c3229157b0f038d964f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.15-SNAPSHOT-sources.jar",
          "url": "ConnectorAPI-0.1.3.15-SNAPSHOT-sources.jar",
          "size": 18224,
          "sha512": "0b177fffe2d3d1171548e55b6f82f974c63162b04f3b5ae4f12a72aa774a8fb07c9dca554cc74ece8fb42b9d8d1ff891cf181669c1fd754380b1f133ba768ec3",
          "sha256": "fd8e324cb193670c2c3947a718587ecbaf3ea8b3f3d98de00a7bd321829333fb",
          "sha1": "04112e40643b814dbb8817cadbb416fe800ef8f9",
          "md5": "93b73ce61866360f5ca2a8310bcd47fe"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.15-SNAPSHOT-javadoc.jar",
          "url": "ConnectorAPI-0.1.3.15-SNAPSHOT-javadoc.jar",
          "size": 152550,
          "sha512": "3748aeaf4dfbc9e46d1e2017874350a532f8bc71d8612a14892bc04f24ff8dc40585edf30502abe534fcfae794fa878ca88a12a27212429ee2e306c56da7add9",
          "sha256": "f863712edfcb93cf7e743f5ce896e53926727c3e84e73d0aa310cd5d9ad62f18",
          "sha1": "4f4e7d970a1c5c6392f14d11cf476e3c044af5d7",
          "md5": "f77ce093427d20e6e15b3a9af818243d"
        }
      ]
    }
  ]
}
