{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectLib",
    "version": "0.4.5-STABLE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectLib-0.4.5-STABLE.jar",
          "url": "ConnectLib-0.4.5-STABLE.jar",
          "size": 62818,
          "sha512": "ad302cd5de379c4aa563bf40eced600f8d4c8e571f8bc0da1162d6639d905ac691f3a6bd375c93d4adbb268d616491c756feefd55e318c704231619283a6e42c",
          "sha256": "a44dd67d182d184ce303cb697617ffaf91717a2042c061490bc9b406ae4dcf04",
          "sha1": "918792a4470cc93d452eaadc5f9dd0162bc3be36",
          "md5": "45c4ff41ffba0e06c0969ec61d50f77b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "ConnectLib-0.4.5-STABLE.jar",
          "url": "ConnectLib-0.4.5-STABLE.jar",
          "size": 62818,
          "sha512": "ad302cd5de379c4aa563bf40eced600f8d4c8e571f8bc0da1162d6639d905ac691f3a6bd375c93d4adbb268d616491c756feefd55e318c704231619283a6e42c",
          "sha256": "a44dd67d182d184ce303cb697617ffaf91717a2042c061490bc9b406ae4dcf04",
          "sha1": "918792a4470cc93d452eaadc5f9dd0162bc3be36",
          "md5": "45c4ff41ffba0e06c0969ec61d50f77b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectLib-0.4.5-STABLE-sources.jar",
          "url": "ConnectLib-0.4.5-STABLE-sources.jar",
          "size": 38634,
          "sha512": "8822961632e65eb9eb6e68206b8c8c00f38bc88097234da591f12849b536939adc3e4503658ce3f534facea21de9593712fafa1c340159449b9ed9829bfb1e6d",
          "sha256": "6454ed830b4b7c272d0f0900178a5118ef71090d2ce84c7cd2661cb37e619f88",
          "sha1": "8e9da4c58a48c9e5be62fda3b48a3edff3b11cb5",
          "md5": "2adb5135bd3ad373c8cc8e05a7012f19"
        }
      ]
    }
  ]
}
