{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectorAPI",
    "version": "0.1.3.5-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.5-SNAPSHOT.jar",
          "url": "ConnectorAPI-0.1.3.5-SNAPSHOT.jar",
          "size": 25922,
          "sha512": "35168744da47482b55ea210d84f559a30dc57969bad7e4dcbbcb2c654c17ddcf5602b54a805cd30fdef7125569b0eaa33e544190c346ac6d685d3a0281c7be83",
          "sha256": "33cdd244aa675645b2b3cba6d5bc5c9dd0acff627687466f2b59e77614c8bf99",
          "sha1": "a403d5423d5dc008d0d4fa8fcd3df85522fd0627",
          "md5": "616b6c0e7537032bcf2867078ecd2872"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-base",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-base",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-graphics",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-graphics",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-controls",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-controls",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-fxml",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-fxml",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.5-SNAPSHOT.jar",
          "url": "ConnectorAPI-0.1.3.5-SNAPSHOT.jar",
          "size": 25922,
          "sha512": "35168744da47482b55ea210d84f559a30dc57969bad7e4dcbbcb2c654c17ddcf5602b54a805cd30fdef7125569b0eaa33e544190c346ac6d685d3a0281c7be83",
          "sha256": "33cdd244aa675645b2b3cba6d5bc5c9dd0acff627687466f2b59e77614c8bf99",
          "sha1": "a403d5423d5dc008d0d4fa8fcd3df85522fd0627",
          "md5": "616b6c0e7537032bcf2867078ecd2872"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.5-SNAPSHOT-sources.jar",
          "url": "ConnectorAPI-0.1.3.5-SNAPSHOT-sources.jar",
          "size": 14995,
          "sha512": "d1fd2010519c0bbe1e7d21ac7490e9d5ba0a4372a0525ae2f7bc1786dc045ce5be6d6df0855af3d04c6a5a0da78e933e6bbc43558097f54cbce6de06d343faba",
          "sha256": "8cd6089d4f0c9a86c3f62661a8db3acc0163eefc9e73f3dde6bbcd72ebe2a47b",
          "sha1": "dec6946f220dd32df8dc758b38f8b663369a5d30",
          "md5": "279b9927db2cd27501439c56e4926f13"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.5-SNAPSHOT-javadoc.jar",
          "url": "ConnectorAPI-0.1.3.5-SNAPSHOT-javadoc.jar",
          "size": 145910,
          "sha512": "3439349666d4b7b45691eb1057b171d3f7a26644b4f804468ee060d787287fca139c3609672ecd7e041a28ed6b4b3f2dc3ef65abc72da0411eedc323c4d390eb",
          "sha256": "d1788a3a0a5d8cc2c4d7af3f7ac9413c89343772f48e2616bba1a197fcdbb57a",
          "sha1": "43077aca854cc702cd55ed276aec0b7848c56ce7",
          "md5": "97c733e977bd5f321a88532e60fb6a05"
        }
      ]
    }
  ]
}
