{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectLib",
    "version": "0.4.4-DEV_BUILD",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectLib-0.4.4-DEV_BUILD.jar",
          "url": "ConnectLib-0.4.4-DEV_BUILD.jar",
          "size": 62824,
          "sha512": "6814fc703bcb404ebfeafa6e9d82c33ba12d2ab39a4ed4a470e490dda8e9a5cf154957cc63c1acac89f159c3187443a75e1c22644be7e1b795c01730d3bf87c2",
          "sha256": "a46d1edbdb4e122cf9b61e9a6f3b00ba386a739276db11dd1a70a05bb9862d06",
          "sha1": "ee8babe7cfccc2042f79eb42de93d719286debbe",
          "md5": "513d1509d2fa639a2df73ac6a58d6423"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "ConnectLib-0.4.4-DEV_BUILD.jar",
          "url": "ConnectLib-0.4.4-DEV_BUILD.jar",
          "size": 62824,
          "sha512": "6814fc703bcb404ebfeafa6e9d82c33ba12d2ab39a4ed4a470e490dda8e9a5cf154957cc63c1acac89f159c3187443a75e1c22644be7e1b795c01730d3bf87c2",
          "sha256": "a46d1edbdb4e122cf9b61e9a6f3b00ba386a739276db11dd1a70a05bb9862d06",
          "sha1": "ee8babe7cfccc2042f79eb42de93d719286debbe",
          "md5": "513d1509d2fa639a2df73ac6a58d6423"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectLib-0.4.4-DEV_BUILD-sources.jar",
          "url": "ConnectLib-0.4.4-DEV_BUILD-sources.jar",
          "size": 38637,
          "sha512": "816f3e3c5f0050f746c9448bb786f1f76b47ba11490d9042240ec4819a570d1b6ec773a2e510c26e97dd8d7b47f92ac57da102561848fb8f171561d085b764cc",
          "sha256": "2223e4d8ed564709382cd992879effa74838c27e99ab1c5b2bde10209f06f6c4",
          "sha1": "49ec067531e820e500c2fd889f017f096b99c5f3",
          "md5": "9a1ef4ed4fcb4a12b0499596b5c19c04"
        }
      ]
    }
  ]
}
