{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectorAPI",
    "version": "0.1.3.17.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.17.0-SNAPSHOT.jar",
          "url": "ConnectorAPI-0.1.3.17.0-SNAPSHOT.jar",
          "size": 29263,
          "sha512": "5c7ded318a031e672037442f2f2e82367f6f615c88fe96593b65f5596793dd997b588d164334b63b44d93da842e39b0907238bc6b33e2c3b7361d0610f514f26",
          "sha256": "72caabb9a471cefd1759ee50a51fcedfacd807444d1e1c768ea3a3d71ab3e946",
          "sha1": "bfd40703bf0a18e579b88f33d79a910498e606ba",
          "md5": "2578f2ee2f5db418c06f1bee15b4f555"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-base",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-base",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-graphics",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-graphics",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-controls",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-controls",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-fxml",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-fxml",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.17.0-SNAPSHOT.jar",
          "url": "ConnectorAPI-0.1.3.17.0-SNAPSHOT.jar",
          "size": 29263,
          "sha512": "5c7ded318a031e672037442f2f2e82367f6f615c88fe96593b65f5596793dd997b588d164334b63b44d93da842e39b0907238bc6b33e2c3b7361d0610f514f26",
          "sha256": "72caabb9a471cefd1759ee50a51fcedfacd807444d1e1c768ea3a3d71ab3e946",
          "sha1": "bfd40703bf0a18e579b88f33d79a910498e606ba",
          "md5": "2578f2ee2f5db418c06f1bee15b4f555"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.17.0-SNAPSHOT-sources.jar",
          "url": "ConnectorAPI-0.1.3.17.0-SNAPSHOT-sources.jar",
          "size": 17450,
          "sha512": "eccfb81ffa56644c6449cf09e29a788251c21699fa30d9a038c2cf4e86661844461f4f1914660d94e4fe846efbb337dbc82252744775f690925670715bb8d3bc",
          "sha256": "e6247d06bb3821c90d778ee1ee985313e2e7f9dd768cd9c819c3b8b0bbf35b01",
          "sha1": "d4c2a342e6e2b67b164506f23ac09a44b5caa1c8",
          "md5": "45e5de2053a38d6a37eb44682ab2045e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.17.0-SNAPSHOT-javadoc.jar",
          "url": "ConnectorAPI-0.1.3.17.0-SNAPSHOT-javadoc.jar",
          "size": 152615,
          "sha512": "862b7d0aa271f2fa7322aa9b713eb5864b3960926905eea0a5b4610e3045b4fa5e25828a6b547ed52b8dcb19d67c46b7d0fc778b69a3e74135ad9257f7930c55",
          "sha256": "a7cf053555788621ba9d0532856b9ce0cb1b3452a8cb954dd5691582215facd2",
          "sha1": "9957a261170946fe23ec406e12092c9b12aa2023",
          "md5": "51e76732ad315910d6d84383808625db"
        }
      ]
    }
  ]
}
