{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectorAPI",
    "version": "0.1.9-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.9-SNAPSHOT.jar",
          "url": "ConnectorAPI-0.1.9-SNAPSHOT.jar",
          "size": 31377,
          "sha512": "59a2dec987c132e39c2a24d577f4a6561917319e67fe345af7dd5f9dc0bbd4aee55f497947f899185ef5a633245ff7e314e3d56ecb1137d6ee6ede562a67d5b6",
          "sha256": "b6c415d12cca219cc13e0d07c91590c2a65736a0b2b7524e88d54ac4ed9604ed",
          "sha1": "b6ae41c6451142740f91bedd1a940cb7adacac4c",
          "md5": "5e119ff51fb525aa4d76f641ddaa1a67"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "ConnectorAPI-0.1.9-SNAPSHOT.jar",
          "url": "ConnectorAPI-0.1.9-SNAPSHOT.jar",
          "size": 31377,
          "sha512": "59a2dec987c132e39c2a24d577f4a6561917319e67fe345af7dd5f9dc0bbd4aee55f497947f899185ef5a633245ff7e314e3d56ecb1137d6ee6ede562a67d5b6",
          "sha256": "b6c415d12cca219cc13e0d07c91590c2a65736a0b2b7524e88d54ac4ed9604ed",
          "sha1": "b6ae41c6451142740f91bedd1a940cb7adacac4c",
          "md5": "5e119ff51fb525aa4d76f641ddaa1a67"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.9-SNAPSHOT-sources.jar",
          "url": "ConnectorAPI-0.1.9-SNAPSHOT-sources.jar",
          "size": 17397,
          "sha512": "cd8d445bde7ab73c03ef0a214e8dc0b5de5bc95b23c611be09f71f5190788add958fc612aa9c09890d388cf59b92c74ccc7785ab418f3205476c98f8460cd713",
          "sha256": "f85f8858aefb7cac46aff4dd2826ca67d6368b1314911a64f9d830617eb52adf",
          "sha1": "a04b02e7c1d0205ae74d44b75e5d616d6ad29804",
          "md5": "2b6511d93294c94d86ea188357f365b1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.9-SNAPSHOT-javadoc.jar",
          "url": "ConnectorAPI-0.1.9-SNAPSHOT-javadoc.jar",
          "size": 154096,
          "sha512": "8eeb3074edbe239fc0a17e46e7fa81c2d73b0b712ec26e7c9891b64ded2c43df71a606bbf1331dc1026e87ae422f4ebedce8e8c739d3e76806c4bcb1b78170db",
          "sha256": "1bc212b6d1433b6344eaf07bdecbb9d1a9d93385ba6315ea68b45927360aac87",
          "sha1": "b4b921ac85b44fb4484fcd371082b36446066a1d",
          "md5": "1c774491c2e67d88a2631d469128f98c"
        }
      ]
    }
  ]
}
