{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectorAPI",
    "version": "0.2.2-STABLE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.2.2-STABLE.jar",
          "url": "ConnectorAPI-0.2.2-STABLE.jar",
          "size": 25515,
          "sha512": "fb908cf44d8a061a38c3a16310b4c2f2f5a33a3b2c56ce214ac1b17e8136a344923d14da430f3e60f3cae345bb9e0e8e9d7dc875289c6af4c832f944435c7926",
          "sha256": "a8e1be8529304b1c167d01a65b8261e1251cb690be1a305dba17a711cdc3dacc",
          "sha1": "e7067c36af283792196ffceab991a94afd99d8a9",
          "md5": "af1aae86383ca004c1aff29876a62fc4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "ConnectorAPI-0.2.2-STABLE.jar",
          "url": "ConnectorAPI-0.2.2-STABLE.jar",
          "size": 25515,
          "sha512": "fb908cf44d8a061a38c3a16310b4c2f2f5a33a3b2c56ce214ac1b17e8136a344923d14da430f3e60f3cae345bb9e0e8e9d7dc875289c6af4c832f944435c7926",
          "sha256": "a8e1be8529304b1c167d01a65b8261e1251cb690be1a305dba17a711cdc3dacc",
          "sha1": "e7067c36af283792196ffceab991a94afd99d8a9",
          "md5": "af1aae86383ca004c1aff29876a62fc4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.2.2-STABLE-sources.jar",
          "url": "ConnectorAPI-0.2.2-STABLE-sources.jar",
          "size": 15290,
          "sha512": "a26db484326ce41797d1dc05a680893083bd31a282d1310eebf8dd02481ecbd48381069d8ef389498aa9758e2a370fc5ecf8f6028726ac02c944f27ae117c932",
          "sha256": "c468ac08f40509889ea14ddd6a6a71f60b89c56f2ddffb931780d8fdebfa85cc",
          "sha1": "45ace228a4a7e5728541707d99ad45957cbb6644",
          "md5": "4e6e4ecda654d5efa20abd54cec1b6ea"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.2.2-STABLE-javadoc.jar",
          "url": "ConnectorAPI-0.2.2-STABLE-javadoc.jar",
          "size": 145369,
          "sha512": "7e9d40ff565b6d4cf055d87d8ecfddc45de32dc292266a49a14491e14f44746fc5586276fca45120f8a6e3a54afaa75f59bf7f423111d22a8f00644bff581baa",
          "sha256": "b41f5f79e8008bd2ba43da9e80bd0ae54b7d0b1c471ddeb722e9ed9287f643f5",
          "sha1": "a9cb4f5bc19b0eb2efd8d948bac57bc3a5b95f65",
          "md5": "968fac2c72d232a30d7d0550f2b0088d"
        }
      ]
    }
  ]
}
