{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectorAPI",
    "version": "0.2.2-STABLE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.2.2-STABLE.jar",
          "url": "ConnectorAPI-0.2.2-STABLE.jar",
          "size": 25515,
          "sha512": "a564c6dcaeee5fed677310c18f84045cb6d0a331e23301564f4e2b8e2d52c6c6325b89a7f77968d3ebb35c65a054abc89081da71609413c1030c677e97d3c63f",
          "sha256": "87ce3a8862d1708fa60fb6ee8f3e122918470381cc090a3c0bd6bd47126f72f6",
          "sha1": "5a2194283a5b9e2f2151455be782c204a0712085",
          "md5": "f05d9a0cd1ae5a0a498bf84aa670f995"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "ConnectorAPI-0.2.2-STABLE.jar",
          "url": "ConnectorAPI-0.2.2-STABLE.jar",
          "size": 25515,
          "sha512": "a564c6dcaeee5fed677310c18f84045cb6d0a331e23301564f4e2b8e2d52c6c6325b89a7f77968d3ebb35c65a054abc89081da71609413c1030c677e97d3c63f",
          "sha256": "87ce3a8862d1708fa60fb6ee8f3e122918470381cc090a3c0bd6bd47126f72f6",
          "sha1": "5a2194283a5b9e2f2151455be782c204a0712085",
          "md5": "f05d9a0cd1ae5a0a498bf84aa670f995"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.2.2-STABLE-sources.jar",
          "url": "ConnectorAPI-0.2.2-STABLE-sources.jar",
          "size": 15290,
          "sha512": "91edeee333f04b3b8e907e98c218f5243155028f536414e7f3a0e81ba8e1171fb0ee13dd8bbd2cb7c34337e1912f6612c005519b0d796b95648075bdc73d6c68",
          "sha256": "864f4cc2ff54cd273e24ef2141289d666f4a6e47a808d2eb8b194752040ec5e6",
          "sha1": "4a9c476b8c9415331edcc0ae2cbb2643e89cf42e",
          "md5": "d9a9760855c409ec0a04b074cd488ff0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.2.2-STABLE-javadoc.jar",
          "url": "ConnectorAPI-0.2.2-STABLE-javadoc.jar",
          "size": 145369,
          "sha512": "87e0dcfb50c02dd044074cb49ab093eecc7054f4a81323e66e59a7823653a407b700678a2e6be798b57b54db2e54f140170fc54f4e7f998c8edaa755d5bba4f1",
          "sha256": "11808e519ab1f8bf39a357c6899974264f7e6306bcc55fb4ece5f72e2e08effc",
          "sha1": "d8e21a1498a8b6d6e02a3a9c3743da93422bfc03",
          "md5": "73014320a9c9498a41fb5e51575613b1"
        }
      ]
    }
  ]
}
