{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectorAPI",
    "version": "0.1.3.17-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.17-SNAPSHOT.jar",
          "url": "ConnectorAPI-0.1.3.17-SNAPSHOT.jar",
          "size": 29705,
          "sha512": "91097f859c1fdb362913cae0ffe897b5425f3280bfea0edcf1c6f8a03aef2f0daa452ed94338681fad1e129b9c8a7b748119676c44cc8e00929f257fdf6ae50f",
          "sha256": "2570b468ac2fa124f33d5299fdf9aab827c8263af6198f2b616dfea7960f574a",
          "sha1": "995c3bd8acba5c4de539f3afbb55db921c38ee44",
          "md5": "0fd5bccd3ec23743e9e358456775518d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-base",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-base",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-graphics",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-graphics",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-controls",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-controls",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-fxml",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-fxml",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.17-SNAPSHOT.jar",
          "url": "ConnectorAPI-0.1.3.17-SNAPSHOT.jar",
          "size": 29705,
          "sha512": "91097f859c1fdb362913cae0ffe897b5425f3280bfea0edcf1c6f8a03aef2f0daa452ed94338681fad1e129b9c8a7b748119676c44cc8e00929f257fdf6ae50f",
          "sha256": "2570b468ac2fa124f33d5299fdf9aab827c8263af6198f2b616dfea7960f574a",
          "sha1": "995c3bd8acba5c4de539f3afbb55db921c38ee44",
          "md5": "0fd5bccd3ec23743e9e358456775518d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.17-SNAPSHOT-sources.jar",
          "url": "ConnectorAPI-0.1.3.17-SNAPSHOT-sources.jar",
          "size": 17439,
          "sha512": "785fc1d01b04b931abe7567abc9d5660a9f0802e829fb347844ea73b1b14731b9a0aa2f95e7e81283265d36636abb3964a68ace280252372ab8a93af26ff3b94",
          "sha256": "487471d8237aae5723af8343c177c2d128830c75ad9330ce299402878af5eacf",
          "sha1": "1fd169fa2b6a453f73ef284d4e65ce646044c09d",
          "md5": "596857805f6ddfa8e3cb908492d1566a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.17-SNAPSHOT-javadoc.jar",
          "url": "ConnectorAPI-0.1.3.17-SNAPSHOT-javadoc.jar",
          "size": 152539,
          "sha512": "f1fc41dbf03fee2f48edcf2f885ef8a560293bbbe27e82a576140d6e595d2aa70224411b3f2a330693762d9352f7051a8b2f06c54fe13f88bea1d3a0afd12fc1",
          "sha256": "3904b9796d954f11f10cf120cd4c1b3d4cd67407f891653648d0d467d409b823",
          "sha1": "77828207ee12c1b8504255e3415777be199ec139",
          "md5": "c216feace3a3b50de1f6d0cdce96bf50"
        }
      ]
    }
  ]
}
