{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.sandro642.github",
    "module": "ConnectorAPI",
    "version": "0.1.3.10-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.10-SNAPSHOT.jar",
          "url": "ConnectorAPI-0.1.3.10-SNAPSHOT.jar",
          "size": 29314,
          "sha512": "3e728e761cf173f53163403fbd107b57e2b126a14261542a95adfcec8d6b21d5080bfdf3f27d138dfd7066f982d71bac9a0517441f26ec842c0d85b4eac8d948",
          "sha256": "9a03e6f38b701619cf62fad871364b4ab70e6cdf0af7d7274e13713d6992b3cd",
          "sha1": "3223593eeae8c63066171bff1dea23ddcb53a932",
          "md5": "162acdc52ef075cc683377bffdab44fd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-base",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-base",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-graphics",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-graphics",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-controls",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-controls",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-fxml",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-fxml",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.10-SNAPSHOT.jar",
          "url": "ConnectorAPI-0.1.3.10-SNAPSHOT.jar",
          "size": 29314,
          "sha512": "3e728e761cf173f53163403fbd107b57e2b126a14261542a95adfcec8d6b21d5080bfdf3f27d138dfd7066f982d71bac9a0517441f26ec842c0d85b4eac8d948",
          "sha256": "9a03e6f38b701619cf62fad871364b4ab70e6cdf0af7d7274e13713d6992b3cd",
          "sha1": "3223593eeae8c63066171bff1dea23ddcb53a932",
          "md5": "162acdc52ef075cc683377bffdab44fd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.10-SNAPSHOT-sources.jar",
          "url": "ConnectorAPI-0.1.3.10-SNAPSHOT-sources.jar",
          "size": 17202,
          "sha512": "b070cd9e695c135769d42cdf113979f450efa93191a7d0e71c6845497c3ca1461d00333622eb7109cfa4d624ea7bb8952d7154cad13f1afe23608b2dcdcddf9b",
          "sha256": "b21ac6ca3deb4521b036c23a9a29ab32330488dc5cf1605998d8158c0c9b59a7",
          "sha1": "18a89d597185dc6bdb6acf08eca64ba5c40da733",
          "md5": "8cf7b2433f0115b0eda46df7e3d413b1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ConnectorAPI-0.1.3.10-SNAPSHOT-javadoc.jar",
          "url": "ConnectorAPI-0.1.3.10-SNAPSHOT-javadoc.jar",
          "size": 152432,
          "sha512": "267bd6ce70588e6fe9e0264f76a74be99ce0de630a08a997a982cd6de5a074304d45f0db72f0b01d2e93b9464003f9fcbd0423092e7bd475c346c2383bd075b0",
          "sha256": "9b41a75d6f635bf77ce5e9aa50d5c8d71915dae7a98010c24ca100c5acb5d806",
          "sha1": "960ee7098b11342634b891205a9fbd5059b139f3",
          "md5": "109f34deb3d712b044751663090e157f"
        }
      ]
    }
  ]
}
